### ISSUE TITLE
train dataset contains many duplicates of generated instructions

### ISSUE THREAD

**Issue by markstur** [instructlab/instructlab#1003]
Issue raised by this question/bug/feature:

> Then InstructLab generated 100 new instructions for my skill, and a train dataset of 14,557 examples which contains all duplication of the 100 instructions. Any idea how it worked?

From a quick look at the code... it looks like many duplicates are written to train while generate is looping and trying to get to 100 (default) instructions.  It would make more sense to get the 100 unique instructions before writing out the train dataset.

The tricky part for me is deciding if duplication is a desirable side-effect to create more (redundant) data for training.  So we need to be careful about "fixing" this bug.   But if duplication is desirable, I'd suggest that should be better controlled than the current method (and maybe even left up to `ilab train`).

**Comment by derekhiggins** [comment]
`ilab train` has been fixed to only generate 100 instructions https://github.com/instructlab/instructlab/pull/763

this was almost certainly a bug as the number of duplications was not consistent or controllable in any way
I've seen training data contain 30,000 instructions when asked for 100. Also instructions that were found early in training were duplicated more then instructions that were found later.

I assume the correct way to train with duplicate data would be to bump up the number of epochs ?

**Comment by nathan-weinberg** [comment]
@markstur is this issue still relevant?
