### ISSUE TITLE
Training options only allow for well known/tested HW

### ISSUE THREAD

**Issue by derekhiggins** [instructlab/instructlab#1007]
The instructlab userbase will have hardware that require various training configuration options

e.g. to train on colab I needed to disable bf16 and set 
gradient_checkpointing=true
gradient_accumulation_steps=8

we should add a hidden, (perhaps temporary) argument to allow users to try various training options without
having to change the code

this could eventual be replaced with a happy set of arguments we know would cover all the cases
or code to auto sense the HW and set options based on what it finds.

**Comment by nathan-weinberg** [comment]
Hi @derekhiggins just checking in to see if this issue is still relevant or if it should be closed

**Comment by derekhiggins** [comment]
Closing this, a lot has changed since it was created and its probably no longer relevant
