### ISSUE TITLE
line too long

### ISSUE THREAD

**Issue by nheidloff** [instructlab/instructlab#1028]
Hi, when running ```ilab diff``` I always get "line too long" even when I change one of the existing qna.yaml files and make a line shorter.

**Comment by nheidloff** [comment]
Thanks @bjhargrave. When I run check-yaml.py I get "Cannot load schema file "The attribution.txt file does not exist or is not a file" errors. 

I guess I have to wait until the PR has been merged.

**Comment by bjhargrave** [comment]
The taxonomy repo uses git submodules to access the schema files in the schema repo. Make sure to run `git submodule update --init` in the taxonomy repo folder to pull down the schema.

**Comment by nathan-weinberg** [comment]
@nheidloff closing this for now, if you feel it should remain feel free to reopen with justification
