### ISSUE TITLE
model family for granite update to load the merlinite (llama) template for chat and sdg

### ISSUE THREAD

**Issue by mairin** [instructlab/instructlab#1029]
merlinite and granite are both llama family and can use the merlinite template... if I specify granite as the model family, it should be connected to the merlinite template if I specify granite model family.

**Comment by nathan-weinberg** [comment]
@mairin do you know if this an issue?

**Comment by mairin** [comment]
feels like smtg we fixed a long time ago, but not 100% sure.

**Comment by ktam3** [comment]
Confirmed with the team that this is fixed. Closing
