### ISSUE TITLE
Look into pulling chat templates from huggingface

### ISSUE THREAD

**Issue by russellb** [instructlab/instructlab#1038]
From discussion on #1002 from @bbrowning 

> Should we be using the chat templates as specified in the tokenizer_config.json of each model from HuggingFace instead of hardcoding them? Essentially https://huggingface.co/docs/transformers/main/en/chat_templating#how-do-i-use-chat-templates
>
> This would get us out of having to hardcode the templates at all and instead we'll just use what the model's metadata says it requires. This would mean expecting models to maintain appropriate chat templates, but I believe that's a pretty common practice.

**Comment by bbrowning** [comment]
It looks like llama_cpp_python may automatically do this for us if we just don't pass a chat template in? At least https://github.com/abetlen/llama-cpp-python/tree/v0.2.55?tab=readme-ov-file#chat-completion seems to imply some ability here, but we might need to massage the settings we pass in to tell it to pull the metadata out of the gguf and/or huggingface tokenizer config file.

**Comment by bbrowning** [comment]
Noting that this is still relevant, as we are still hardcoding chat templates per model family at https://github.com/instructlab/instructlab/blob/92dae8665c82ef2611a7b6c92853fe2c425e5aaf/src/instructlab/model/backends/backends.py#L42-L51

**Comment by Spartan-71** [comment]
I would like to work on this issue.

**Comment by nathan-weinberg** [comment]
@Spartan-71 we welcome a PR! i will assign it to you :+1:

**Comment by ktam3** [comment]
@Spartan-71 - what's the status on this?

**Comment by jaideepr97** [comment]
closing as this has been addressed as part of https://github.com/instructlab/instructlab/pull/2592
