### ISSUE TITLE
`ilab train` fails if `ilab serve` is still running

### ISSUE THREAD

**Issue by mairin** [instructlab/instructlab#1070]
@tkatarki noted during testing today that if he is running an `ilab serve` from the `ilab generate` phase, then goes to `ilab train`, the `ilab train` will fail unless he manually stops the `ilab serve.` 

Can someone reproduce this behavior, and if it is reproducible, let's have `ilab train` suggest to the user that they stop `ilab serve` first  (r even automatically stop it) so that `ilab train` succeeds?

**Comment by tiran** [comment]
I have seen the problem before multiple times. In my case it was a memory issue with GPU training. `ilab serve` and `ilab train` consume a lot of memory. My GPU has 20 GB VRAM, which is just enough memory for training. `ilab serve` consumes about 5 - 6 GB VRAM. `ilab train` requires about 18 GB. 18 + 5 > 20

**Comment by ivanbaldo** [comment]
Maybe just document clearly in the README.md tutorial, etc. that `ilab train` doesn't require `ilab serve` running and if low on RAM or VRAM stop de `ilab serve` process first.

**Comment by alimaredia** [comment]
@ivanbaldo How does this look: https://github.com/instructlab/instructlab/pull/1345

**Comment by ivanbaldo** [comment]
In my opinion it should be more prominent.
It's on the Linux section although it should be done also for Mac and GPU accelerated cases.
Maybe it could be moved right under the "Training the model" heading and in a line by itself instead of sharing a paragraph.
That way is more visible and if someone jumps right into "Train the model locally with GPU acceleration" there's a chance at least that has read the general notes first.

**Comment by jaideepr97** [comment]
looking at the README now, we have https://github.com/instructlab/instructlab/blob/main/README.md?plain=1#L622
which I think is pretty clearly worded 

IMO this issue can be closed, unless we want a programmatic solution that kills the serve in the background when train starts (which I think might be excessive)

**Comment by ivanbaldo** [comment]
Yeah I concur with @jaideepr97 , now it's more visible than before, so maybe this can be closed.
I would put it in the general section still, where it says `### 👩‍🏫 Training the model`, at about line 615, before the specific sections by platform or acceleration support...
IMO we shouldn't stop `ilab serve` automatically from `ilab train`...

**Comment by ktam3** [comment]
Expected behavior, already documented. Closing
