### ISSUE TITLE
Update system prompt for additional safety

### ISSUE THREAD

**Issue by mairin** [instructlab/instructlab#1082]
Implement some safety guardrails in the `ilab chat`'s system prompt to minimize the risk of offering inaccurate advice in sensitive domains, such as medical and legal advise, and enhance user trust in the chatbot's reliability.

**Comment by leseb** [comment]
Can you clarify the requirement? Thanks.

**Comment by oindrillac** [comment]
@leseb added some more context to the description, please check

**Comment by leseb** [comment]
> @leseb added some more context to the description, please check

Thank you! Now I understand it better :)

**Comment by mairin** [comment]
@aakankshaduggal did we end up getting this change in? (I seem to recall we did?)

**Comment by aakankshaduggal** [comment]
I believe this was addressed by https://github.com/instructlab/instructlab/pull/1956
