### ISSUE TITLE
Could not copy into data directory: list index out of range

### ISSUE THREAD

**Issue by chenz4027** [instructlab/instructlab#1084]
Initially I thought it's a dup of https://github.com/instructlab/instructlab/issues/608, but I got fewer errors:

```
(venv) ➜  instructlab git:(stable) ilab train
Could not copy into data directory: list index out of range
```

My computer is Apple M1 Pro with 14.4.1 (23E224)

**Comment by leseb** [comment]
Did you run `ilab generate` first? The error message should be clearer btw.
