### ISSUE TITLE
ilab train pytorch support

### ISSUE THREAD

**Issue by cdoern** [instructlab/instructlab#1108]
instructlab-training does not have CPU support. It does now support the MPS device type. This means that once we add CPU support, we can remove `--legacy` and probably the custom MLX support we currently have in `ilab`. The overall functionality of the training library is better and is based off of pytorch.

**Comment by cdoern** [comment]
@anik120 sorry for the delay but here is the train issue based off our convo yesterday about the potential rework

**Comment by ktam3** [comment]
Pulling to .19.0 but more design discussion needed.

cc. @cdoern @jaideepr97 @JamesKunstle

**Comment by ktam3** [comment]
This is resolved in #2247
