### ISSUE TITLE
Add man pages to Python package

### ISSUE THREAD

**Issue by russellb** [instructlab/instructlab#1123]
PR #1032 added the ability to generate man pages. The next step would be to ensure they get packaged.

**Comment by booxter** [comment]
@russellb this is not uncontroversial, see this from click-man: https://github.com/click-contrib/click-man?tab=readme-ov-file#automatic-man-page-installation-with-setuptools-and-pip

```
This approach of installing man pages is problematic for various reasons:
...
```

**Comment by tiran** [comment]
@russellb that is no longer possible with modern Python packaging. Python packages can no longer place files outside the installation context.

**Comment by russellb** [comment]
Oh, darn. Thanks for explaining @booxter and @tiran! Makes sense. I'll close this.
