### ISSUE TITLE
Replace aborted with exited or goodbye when exiting instructlab

### ISSUE THREAD

**Issue by flyingbarron** [instructlab/instructlab#1141]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated worried when I exit instruct lab and get an "Aborted!" message because it seems like something has gone wrong! 

**Describe the solution you'd like**
I'd like the message to be more neutral like "exitted" or friendly like "goodbye" 

**Additional context**
Suggested at RedHat Summit

**Comment by bjhargrave** [comment]
I think this is addressed by #1131 + #1136. These fixes are not yet in a release.

**Comment by leseb** [comment]
Fixes are part of https://github.com/instructlab/instructlab/releases/tag/v0.15.0 now, can we close this? Thanks!

**Comment by flyingbarron** [comment]
Thank you!
