### ISSUE TITLE
host docs somewhere

### ISSUE THREAD

**Issue by makelinux** [instructlab/instructlab#1143]
[README](https://github.com/instructlab/instructlab/blob/main/README.md) is getting bloated, so that even table of contents is hard to observe. It is very cumbersome especially for beginners. See screenshot below.

Number of headings is:
```
grep  '^\s*##' README.md -c
35
```
Shorter ToC that fits the screen is more readable.

Solution: branch subdocuments: Install, Training, host docs somewhere

![image](https://github.com/instructlab/instructlab/assets/2335185/f7dafaae-1b8b-466c-aca4-0cca0b7888aa)

**Comment by leseb** [comment]
I believe most of the README should move to a `https://instructlab.ai/docs`, at one point.

**Comment by makelinux** [comment]
But it will not solve the problem.

**Comment by leseb** [comment]
Yes it will because the install, operation instructions, etc will move to the docs so in the end the README should be smaller. At least that is how I envision things.

**Comment by russellb** [comment]
There's been several past discussions about creating a docs site. It's about time we do that.

**Comment by markstur** [comment]
I think the platform-specific notes are the biggest problem.  We could work on that in the README, but I think let's just hope we can get a docs site that handles that better.   Most folks don't need to see notes about platforms they are not using.

After that it's more a style choice of wordy/lengthy/examples vs need-to-know style. Again better to tackle that in a nicer doc format, right?

**Comment by nathan-weinberg** [comment]
@makelinux could we convert this issue into a "host docs somewhere" issue?
