### ISSUE TITLE
Failed to convert LoRA into a GGUF

### ISSUE THREAD

**Issue by xuliucool** [instructlab/instructlab#1176]
**Describe the bug**
I used notebook Training_a_LoRA_With_Instruct_Lab.ipynb for a model fine-tuning. After training execution, I wanted to convert the LoRA into a GGUF file using llama.cpp. I successfully downloaded llama.cpp and installed requirements in Colab, but when I ran the next command, it returned me an error saying the convert-lora-to-ggml.py file doesn't exist.
 
**To Reproduce**
1. Run "Training_a_LoRA_With_Instruct_Lab.ipynb" step by step in Colab.
2. When it comes to "!python convert-lora-to-ggml.py ../adapter-only" under section "Optional Path 2: Play with Model in llama.cpp", you will see error file convert-lora-to-ggml.py doesn't exit. 

**Expected behavior**
The LoRA can be converted into GGUF successfully without errors.  

**Screenshots**

**Device Info (please complete the following information):**
 - Hardware Specs: ThinkPad P1 Gen 5
 - OS Version: Fedora Linux 39
 - Python Version: Python 3.12.2
 - InstructLab Version: version 0.13.1

**Additional context**
File convert-lora-to-ggml.py was removed from llama.cpp https://github.com/ggerganov/llama.cpp/pull/7204

**Comment by rascasoft** [comment]
Same exact problem here. I've forced the usage of the previous commit in which `convert-lora-to-ggml.py` was still present, changing the step as follows:

```python
# hack sometimes required - solution from https://github.com/googlecolab/colabtools/issues/3409
import locale
locale.getpreferredencoding = lambda: "UTF-8"

!git clone https://github.com/ggerganov/llama.cpp
%cd llama.cpp
!git reset --hard 7bd4ffb78062
!make
!pip install -r requirements.txt
```

And with this in place, the next command:

```python
!python convert-lora-to-ggml.py /content/adapter-only
```

Produces `/content/adapter-only/ggml-adapter-model.bin`, which might be considered an acceptable workaround, but it's far from being optimal.

**Comment by xuliucool** [comment]
> Same exact problem here. I've forced the usage of the previous commit in which `convert-lora-to-ggml.py` was still present, changing the step as follows:
> 
> ```python
> # hack sometimes required - solution from https://github.com/googlecolab/colabtools/issues/3409
> import locale
> locale.getpreferredencoding = lambda: "UTF-8"
> 
> !git clone https://github.com/ggerganov/llama.cpp
> %cd llama.cpp
> !git reset --hard 7bd4ffb78062
> !make
> !pip install -r requirements.txt
> ```
> 
> And with this in place, the next command:
> 
> ```python
> !python convert-lora-to-ggml.py /content/adapter-only
> ```
> 
> Produces `/content/adapter-only/ggml-adapter-model.bin`, which might be considered an acceptable workaround, but it's far from being optimal.

@rascasoft yes this workaround works good! It seems we still need a fix here.

**Comment by ktam3** [comment]
closing as no longer supported

cc. @cdoern @jaideepr97 @alimaredia

**Comment by rascasoft** [comment]
@ktam3 that's interesting to know, I wonder one that is not having AI enabled hardware how is supposed to test or work with instructlab... Do you have any suggestion?

**Comment by ktam3** [comment]
@cdoern @alimaredia @jaideepr97 could you PTAL ^
