### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by williamsun-hha** [instructlab/instructlab#1180]
**Describe the bug**

ilab download from MacBookPro M1 Sonoma 14.5 (23F79)

Got this error when issue 

ilab download
Downloading model from instructlab/merlinite-7b-lab-GGUF@main to models...
Downloading model failed with the following Hugging Face Hub error: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/instructlab/merlinite-7b-lab-GGUF/tree/main?recursive=True&expand=False (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))"), '(Request ID: 08e69502-6471-45ff-b99b-3aceffd21045)')

**To Reproduce**
# Step 0: Deactivate any currently active virtual environment
========
# Step 0: Deactivate any currently active virtual environment
conda deactivate

# Step 1: Create a new Conda environment with Python 3.11
conda create -n instructlab python=3.11 -y

# Step 2: Activate the Conda environment
conda activate instructlab

# Step 3: Install certifi to update CA certificates
pip install certifi

# Step 4: Set SSL_CERT_FILE environment variable to use certifi's certificates
export SSL_CERT_FILE=$(python -m certifi)

# Step 5: Remove the cache for llama_cpp_python (if any)
pip cache remove llama_cpp_python

# Step 6: Install instructlab from the GitHub repository with the specified CMake arguments
pip install git+https://github.com/instructlab/instructlab.git@stable -C cmake.args="-DLLAMA_METAL=on"

# Step 7: Verify the installation
python -c "import instructlab; print('instructlab installed successfully')"

# Step 8: ilab init
ilab init

# Step 9: Download the model (retry the command causing the SSL error)
ilab download
===========

**Expected behavior**

from the instructlab repo

(venv) $ ilab download
Downloading model from instructlab/merlinite-7b-lab-GGUF@main to models...
(venv) $ ls models
merlinite-7b-lab-Q4_K_M.gguf

**Screenshots**

**Device Info (please complete the following information):**
 - Hardware Specs: Apple MacBook Pro:  M1 Pro Chip, 32 GB Memory, 500GB SSD/300GB Free space]
 - OS Version: [Mac OS 14.5]
 - Python Version: [Python 3.11.9]
 - InstructLab Version: [ilab, version 0.15.0]

**Comment by williamsunctp** [comment]
There is an article to fix this issue.  https://stackoverflow.com/questions/71692354/facing-ssl-error-with-huggingface-pretrained-models.  What would be the configuration in Ilab to add the setting in?

**Comment by jammiguelyfish** [comment]
> There is an article to fix this issue. https://stackoverflow.com/questions/71692354/facing-ssl-error-with-huggingface-pretrained-models. What would be the configuration in Ilab to add the setting in?

none of the solutions worked for me
