### ISSUE TITLE
Contextual hints for CLI commands

### ISSUE THREAD

**Issue by mairin** [instructlab/instructlab#1240]
It would be really nice if when using the CLI we gave some contextual hints / guidance to the user about the command structure. Think of it as in-context help. 

An inspiration / model-to-follow would be, for example, if you run systemd with the wrong command order, it suggests the correct one:

```
duffy@fedora:~$ systemctl httpd stop
Unknown command verb 'httpd', did you mean 'stop'?

```

**Comment by cdoern** [comment]
this currently exists: 

```
ilab model char
Usage: ilab model [OPTIONS] COMMAND [ARGS]...
Try 'ilab model --help' for help.

Error: No such command 'char'.

Did you mean one of these?
    chat

```
