### ISSUE TITLE
Number of generated items does not match input

### ISSUE THREAD

**Issue by Felix-Lee14** [instructlab/instructlab#1260]
**Describe the bug**
I ran a ilab generate using the merlinite-7b-lab-Q4_K_M_2024 model.  I used the following command:

ilab generate --num-instructions 10 

And it was completed successfully.

**To Reproduce**

**Expected behavior**
I expected the generated_merlinite-7b-lab-Q4_K_M_2024-06-04T15_44_20.json and the train_merlinite-7b-lab-Q4_K_M_2024-06-04T15_44_20.jsonl files to each have 10 output entries.  However, I got 11 for each.

**Screenshots**
![image](https://github.com/instructlab/instructlab/assets/139508937/3da2ced4-3dea-46ff-bbd6-51767cba8187)

![image](https://github.com/instructlab/instructlab/assets/139508937/53a1189d-c253-41dc-a47f-617a03203301)

**Additional context**

**Comment by chudegao** [comment]
num-instructions is actually the least number of instructions to generate. 
Until it generate satisfied num-instructions  instructions, it will keep generate a set of instructions and keep the ones satisfied. e.g. it already generate 9 satisfied instructions( < 10), it still need generate a set. It generate 2 this time and the 2 are all satisfied. 9+2=11 instructions are kept.

**Comment by chudegao** [comment]
I do not know the exact design, but from the code (the default prompt), I think it's supposed to generate 2. But actually it may generate kinds of number instructions(up to how the llm work based on the prompt).

**Comment by Felix-Lee14** [comment]
Thanks - I think we can close this.
