### ISSUE TITLE
Generating All Synthetic Data

### ISSUE THREAD

**Issue by anniedoris** [instructlab/instructlab#1272]
Hi,
I'm curious if it is possible to access or generate all of the synthetic data that was described in the paper (using all seed examples). If I'm understanding correctly, when we run ```ilab generate```, it generates synthetic data based on just new qna.yamls that we have added. Is there a way that we could generate synthetic data using all of the seed examples (not just the newly added ones?). Thanks!

**Comment by bjhargrave** [comment]
Opening github issues here is not an appropriate way to ask this sort of question. Please use either the slack workspace or the users mail list. https://github.com/instructlab/community/blob/main/Collaboration.md#chat
