### ISSUE TITLE
[v0.16.0] Granite/Mistral models respond with nonesense/hallucinate

### ISSUE THREAD

**Issue by dsanchezseco-ibm** [instructlab/instructlab#1281]
**Describe the bug**
Models like granite or mistral when served with the v0.16.0 hallucinate pretty badly when even prompted with a simple 'hello'. Both for the base and trained models.

**The exact same models work fine with v0.15.1**

**To Reproduce**
1. Serve https://huggingface.co/instructlab/granite-7b-lab-GGUF/blob/main/granite-7b-lab-Q4_K_M.gguf with the v.0.16.0
2. Chat and send a "hello"

**Expected behavior**
Model shouldn't hallucinate that badly

**Screenshots**

<img width="1728" alt="Screenshot 2024-06-06 at 14 40 23" src="https://github.com/instructlab/instructlab/assets/85176020/5fe20b2f-e9a0-45c5-aac7-a5d407bb0877">

**Device Info (please complete the following information):**
 - Hardware Specs: M1, 32GB
 - OS Version: Sonoma 14.5
 - Python Version: Python 3.12.3
 - InstructLab Version: [output of `ilab --version`]

**Additional context**

**Comment by nathan-weinberg** [comment]
I was able to reproduce this

**Comment by gshipley** [comment]
I am also able to reproduce this.

**Comment by jjasghar** [comment]
We have also had a few reports in the #users channel in slack about this too.

**Comment by nathan-weinberg** [comment]
@jjasghar was anyone on Slack able to determine a root cause? I think this bug would be worthy of a `0.16.1` - if we can get a fix I can backport/release that next week

**Comment by nathan-weinberg** [comment]
Bug is also present on the `main` branch

**Comment by dsanchezseco-ibm** [comment]
> We have also had a few reports in the #users channel in slack about this too.

which is the slack channel? cause I only saw one IBM internal one without much going on

**Comment by russellb** [comment]
Thanks for the report.  I used git bisect to narrow it down

It broke here:

> [bf332e84a3ddeaa4150bbeb6fb05648d6d0e8537] option --model-family forces model_family

from #1174 

I'm looking into a fix (or I'll just revert the change if needed)

**Comment by russellb** [comment]
I see the problem and will post a fix shortly.

**Comment by Ardian0x26** [comment]
Yesterday I posted in #users in the InstructLab Community, the error seem to happen because of the wrong model family, I could get merlinite running by setting the model family while serving merlinite, but by default, it didn't even choose the right model family for the merlinite model. I think it uses the wrong template.

**Comment by nathan-weinberg** [comment]
> > We have also had a few reports in the #users channel in slack about this too.
> 
> which is the slack channel? cause I only saw one IBM internal one without much going on

https://github.com/instructlab/community/blob/main/Collaboration.md#chat

**Comment by pilhuhn** [comment]
@Ardian0x26 Yes, exactly
