### ISSUE TITLE
name of the merlinite template

### ISSUE THREAD

**Issue by xukai92** [instructlab/instructlab#1300]
the merlinite template is used by both merlinite and granite (and probably future models trained through instructlab).
perhaps we should rename it here (https://github.com/instructlab/instructlab/blob/main/src/instructlab/server.py#L27) as `instructlab` and make the model-template mapping explicit here (https://github.com/instructlab/instructlab/blob/main/src/instructlab/config.py#L48) as 
```
MODEL_FAMILY_MAPPINGS = {
    "merlinite": "instructlab",
    "granite": "instructlab",
    "mixtral": "mixtral",
}
```
cc @russellb

**Comment by russellb** [comment]
Thank you @xukai92 ! This makes sense to me

**Comment by jaideepr97** [comment]
This one is still relevant, it seems like
