### ISSUE TITLE
Support .yml extension in addition to .yaml for qna files

### ISSUE THREAD

**Issue by gfbarros** [instructlab/instructlab#1306]
**Is your feature request related to a problem? Please describe.**
The fairly common .yml extension for yaml files is quietly ignored when handling new taxonomy qna files. 

**Describe the solution you'd like**
Allow using .yml files for taxonomy.

**Comment by bjhargrave** [comment]
The taxonomy repo requires `qna.yaml`. I think the backend does also. So any change to allow `qna.yml` would need to be properly coordinated through all the stakeholder projects.

**Comment by gfbarros** [comment]
I checked the taxonomy and backed repo files for mentions of yaml and didn't see this. Could you show me where I missed it?

**Comment by bjhargrave** [comment]
> Taxonomy skill files must be a valid [YAML](https://yaml.org/) file named qna.yaml.

https://github.com/instructlab/taxonomy/blob/main/README.md#getting-started-with-skill-contributions



https://github.com/instructlab/taxonomy/blob/main/.github/scripts/check-yaml.py#L129-L133

are some examples.

**Comment by tiran** [comment]
I would prefer if we would stick to a consistent `.yaml` and not add support for `.yml` extension. A second extension adds a very minor UX improvement. Instead of support `.yml`, how about `ilab diff` checks for `.yml`, informs the user to rename the file, and fails?

**Comment by markstur** [comment]
it's debatable because both .yml and .yaml are commonly used, but allowing both can result in a messy taxonomy with both qna.yml and qna.yaml (even in the same dir).  So I felt from the beginning it's just best to allow one and throw an error on the other.  I think it is just a warning.  Is the warning clear enough to make it an easy fix?

Otherwise open to debate about allowing both but inconsistency is bad

**Comment by leseb** [comment]
I think the project should stay consistent with the extensions we support, so I'd prefer to stick with .yaml. For what it's worth, the [YAML project](https://github.com/search?q=org%3Ayaml+.yaml+language%3AYAML&type=code&l=YAML) itself uses .yaml, so let's follow the standard.

**Comment by leseb** [comment]
It looks like the consensus is to not go with another extension and stay we `.yaml`, however @tiran's [proposal](https://github.com/instructlab/instructlab/issues/1306#issuecomment-2158123655) is a good middle-ground.

@gfbarros would you like to take a stab at it? Thanks!

**Comment by gfbarros** [comment]
Yes, I'll take a stab at it later this week. thx.
