### ISSUE TITLE
ilab command redesign follow up: Add DYM functionality back to `ilab`

### ISSUE THREAD

**Issue by cdoern** [instructlab/instructlab#1325]
The new resource groups in `ilab` have dym functionality meaning if you type something like 

`ilab model char` instead of `ilab model chat` it will tell you some valid alternatives. `ilab` itself does not have this due to the custom aliasing class added. Add this back after deprecating the aliases.

follow up to #990

**Comment by nathan-weinberg** [comment]
Can we link the original DYM PR here for reference?
