### ISSUE TITLE
ilab command redesign follow up: switch `ilab model test` to `ilab model evaluate`

### ISSUE THREAD

**Issue by cdoern** [instructlab/instructlab#1327]
`ilab` is adding full rank evaluation in future versions so in the command redesign I switched the command name for test to evaluate. It was deemed that the PR should only move existing code and stay away from functional changes.

switch `ilab test` to `ilab evaluate`

follow up to #990

**Comment by nathan-weinberg** [comment]
This is more of a refactor than an enhancement, going to change the labels as such

**Comment by ktam3** [comment]
closing as this has been implemented in 0.18.3
