### ISSUE TITLE
ilab command redesign follow up: make sure test coverage is complete

### ISSUE THREAD

**Issue by cdoern** [instructlab/instructlab#1328]
In the redesign PR I changes most of the unit tests to use the new cmd structure but did not touch the functional tests. This was purposeful as I wanted to ensure we still supported the old cmd structure. As we remove the aliases and expand this new structure, update the test suite accordingly.

follow up to #990

**Comment by ktam3** [comment]
Moving to backlog bc this needs more details to be able to assign properly

**Comment by ktam3** [comment]
Completed in #2214
