### ISSUE TITLE
Change command usage throughout docs and code to new style

### ISSUE THREAD

**Issue by russellb** [instructlab/instructlab#1331]
This is a follow-up after #990.

There are many places in the code and in docs that should be updated to reflect the new commands. It's not blocking #990 since all the old commands still work.

**Comment by nathan-weinberg** [comment]
@cdoern @kelbrown20 are either of you interested in picking this up?

**Comment by kelbrown20** [comment]
I can work on this, I have a CLI ref already made as well with the new design.
