### ISSUE TITLE
Rename src/instructlab/configuration/ to src/instructlab/config/

### ISSUE THREAD

**Issue by russellb** [instructlab/instructlab#1332]
This is a follow-up to #990.

This PR created a directory - `src/instructlab/configuration/`, but it would be
more consistent with other new directories if it was called
`src/instructlab/config/`.

**Comment by nathan-weinberg** [comment]
@cdoern will you be doing this or is this for anyone to pick up?

**Comment by leseb** [comment]
> @cdoern will you be doing this or is this for anyone to pick up?

No one was assigned so I picked it up!
