### ISSUE TITLE
After 0.16.0, ilab serve and ilab chat are not handling directory names correctly

### ISSUE THREAD

**Issue by gshipley** [instructlab/instructlab#1338]
**Describe the bug**
After ilab 0.16.0, when passing in --model-path on serve and -m, it is not handling the difference between directories with the ./models/modelname and models/modename correctly

**To Reproduce**
on ilab v0.16.1

ilab serve --model-path ./models/merlinite.gguf
ilab chat -m models/merlinite.gguf

Gives an error even though ./models and models/ references the same file.

Also,
ilab serve --model-path ./models/merlinite.gguf
ilab generate --num-instructions 100

fails that the model is not being served. For generate to work now you have to not have ./ in the serve command as follows:
ilab serve --model-path modes/merlinite.gguf
^^ will work.

**Expected behavior**
The CLI should revert back to understanding that ./models and models/ are the same thing

**Screenshots**

**Device Info (please complete the following information):**
 ilab sysinfo
instructlab.version: 0.16.1
sys.version: 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]
sys.platform: darwin
os.name: posix
platform.release: 23.5.0
platform.machine: arm64
torch.version: 2.3.1
torch.backends.cpu.capability: NO AVX
torch.version.cuda: None
torch.version.hip: None
torch.cuda.available: False
torch.backends.cuda.is_built: False
torch.backends.mps.is_built: True
torch.backends.mps.is_available: True
llama_cpp_python.version: 0.2.75
llama_cpp_python.supports_gpu_offload: True

**Comment by ktam3** [comment]
Closing in favor of #1871
