### ISSUE TITLE
`ilab chat` should allow the user to set the temperature

### ISSUE THREAD

**Issue by gshipley** [instructlab/instructlab#1342]
**Is your feature request related to a problem? Please describe.**
Currently ilab chat does not allow for an easy way to set the temperature.

**Describe the solution you'd like**
I would like for the config.yaml to have a default temperature setting of .5 or .6 or whatever to use as a default but allow the user to set their own value. I would also suggest adding a --temperature flag to the ilab chat so the user can set it on a case by case basis.

**Additional context**
I think allowing users to change the temperature value will provide better results when looking for more deterministic and accurate responses.

**Comment by chudegao** [comment]
ilab generate may also need this

**Comment by chudegao** [comment]
BTW, ilab chat support '-gm, --greedy-mode' , it's same as '--temperature 0'.

**Comment by gshipley** [comment]
> ilab generate may also need this
Yeah, from what I can tell in the code, generate uses a temp value of .7 - It should be able to be user configured for advanced users.

**Comment by RacketyWater7** [comment]
I strongly support the idea of allowing users to set the temperature in iLab chat.

    The ability to configure a default temperature in the config.yaml file and a flag like --temperature for individual chats would be very useful.

    As mentioned in the discussion, this would allow for more control over the balance between creativity and accuracy in the generated responses, improving the overall user experience.
