### ISSUE TITLE
README.md CUDA build instructions wrong or confusing

### ISSUE THREAD

**Issue by ivanbaldo** [instructlab/instructlab#1354]
If one simply runs for the first time in a fresh new server:
```sh
python3 -m venv --upgrade-deps venv
source venv/bin/activate
pip cache remove llama_cpp_python
pip install instructlab -C cmake.args="-DLLAMA_CUDA=on"
```
Then both instructlab and llama_cpp_python get installed but the later is not compiled with CUDA support.
I guess maybe this is meant to be run after installing just for the CPU case and then reinstalling only llama_cpp_python and maybe in that case the cmake args go to llama_cpp_python and it all works (didn't test).

Maybe a better suggestion is to just run this instead:
```sh
python3 -m venv --upgrade-deps venv
source venv/bin/activate
pip cache remove llama_cpp_python
CMAKE_ARGS="-DLLAMA_CUDA=on" pip install instructlab
```
This works if executed the first time in a fresh environment and also on reinstalling just llama_cpp_python.

Versions (this is in Google Colab):
- instructlab 0.16.1
- pip 23.1.2
- python 3.10.12
- Ubuntu 22.04.3

**Comment by leseb** [comment]
Using `-C cmake.args` or `CMAKE_ARGS` should give the same results so I'm confused.

@ivanbaldo do you mind showing a bit more logs of your testing procedure and how you validated whether `llama_cpp_python` was compiled or not with CUDA support? Thanks!

**Comment by ivanbaldo** [comment]
Thanks for replying!
Tested with 0.17.0 today and still happens.
Two logs attached to see the differences.
[with_C_parameter.txt](https://github.com/user-attachments/files/15843508/with_C_parameter.txt)
[with_env_variable.txt](https://github.com/user-attachments/files/15843509/with_env_variable.txt)
I can do a PR if you like, just let me know.

**Comment by nathan-weinberg** [comment]
@ivanbaldo would welcome a PR!

**Comment by ivanbaldo** [comment]
You asked you, have it @nathan-weinberg !!!
https://github.com/instructlab/instructlab/pull/2104
Hope it's ok, otherwise happy to correct.
