### ISSUE TITLE
ilab diff after adding a new foundational skill within logical_reasoning not working

### ISSUE THREAD

**Issue by ltacke** [instructlab/instructlab#1367]
**Describe the bug**
After adding a new foundational skill within the path _foundational_skill > reasoning > logical_reasoning_ with the exact same format like all the other qna.yaml that are already there, the ilab diff command does not work. 
I checked multiple times, the config.yaml looks at the correct taxonomy path and when adding knowledge to the taxonomy the ilab diff does take notice of the added data.

**To Reproduce**
1. Follow all the steps of setting up ilab.
2. Add a new qna.yaml within the logical_reasoning folder.
3. Try ilab diff -> It won't recognize the added data to the taxonomy, simply displays that the taxonomy is valid.

**Expected behavior**
Responding with the path to the added qna.yaml in logical_reasoning folder. So you could move on and run ilab generate and ilab train. This is not possible like this.

**Screenshots**
<img width="580" alt="image" src="https://github.com/instructlab/instructlab/assets/90914166/061c4137-abe8-48c7-8285-f539f5f2c6c1">

**Device Info (please complete the following information):**
 - Hardware Specs: Apple M1 Max, 32GB
 - OS Version: macOS Sonoma 14.5
 - Python Version: 3.9.6
 - InstructLab Version:  0.16.1

**Comment by bjhargrave** [comment]
Adding foundational_skills is not supported. Only under compositional_skills and knowledge.

See https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#core-skills
