### ISSUE TITLE
cuda toolkit referenced in linux gpu docs is out of date

### ISSUE THREAD

**Issue by mairin** [instructlab/instructlab#1380]
`sudo dnf -y install cuda-toolkit-12-4 nvtop`

https://github.com/instructlab/instructlab/blob/main/docs/gpu-acceleration.md

12.5 is out. quick docs update needed here.

**Comment by mairin** [comment]
With great pain it appears that perhaps cuda 12.5 isn't actually compatible (at least not with f39 despite vendor's claims) because wow that sucked.

**Comment by bjhargrave** [comment]
You probably need to use CUDA versions supported by PyTorch. The latest PyTorch stable (2.3.1) supports CUDA 12.1. The PyTorch nightly builds now support CUDA 12.4. https://pytorch.org/get-started/locally/
