### ISSUE TITLE
Add upgrade instructions to README.md

### ISSUE THREAD

**Issue by mairin** [instructlab/instructlab#1381]
We don't have instructions on how to upgrade in the cli repo readme nor in the changelogs. It might be a good idea to have a thing in both places.

`pip install instructlab --upgrade` worked for me, but i dont know if i have to upgrade venv as well as a good practice or whatnot

**Comment by sanskriti2005** [comment]
Hello! Can I be assigned to this?

**Comment by leseb** [comment]
> Hello! Can I be assigned to this?

It's all yours now! Thanks!

**Comment by leseb** [comment]
I don't think we need this in the CHANGELOG.md, we just include the `pip install instructlab --upgrade` once we ship a release in https://github.com/instructlab/instructlab/releases.
However having this in the README is important. Thanks!
