### ISSUE TITLE
ilab test fails with default settings - Authentication at Huggingface

### ISSUE THREAD

**Issue by r0llingclouds** [instructlab/instructlab#1406]
**Describe the bug**
The ilab test command should run a comparison between original and fine-tuned model for a set of questions.
However, the test command fails with the following error when trying to run the whole flow with the default settings:
```
Repository Not Found for url: https://huggingface.co/api/models/instructlab-merlinite-7b-lab-mlx-q/revision/main.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

```

**To Reproduce**
1. Download the default model (merlinite)
2. Generate samples (default)
3. Train
4. Run ilab test

**Expected behavior**
The ilab test command should run a comparison between original and fine-tuned model for a set of questions.

**Comment by leseb** [comment]
Dup of https://github.com/instructlab/instructlab/issues/1375, thanks.
