### ISSUE TITLE
Loosen requirements.txt version pins

### ISSUE THREAD

**Issue by RobotSail** [instructlab/instructlab#1422]
Installing this package currently takes an extremely long amount of time (20+ minutes) if you want a specific
version of a package. For example, say `torch==2.1`. 

The error that happens at the commandline is:
```
INFO: pip is looking at multiple versions of peft to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of openai to determine which version is compatible with other requirements. This could take a while.
```

It looks like all of the dependencies in the `requirements.txt` file have an upper bound, which
seems unnecessary and is likely slowing down the resolution times.

We should remove the upper bounds for all the packages except for those that introduce breaking changes.
For those introducing breaking changes, we should instead create an issue to handle them and then have a seprate PR
which upgrades the dependency.

**Comment by bjhargrave** [comment]
This is sort of related to https://github.com/instructlab/dev-docs/issues/77. It would be good to have a general policy for the version ranges of python dependencies.

When we add dependabot support for python dependencies, we may be then able to use `==` versions and let dependabot manage them for us.

**Comment by bjhargrave** [comment]
We are currently using it to manage GitHub actions versions.

**Comment by RobotSail** [comment]
> When we add dependabot support for python dependencies, we may be then able to use == versions and let dependabot manage them for us.

Pinning specific packages with `==` is considered to be a bad practice as it can lead to Python uninstalling incompatible packages, as @dhellmann pointed out in his message here: 
https://github.com/instructlab/training/issues/34#issuecomment-2176071856
