### ISSUE TITLE
ilab test&co for other platforms 

### ISSUE THREAD

**Issue by bog-dan-ro** [instructlab/instructlab#1428]
Right now some features like `test` are available only on M-series, will be great if they will be available for other platforms (Linux cuda/rocm).

**Comment by leseb** [comment]
Dup of https://github.com/instructlab/instructlab/issues/659? In-progress here https://github.com/instructlab/instructlab/pull/1337. Please close if this is a dup or change the title/description for your enhancement request. Thanks!

**Comment by bog-dan-ro** [comment]
It looks like, there is another macos only warning here https://github.com/instructlab/instructlab?tab=readme-ov-file#-serve-the-newly-trained-model but it seems it's a mistake as `ilab serve` worked just fine on Linux. (Didn't test the `ilab convert` though.

**Comment by bog-dan-ro** [comment]
Just checked it:  `ilab convert` is only implemented for macOS with M-series chips for now.
Aren't you using `convert-hf-to-gguf.py` for that job?

**Comment by ktam3** [comment]
Tests for linux implemented, also eval exists. Closing.
