### ISSUE TITLE
Using a LoRa model on top of a gguf model

### ISSUE THREAD

**Issue by jgato** [instructlab/instructlab#1433]
I am trying to follow the instruction to generate/train a model with some custom knowledge. The thing is that I am using CPU and Linux training, that seems to be not working  correctly. The generation looks good, but training produces a model that cannot have a conversation.
So, I did the generation on Linux, and moved generated data with the tutorial to Train a LoRa model on Google Colab:
https://github.com/instructlab/instructlab/blob/main/notebooks/Training_a_LoRA_With_Instruct_Lab.ipynb

But this produces a LoRa model bin (sorry I have very little AI knowledge, so maybe I am wrong with some concepts). I can download it, and I can use 'llama.cpp' together with the original Merlininte gguf model, and seems to work, it can answers me about the new knowledge.
So, I can generate on Linux, train on Colab, and now... how do I use the LoRa model to be served with `ilab serve`?  Do I need to do another transformation? or, how to combine the LoRa with the gguf?

**Comment by jessesightler-redhat** [comment]
It is possible that you are having the issue locally due to the llama_cpp_python version. Upgrading it fixed this issue for me.

**Comment by nathan-weinberg** [comment]
@jgato are you still having the issue?

**Comment by jgato** [comment]
I managed to be able to train the model on Linux/CPU with some of the suggestions provided in other threads :)
