### ISSUE TITLE
Deprecation Notices

### ISSUE THREAD

**Issue by jjasghar** [instructlab/instructlab#1450]
With the changes with `ilab download` and the like, can we get deprecation notices when we use that?

Something i'd imagine is:
```bash
> (venv-instructlab) ilab download
WARNING: The _ilab download_ command has been deprecated in favor of the _ilab model download_, and it will be removed soon.
```

I imagine we can do this with all these commands.

**Comment by leseb** [comment]
Today we have:

```
$ ilab download
You are using an aliased command, this will be deprecated in a future release. Please consider using `ilab model download` instead
```

As well as a note here under 0.17: https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md.

**Comment by nathan-weinberg** [comment]
What do you think @jjasghar?

**Comment by nathan-weinberg** [comment]
Closing due to lack of traction, feel free to reopen
