### ISSUE TITLE
ilab startup time increased after training lib merge

### ISSUE THREAD

**Issue by russellb** [instructlab/instructlab#1467]
On my laptop, `ilab` started in about 1.5s prior to the merge and 3s after. This is from `time ilab --help`.

**Comment by russellb** [comment]
This may have the same fix as #1465 since they're both related to what is imported at startup

**Comment by JamesKunstle** [comment]
Yep I think these two issues are directly linked to imports from the `training` library in `configuration.py` and `train.py`.  When I comment `training` repo stuff out of those files, `ilab` boots immediately and those logs aren't emitted.

**Comment by tiran** [comment]
There are also some more places:

- The import of torch in `train` should be guarded by `if typing.TYPE_CHECKING`.
```
if typing.TYPE_CHECKING:
    import torch
```
- `instructlab.model.serve` needlessly imports `llama_cpp`

I also recommend to add a unit test, so we do not regress. Here is an easy way to dump imports from a subprocess:
```
import json
import subprocess
import sys

modules_txt = subprocess.check_output([sys.executable, "-c", "import sys, json, instructlab.lab; json.dump(sorted(sys.modules), sys.stdout)"], text=True)
modules = json.loads(modules_txt)
```

Other ways are `python3 -v -m instructlab` or `python3 -X importtime -m instructlab`.

**Comment by tiran** [comment]
I got imports down from 5,906 modules and 6.5s to 1,387 imports and 0.8s startup time.

**Comment by tiran** [comment]
PR #1716 speed up the CLI even further. `ilab model train --help` now takes 0.4s instead of 1.6s on my machine.
