### ISSUE TITLE
Use new training code in e2e CI job

### ISSUE THREAD

**Issue by russellb** [instructlab/instructlab#1470]
The e2e CI job test script uses the `--legacy` flag for training, meaning that we are not exercising the new training library. We should fix this so we're testing the new, non-legacy code.

**Comment by russellb** [comment]
https://github.com/instructlab/instructlab/blob/696852ab0dd3f85b1104ebef0aad26299175d3bf/scripts/basic-workflow-tests.sh#L136

**Comment by russellb** [comment]
#1494 is addressing this

**Comment by nathan-weinberg** [comment]
@russellb @cdoern does https://github.com/instructlab/instructlab/pull/1557 fix this? can it be closed?

**Comment by ktam3** [comment]
@nathan-weinberg @cdoern - the reqs for this issue has been done. There are future plans to iterate this and a followup issue will be created. Closing this as done.
