### ISSUE TITLE
long duplicated code in generate, chat, and serve

### ISSUE THREAD

**Issue by makelinux** [instructlab/instructlab#1499]
Copy-pasting code results from poor design and architecture, leading to technical debt and unmaintainable code.

Lines near the start:

src/instructlab/data/generate.py:186:            backend = backends.get(logger, model_path, backend)
src/instructlab/model/chat.py:191:            backend = backends.get(logger, model_path, backend)
src/instructlab/model/serve.py:81:        backend = backends.get(logger, model_path, backend)

Lines near the end:

src/instructlab/data/generate.py:210:            backend_instance = vllm.Server(
src/instructlab/model/chat.py:215:            backend_instance = vllm.Server(
src/instructlab/model/serve.py:112:        backend_instance = vllm.Server(

**Comment by leseb** [comment]
Thanks for opening an issue for this, the code only had a TODO :)
