### ISSUE TITLE
python3-GitPython not found on RHEL

### ISSUE THREAD

**Issue by buckwem** [instructlab/instructlab#1505]
**Describe the bug**

The install instructions for [Installing ilab](https://github.com/instructlab/instructlab?tab=readme-ov-file#-installing-ilab) tools includes python3-GitPython that fails to install.

**To Reproduce**
1. Run `sudo dnf install gcc-c++ gcc make pip python3 python3-devel python3-GitPython`
2. The error shown is
`No match for argument: python3-GitPython`
`Error: Unable to find a match: python3-GitPython`

**Expected behavior**
I would have expected the package to install correctly.

**Screenshots**
N/A

**Device Info (please complete the following information):**
 - Hardware Specs: [Dell XPS15 with 32GB memory.]
 - OS Version: [RHEL9 running using WSL on Windows 11]
 - Python Version: [Python 3.9.18`]
 - InstructLab Version: [ilab, version 0.17.1]
 - hostnamectl
Static hostname: DESKTOP-3793O7S
       Icon name: computer-container
         Chassis: container ☐
      Machine ID: 6bd48cb80ff7401a87436cba210ae712
         Boot ID: 2df5afc0cac54a26b1f6e4978f2d26b0
  Virtualization: wsl
Operating System: Red Hat Enterprise Linux 9.4 (Plow)
     CPE OS Name: cpe:/o:redhat:enterprise_linux:9::baseos
          Kernel: Linux 5.15.153.1-microsoft-standard-WSL2
    Architecture: x86-64

**Additional context**
I think I fixed it by running `pip install GitPython`. That gave a warning and suggested I install using venv.  I am no RHEL expert and wonder if that is the right way to solve the problem.

**Comment by tiran** [comment]
Does anybody know why this dependency was included in the first place? It does not make sense. `dnf install` adds `python3-GitPython` to the global Python installation. We are using a virtual env that does not have access to global packages.

I suggest to update the line to `sudo dnf install gcc-c++ gcc make pip python3.11 python3.11-devel`. The next version of InstructLab requires either 3.10 or 3.11. 3.9 is no longer supported and 3.12 is not supported by some of our dependencies.
