### ISSUE TITLE
HTML tags are not stripped off from the knowledge document

### ISSUE THREAD

**Issue by vincentywdeng** [instructlab/instructlab#1508]
**Describe the bug**
When processing knowledge document, html tags are no stripped. As html tags doesn't contain meaningful information when doing `ilab data generate`. It is better to remove them

**To Reproduce**
1. Follow [Oscars knowledge examples](https://github.com/instructlab/taxonomy?tab=readme-ov-file#knowledge-yaml-examples) which trying to get this [knowledge document(https://github.com/juliadenham/oscars2024_knowledge/blob/main/oscars2024_results.md)
2. Set a break point at https://github.com/instructlab/instructlab/blob/214fe45abd8d0d2db28bf62d414c72b8d5858a48/src/instructlab/utils.py#L537 , you will find html tags are not removed
3. Set break point at [encode_prompt method in sdg](https://github.com/instructlab/sdg/blob/6c9d69a8ff14a443655ee14b2eb7bd9cd0159f50/src/instructlab/sdg/generate_data.py#L139),  the document still contain html tags

**Expected behavior**
The tags should be stripped as it didn't contain meaningful information

**Screenshots**

**Device Info (please complete the following information):**
 - Hardware Specs: Apple M1 Max 32 GB Memory
 - OS Version: Sonoma 14.5
 - Python Version: Python 3.10.13
 - InstructLab Version: 0.17.1.dev113

**Additional context**

**Comment by nathan-weinberg** [comment]
Closing in favor of the SDG repo issue
