### ISSUE TITLE
ilab data generate ignores --model

### ISSUE THREAD

**Issue by Max-Jesch** [instructlab/instructlab#1512]
**Describe the bug**
When I try to do 
`ilab data generate --model models/mixtral-8x7b-instruct-v0.1.Q3_K_M.gguf` 
I get a 
`Failed to determine backend: Failed to determine whether the model is a GGUF format: [Errno 2] No such file or directory: 'models/merlinite-7b-lab-Q4_K_M.gguf'
`

When I try to serve the model with `ilab serve --model-path models/mixtral-8x7b-instruct-v0.1.Q3_K_M.gguf`
everyting works fine

**Screenshots**
Model not being recognised when trying to generate data
![image](https://github.com/instructlab/instructlab/assets/23448917/90999a15-53c9-4411-bfee-14e2a772a1e5)
everything working fine, when serving
![image](https://github.com/instructlab/instructlab/assets/23448917/f69af0fd-2cf8-4944-889b-f73eb5dc028f)

**Device Info (please complete the following information):**
 Google colab L4 instance

**Additional context**

**Comment by nathan-weinberg** [comment]
Can you share the output of `ilab sysinfo` please?

**Comment by Max-Jesch** [comment]
@nathan-weinberg I have nuked the machine by now, so I cannot easily run `ilab sysinfo`. Is there anything particular that you are looking for? I might be able to set the enviroment up again some time in the next days

**Comment by nathan-weinberg** [comment]
@Max-Jesch when you get a chance just share the full output please, thanks!

**Comment by nathan-weinberg** [comment]
Closing due to a lack of traction, feel free to reopen if you wish to revisit
