### ISSUE TITLE
`make verify` became slow

### ISSUE THREAD

**Issue by tiran** [instructlab/instructlab#1525]
**Describe the bug**
@nathan-weinberg add `mypy` to `make verify` in PR #1472. This makes `make verify` very slow.

 You probably didn't know this, because I never documented it. I designed `make verify` to be very fast and with low impact on disk space consumption. Environments like `fastlint` and `ruff` don't install InstructLab, PyTorch, and other packages. The `mypy` target requires a full installation and nearly 2GB disk space.

**To Reproduce**
Run `make verify`

**Expected behavior**
`make verify` should complete in 5 to 10 seconds and not require a full installation of InstructLab. 

**Additional context**

We probably need something like `fastmypy` that works similar to `fastlint`.

**Comment by leseb** [comment]
In the meantime this gets addressed, should we revert 179e4b609352b3bd087b3df8e717dc717bd7ef52? Or was it fixing something critical? @nathan-weinberg?

**Comment by nathan-weinberg** [comment]
Not opposed to reverting if it's causing issues, but I'd prefer to iterate - how hard would it be to implement a `fastmypy` @tiran?

**Comment by nathan-weinberg** [comment]
This is fixed now, `mypy` was moved to `make tests`
