### ISSUE TITLE
refer to the mmlu task constant 

### ISSUE THREAD

**Issue by alinaryan** [instructlab/instructlab#1534]
The default 57 task list for the mmlu eval benchmark needs to be referenced in the cli. Currently it points to a smaller list (for testing purposes).
Convo started in https://github.com/instructlab/instructlab/pull/1369#discussion_r1660048651

**Comment by nathan-weinberg** [comment]
Referenced how exactly? Like we need to expose the list to users?

**Comment by alinaryan** [comment]
@nathan-weinberg referenced by the cli, currently it's pointing to a smaller list used for testing purposes https://github.com/instructlab/instructlab/blob/main/src/instructlab/model/evaluate.py#L98

**Comment by alinaryan** [comment]
Updated the description

**Comment by nathan-weinberg** [comment]
Can this be closed now @alinaryan?
