### ISSUE TITLE
improve error handling and user feedback for `ilab model evaluate`

### ISSUE THREAD

**Issue by cdoern** [instructlab/instructlab#1535]
`ilab model evaluate` currently doesn't have the most responsive error handling or logging in general. Improve this by checking for all possible exceptions and logging during the evaluation process. 

related to #1369

**Comment by nathan-weinberg** [comment]
Related to https://github.com/instructlab/eval/issues/36

**Comment by nathan-weinberg** [comment]
Couple related PRs:
- https://github.com/instructlab/instructlab/pull/1795
- https://github.com/instructlab/instructlab/pull/1870

**Comment by nathan-weinberg** [comment]
Related PRs are merged so I'm closing this, we can iterate with additional followups
