### ISSUE TITLE
Add test cases for `ilab model evaluate` outside of the config

### ISSUE THREAD

**Issue by cdoern** [instructlab/instructlab#1536]
`ilab model evaluate` currently only has tests validating the cfg options. We need to add unit, functional and e2e tests running some form of evaluation.

relates to #1369

**Comment by nathan-weinberg** [comment]
Related to https://github.com/instructlab/instructlab/issues/1540

I think we can use this just for the regular unit and functional tests

**Comment by nathan-weinberg** [comment]
Since https://github.com/instructlab/instructlab/pull/1572 and https://github.com/instructlab/instructlab/pull/1573 have merged I'm going to close this - https://github.com/instructlab/instructlab/issues/1540 can be used to track remaining E2E work
