### ISSUE TITLE
Add `model evaluate` command to `e2e` CI

### ISSUE THREAD

**Issue by russellb** [instructlab/instructlab#1540]
#1369 added a new command, `ilab model evaluate`. It would be great to run this in the `e2e` CI job (or a future one that runs on a larger instance type if that's necessary).

**Comment by danmcp** [comment]
Is there a target on length of time for eval to run?  Best case (with shortcuts to test the flow but not the accuracy) as of now is ~10 mins for the 4 benchmarks.

**Comment by russellb** [comment]
> Is there a target on length of time for eval to run? Best case (with shortcuts to test the flow but not the accuracy) as of now is ~10 mins for the 4 benchmarks.

the job takes 25-30 minutes right now. Another 10 minutes doesn't seem terrible to me. I know others may feel differently.

I expect we're going to end up with some variants of `e2e`. Maybe the one that runs on every commit in every PR only runs one variant (or whatever you decide is the most minimal configuration that still exercises the most important integration points)

more extensive variants running on larger machines may end up taking longer because we're running more extensive features (full SDG vs simple SDG for example), so there, that's where we could test all variants.

i haven't looked at eval enough to make any kind of informed recommendation. I guess I'm saying we have some flexibility to test different variations, so it'd help to think of what's the minimal thing vs. the full thing you'd test

**Comment by nathan-weinberg** [comment]
Related to https://github.com/instructlab/eval/issues/12 (we'll want some level of checking on both sides)

**Comment by russellb** [comment]
We merged #1369 though there is still some ongoing work needed

* test more benchmarks
* test the output of `ilab model train` instead of model pulled from huggingface

**Comment by alimaredia** [comment]
Closing this as it is covered in the more encompassing https://github.com/instructlab/instructlab/issues/1642
