### ISSUE TITLE
generate: Allow custom data generation pipeline extensions

### ISSUE THREAD

**Issue by russellb** [instructlab/instructlab#1546]
the `instructlab/sdg` is introducing more extensive data generation pipelines. These pipelines are defined in a format that's possible to express as configuration. To allow some customizations, we should allow a configuration to be provided that adds additional custom steps on the end of our built-in generation pipeline.

It could be something like

```sh
ilab data generate --pipeline full --pipeline-extend path/to/custom_pipeline_steps.yaml
```

One complication here is that custom pipelines may have more unique model serving requirements. Instead of serving just one model, we may need to serve a model, as well as optional a model with an adapter. We need to intelligently launch the model server based on some additional configuration here. Maybe it's something we can infer from the custom pipeline config, or maybe we need some new options to express the needs.  Automatic is certainly preferred if possible.

**Comment by markmc** [comment]
See instructlab/sdg#86 for an implementation of the file format. The design doc has details of the proposed CLI integration

**Comment by russellb** [comment]
This requirement was satisfied a bit differently than originally described here.

* design: https://github.com/instructlab/dev-docs/blob/main/docs/sdg/sdg-flow-yaml.md#cli-integration
* code: https://github.com/instructlab/instructlab/pull/1668
