### ISSUE TITLE
ilab init should default to "yes" for cloning down taxonomy if not existing

### ISSUE THREAD

**Issue by paulczar** [instructlab/instructlab#1547]
when running `ilab init`. it will ask to download the taxonomy from git if its not already there,  the default response is no.  We should default to YES to improve the new user experience.  (also the repeat user who just blindly hits "enter" every time, not naming any names @jjasghar).

in my opinion this will help the new user experience.

**Comment by nathan-weinberg** [comment]
I feel like this is how it used to work? But maybe I am wrong
