### ISSUE TITLE
No name 'run_training' in module 'instructlab.training'

### ISSUE THREAD

**Issue by RobotSail** [instructlab/instructlab#1550]
For some reason, the latest version of instructlab-training breaks when being imported on some machines.
For example, the CI is currently getting the error:

```
Error: src/instructlab/model/train.py:11:0: E0611: No name 'run_training' in module 'instructlab.training' (no-name-in-module)
```

**Comment by RobotSail** [comment]
Still getting the error after rebasing on the latest main branch:
```
  Error: src/instructlab/model/train.py:10:0: E0611: No name 'run_training' in module 'instructlab.training' (no-name-in-module)
```

See: https://github.com/instructlab/instructlab/actions/runs/9751642425/job/26913659312?pr=1471#step:8:23

**Comment by nathan-weinberg** [comment]
@RobotSail i looked at your PR and the reason it's still failing is this change got overriden as part of your rebase
![image](https://github.com/instructlab/instructlab/assets/31703736/930e9cad-4b1d-441b-973e-4da23df3b49d)
Please fix this and if you longer see the problem reclose this issue, thanks!

**Comment by RobotSail** [comment]
@nathan-weinberg Yep, I realized that at the end of day but didn't get a chance to close this. Doing it now.
