### ISSUE TITLE
Evaluate hangs with wrong serving options

### ISSUE THREAD

**Issue by danmcp** [instructlab/instructlab#1555]
**Describe the bug**
If you pass a model which doesn't work with the selected serving backend, the cli hangs with no feedback to the user

**To Reproduce**
1. Set serving backend to vllm in config.yaml
2. Run evaluate with a gguf model: ilab model evaluate --model models/merlinite-7b-lab-Q4_K_M.gguf --judge-model models/merlinite-7b-lab-Q4_K_M.gguf --benchmark mt_bench

**Expected behavior**
Error indicating the model type wasn't appropriate for the serving backend

**Device Info (please complete the following information):**
N/A

**Additional context**
The same will happen trying to use a safetensors model with llama-cpp

**Comment by nathan-weinberg** [comment]
@danmcp is this still an issue?

**Comment by danmcp** [comment]
No!

Fixed with: https://github.com/instructlab/instructlab/pull/1969

After already being made much better with backend auto detection
