### ISSUE TITLE
Train the model in the cloud

### ISSUE THREAD

**Issue by naina1S** [instructlab/instructlab#1574]
In Training_a_LoRA_With_Instruct_Lab.ipynb, while converting LORA to gguf, all the required files are not getting downloaded and thus in the next cell "!python convert-lora-to-ggml.py ../adapter-only" getting file not found error 

<img width="1329" alt="image" src="https://github.com/instructlab/instructlab/assets/94594164/9d207a7b-132f-442c-86e1-436fc7bb83af">

**Comment by nathan-weinberg** [comment]
@naina1S can you update the name of the bug to more accurately reflect the actual problem?

**Comment by nathan-weinberg** [comment]
Closing due to a lack of traction, feel free to reopen if it's still an issue
