### ISSUE TITLE
Instantiation of defaults is required at import-time

### ISSUE THREAD

**Issue by RobotSail** [instructlab/instructlab#1582]
Presently, the default variables defined in the `configuration.py` are set at the top-level.
This is an issue because it means that they are defined at import-time. 

The reason this is a problem is that when we switch to a dedicated config/storage directory structure, we rely on environment
variables to set our defaults. For example, `ilab model serve` relies on a variable called `DEFAULT_MODEL_PATH`, which is set using `XDG_DATA_HOME` in the [new version](https://github.com/instructlab/instructlab/pull/1471).

When we run unit tests, for example like those in [test_lab_init.py](https://github.com/instructlab/instructlab/blob/main/tests/test_lab_init.py), we import `ilab` and then invoke running it with `ilab init`. 
This means that `ilab init` (and other commands) will receive the wrong defaults.

**Comment by RobotSail** [comment]
I was able to resolve this by lazy-loading the defaults in pr #1471

**Comment by leseb** [comment]
> I was able to resolve this by lazy-loading the defaults in pr #1471

Should we close this then?

**Comment by nathan-weinberg** [comment]
Closing this, @RobotSail feel free to reopen if it's still an issue

**Comment by RobotSail** [comment]
This is old, thanks for closing this @nathan-weinberg !
