### ISSUE TITLE
E2E - add coverage for multiple taxonomy leaf nodes 

### ISSUE THREAD

**Issue by russellb** [instructlab/instructlab#1599]
Current e2e tests one new taxonomy node at a time. Need to test running them through together to have caught this bug: https://github.com/instructlab/sdg/pull/85

the current e2e behavior was necessary with the old code path to make sure we exercised all taxonomy types. With the new version in the library, we don’t need to worry about that and can run all 3 into a single generate run

**Comment by nathan-weinberg** [comment]
@russellb do you still intend on doing this? if not is there someone else from SDG that can take this on?

**Comment by nathan-weinberg** [comment]
@danmcp @alimaredia i think the large job is currently testing 3 new leaf nodes no? is this one done?

**Comment by alimaredia** [comment]
Yes, I'd say this is done. The large job is currently testing knowledge, free form skills, and grounded skills.
