### ISSUE TITLE
Will prompt file path still available after sdg package change?

### ISSUE THREAD

**Issue by SamYuan1990** [instructlab/instructlab#1618]
Ref to config.yaml for release v0.17.1 I know that we can have a prompt.txt file(following config.yaml) to change the prompt which used for SDG process.
But I had check the main branch, https://github.com/instructlab/instructlab/blob/9afa4da2979fd60714d3185819838163faafc9fc/src/instructlab/data/generate.py#L205 it seems we passed prompt file path at line 205 but seems https://github.com/instructlab/sdg/blob/main/src/instructlab/sdg/generate_data.py is not used for prompt_file_path.

so, does it means after v0.17.1 we will not allow for customer prompt and we just have one prompt as below?
https://github.com/instructlab/sdg/blob/main/src/instructlab/sdg/default_flows.py#L18

**Comment by russellb** [comment]
It will actually be much more configurable than before, but it's still a work in progress. The next release will have a very different SDG implementation.

As for what configuration will look like, take a look here: https://github.com/instructlab/dev-docs/pull/109

**Comment by russellb** [comment]
Feedback on that design or the corresponding implementation PRs would be great! Otherwise, I think I've answered the question here so I'm going to close the issue. Feel free to reopen if needed.
