### ISSUE TITLE
Ensure that statically installed ilab is uninstalled properly after testing

### ISSUE THREAD

**Issue by RobotSail** [instructlab/instructlab#1641]
Currently in the `scripts/functional-tests.sh` file (and `scripts/basic-workflow-tests.sh` file too I believe, we always install `ilab` statically via `pip install .`.

While this allows us to validate that our code works correctly on what the end users will be running, this creates issues during development where unless properly cleaned up, the following happens:

1. The local `ilab` binary will point to the static set of files and will not reflect any changes made during development
1. Lanaguage servers incorrectly point to the static instructlab packages that live under `venv/lib/python3.X/site-packages/instructlab` and thus do not refactor correctly from the IDE.

To reproduce this issue, please install instructlab statically via `pip install .` and then attempt to rename one of the property names in the `DEFAULTS` object  in `configuration.py`. You will find that old symbols still exist throughout the project. Following through to their definition will then lead you to their site-packages installation.

To resolve this issue, we need to ensure that we properly cleanup all instructlab files after performing a `pip install .` anywhere during testing.

**Comment by leseb** [comment]
`pip install .` was removed in https://github.com/instructlab/instructlab/pull/1471. Is it still valid?

**Comment by RobotSail** [comment]
@leseb Oh whoops, I'm not sure how that was missed in the PR. We should definitely still have the `pip install .` line there.

**Comment by RobotSail** [comment]
@leseb  PR up to revert that change is here: https://github.com/instructlab/instructlab/pull/1781
