### ISSUE TITLE
Add MMLU-Branch, MT-Bench, and MT-Bench-Branch into E2E CI

### ISSUE THREAD

**Issue by alimaredia** [instructlab/instructlab#1643]
In `basic-worklfow-tests.sh` ilab is only running the MMLU model evaluation. MMLU-Branch, MT-Bench, and MT-Bench-Branch need to be added to `test_evaluate()`.

**Comment by nathan-weinberg** [comment]
Happy to help y'all with this if you want

**Comment by alinaryan** [comment]
Started in #1676
