### ISSUE TITLE
Training CI cleanup catch-all

### ISSUE THREAD

**Issue by cdoern** [instructlab/instructlab#1655]
Most items from review discussion on #1557 

- [ ] fix `FULL_TRAIN` so that training does not run twice on when FULL_TRAIN is true
- [ ] establish if re-installation of deepspeed is necessary and if it is a fix in the CLI or in the training repo
- [ ] remove packaging installation in the e2e workflow. Figure out why it is causing failures since it is a requirement in training repo
- [ ] update training-lib based training to do training based on the output of `ilab data generate` instead of a file checked in to the tree - `scripts/test-data/train_all_pruned_SDG.jsonl`
- [ ] update `docs/ci.md` to reflect where the training-lib is used

**Comment by nathan-weinberg** [comment]
@cdoern did https://github.com/instructlab/instructlab/pull/1557 fix this?

**Comment by cdoern** [comment]
@nathan-weinberg no this should be handled as part of the CI cleanup that I think @alimaredia is working on
