### ISSUE TITLE
Document new file locations and use of platform directories

### ISSUE THREAD

**Issue by tiran** [instructlab/instructlab#1660]
**Describe the bug**
https://github.com/instructlab/instructlab/pull/1471 changed the location of files to use XDG on Linux and platform directories on macOS. This is a breaking change and behavior change that needs to be documented. PR 1471 did not update the changelog and other documentation to explain the behavior

**Comment by romfreiman** [comment]
lets take bootc upgrade into consideration. cc @tsorya

**Comment by RobotSail** [comment]
My bad - it looks like I missed the changelog update in that PR. I'll create a follow-up.
