### ISSUE TITLE
evaluate: consider renaming --sdg-path to --tasks-dir or similar

### ISSUE THREAD

**Issue by markmc** [instructlab/instructlab#1663]
This `model evaluate` option:

```
@click.option(
    "--sdg-path",
    type=click.Path(),
    cls=clickext.ConfigOption,
    config_sections="mmlu_branch",
    help="Path where all the MMLU Branch tasks are stored. Needed for running mmlu_branch.",
)
```

has nothing to do with the `instructlab.sdg` library, right? It's a directory that contains lm_eval tasks config files

This is pretty confusing, since the sdg library will have its own directory full of config files that is completely unrelated

I think it would be good to change to `--lm-eval-tasks-dir` or similar to avoid confusion

@danmcp

**Comment by danmcp** [comment]
I had been considering whether this should be renamed to something like --generated-tasks-path but hadn't thought about putting lm-eval in the name since the format isn't specific to lm-eval and we could potentially change that dependency and still implement mmlu.

@alimaredia @alinaryan

**Comment by alinaryan** [comment]
+1 for --tasks-dir

**Comment by alimaredia** [comment]
--tasks-dir seems fine with me.
