### ISSUE TITLE
llama_cpp_python is built without hardware acceleration

### ISSUE THREAD

**Issue by Fianax** [instructlab/instructlab#1664]
hello, I have installed instructlab on both my local computer and on a google colab and I have had problems using ilab data generated.

On the google colab I have installed it like this:
```
!python -m venv --upgrade-deps venv
!source venv/bin/activate
!pip cache remove llama_cpp_python
!pip install instructlab \
   -C cmake.args="-DLLAMA_CUDA=on" \
   -C cmake.args="-DLLAMA_NATIVE=off"
```

and with this execution I check that I have cuda enabled:
```
import torch

print(torch.zeros(1).cuda())
print(torch.cuda.is_available())

torch.cuda.empty_cache()
```

But when I run `ilab data generate` with a valid taxonomy, it tells me:
```
llama_cpp_python is built without hardware acceleration. ilab generate will be very slow.
```

I managed to compile it separately with this command:
`!pip install --upgrade --force-reinstall --no-cache-dir llama-cpp-python -C cmake.args="-DGGML_CUDA=on"`

but then the `ilab data generate` gives me other compatibility failures.
How can I fix it.

PS: My local computer has a nvidia RTX 2060

**Comment by tiran** [comment]
RTX 2060 may have insufficient memory and insufficient CUDA compute level to run data generation.

**Comment by Fianax** [comment]
Thank you.
And in a google colab 'T4 GPU'???

**Comment by noelo** [comment]
I had the same issue with hardware acceleration not being detected and changing the cmake flags to CMAKE_ARGS="-DGGML_CUDA=on" fixed the issue

**Comment by nathan-weinberg** [comment]
@Fianax is still an issue or can it be closed?

**Comment by Fianax** [comment]
Yes, and thank for the help
