### ISSUE TITLE
`ilab model download` needs to be able to pull from different types of registires

### ISSUE THREAD

**Issue by cdoern** [instructlab/instructlab#1687]
Currently `ilab model download` can only pull safetensors and gguf models from HuggingFace

we need to support multiple types of registries namely OCI registries. This will entail adding new cfg entries and flags for keys, auth, etc.

This needs some investigation, anyone feel free to chime in!!!

**Comment by cdoern** [comment]
@n1hility do you have a working branch for this? @alimaredia mentioned you might

**Comment by n1hility** [comment]
@cdoern not yet, unfortunately I was hung up on vllm / ci related work, but was planning to implement OCI artifact fetching early next week (and hopefully finding some time in the weekend).  

The implementation I had in mind is that we recognize oci registry url syntax (e.g. docker://quay.io/foo/model), which  for an initial implementation would then delegate to skopeo (expected installed on the system) as a helper to do a clone to a staing area in oci directory format (supports resumption and so on), which we could then post process to relocate or link the files. There was another option I had in mind to write a containers/images client where we could make the output format more closely resemble HF output and also be able to do everything inline, but with limited time on the roadmap, the skopeo route is simpler.  In the future the containers projects are looking to add direct support for OCI artifact downloads.

Happy to collaborate on this if you are interested. BTW even though I'm assuming auto resolution by URL, it sounds like you might be thinking about a config directed short name policy, which is also a good idea. Maybe we can sync on chat next week sometime?

**Comment by romfreiman** [comment]
I think as part of it, https://github.com/instructlab/instructlab/issues/1705 should be addressed as well?
