### ISSUE TITLE
SDG path as an input to Eval mmlu_branch e2e

### ISSUE THREAD

**Issue by alinaryan** [instructlab/instructlab#1698]
currently the sdg path is just a path that lives in ilab: https://github.com/instructlab/instructlab/pull/1676/files#diff-371efab14255b4753e32f13f159c38b02be3db7fe06f4a0d29fa7e3292f17d7bR270

Confirm with SDG what the path will actually be, and open a pr to adjust the path

**Comment by alinaryan** [comment]
cc: @aakankshaduggal

**Comment by nathan-weinberg** [comment]
@alinaryan @alimaredia Is this separate from https://github.com/instructlab/instructlab/issues/1642?

**Comment by alimaredia** [comment]
No it's not, I'm going to go ahead and close this.
