### ISSUE TITLE
PR 1653: ilab creates and writes to file on every invocation

### ISSUE THREAD

**Issue by tiran** [instructlab/instructlab#1704]
**Describe the bug**
PR #1653 added code, which causes `ilab` to always create or write to a file on every invocation of the CLI. Even `--help` on subcommands creates and writes to the file.

**To Reproduce**
```
$ strace -e openat ilab config --help 2>&1 | grep O_WRONLY
openat(AT_FDCWD, "/home/heimes/.local/share/instructlab/internal/train_configuration/additional/additional_args.yaml", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 3
```

**Expected behavior**
`ilab` should not create a file or write to files on startup.

**Additional context**
Suggestion:
- if the content of the JSON file is static, then the data should be included as a JSON file in the project as a project resource
- if the content is dynamic, then creation and write should be limited to execution of a subcommand. The content should be written to a temporary file or to the user cache directory. The user data directory is the wrong directory for the purpose.

**update**

Here is are better reproducers. 
```console
$ HOME=/dev/null ilab config --help
Traceback (most recent call last):
...
NotADirectoryError: [Errno 20] Not a directory: '/dev/null/.cache'
```

```console
$ rm -rf /tmp/instructlab/
$ HOME=/tmp/instructlab ilab config --help
$ if [ -d /tmp/instructlab/ ]; then echo "ERROR: --help created a directory"; fi
ERROR: --help created a directory
```

**Comment by cdoern** [comment]
this should probably be in 0.18.0. I can fix this pretty quick

**Comment by tiran** [comment]
@cdoern I have updated the ticket with more reproducers

**Comment by juliadenham** [comment]
Just looked into this and I agree that we shouldn't be creating or writing to a file every time an ilab command is run.  I synced with @cdoern on this and he will look into the code!
