### ISSUE TITLE
Wrong warning message from `ilab config init`

### ISSUE THREAD

**Issue by tiran** [instructlab/instructlab#1706]
**Describe the bug**
`ilab config init` prints this warning when the config file exists
```
Found /home/heimes/.config/instructlab/config.yaml in the current directory, do you still want to continue?`
```
`/home/heimes/.config/instructlab` is not the current directory. The warning was not updated as part of PR #1471 

**To Reproduce**
`ilab config init`

**Expected behavior**
Correct warning message

**Comment by nathan-weinberg** [comment]
This has been fixed as of `0.18.2`
```bash
[nathan@nathan-redhat ~]$ ilab config init
Found /home/nathan/.config/instructlab/config.yaml, do you still want to continue? [y/N]:
```
