### ISSUE TITLE
Reconsider default logging format and logging format option

### ISSUE THREAD

**Issue by tiran** [instructlab/instructlab#1720]
**Is your feature request related to a problem? Please describe.**
InstructLab has a hard-coded log format:

https://github.com/instructlab/instructlab/blob/49622efe32233b4da9fcd4978a8cac6a3a0d506f/src/instructlab/log.py#L7-L9

I see two problems with the approach:

- The log source information is not very useful and makes it hard to understand which library or part of the stack is emitting the log entry.
- The output has a hard-coded time stamp. For integration with systemd, journald, or rsyslog, we don't want to have a time stamp in log line. Journald and others already include time stamps.

The format elements `%(filename)s:%(lineno)d: %(funcName)s:` print the basename of the file (without directory), the line number, and the function name. The file name is not unique. Our dependencies have two files named `connectionpool.py` and three files named `_api.py`. It's impossible to say which messages are coming from `httpx`, `httpcore`, `urllib3`, or `filelock` package at first glance.

```console
$ ilab -vv model download
DEBUG 2024-07-15 16:01:20,501 _http.py:59: add_headers: Request de6cab31-27f2-4fd9-807a-c6a2910d178c: GET https://huggingface.co/api/models/instructlab/merlinite-7b-lab-GGUF/tree/main?recursive=True&expand=False (authenticated: False)
DEBUG 2024-07-15 16:01:20,502 connectionpool.py:1051: _new_conn: Starting new HTTPS connection (1): huggingface.co:443
DEBUG 2024-07-15 16:01:20,637 connectionpool.py:546: _make_request: https://huggingface.co:443 "GET /api/models/instructlab/merlinite-7b-lab-GGUF/tree/main?recursive=True&expand=False HTTP/11" 200 531
DEBUG 2024-07-15 16:01:20,638 _api.py:331: acquire: Attempting to acquire lock 140579829828624 on /home/heimes/.local/share/instructlab/models/.huggingface/.gitignore.lock
DEBUG 2024-07-15 16:01:20,638 _api.py:334: acquire: Lock 140579829828624 acquired on /home/heimes/.local/share/instructlab/models/.huggingface/.gitignore.lock
```

**Describe the solution you'd like**

- Add an option to `config.yaml` to set the log file format. That will allow users to customize logging, e.g. to drop the time stamp for journald.
- Default to `%(name):` instead of `%(filename)s:%(lineno)d: %(funcName)s:`. This logs the name of the logger, which is far more useful to understand log entries:

```
DEBUG 2024-07-15 16:15:22,154 huggingface_hub.utils._http: Request e6c766c4-0996-49d4-b094-0a5c7e7edebe: GET https://huggingface.co/api/models/instructlab/merlinite-7b-lab-GGUF/tree/main?recursive=True&expand=False (authenticated: False)
DEBUG 2024-07-15 16:15:22,154 urllib3.connectionpool: Starting new HTTPS connection (1): huggingface.co:443
DEBUG 2024-07-15 16:15:22,294 urllib3.connectionpool: https://huggingface.co:443 "GET /api/models/instructlab/merlinite-7b-lab-GGUF/tree/main?recursive=True&expand=False HTTP/11" 200 531
DEBUG 2024-07-15 16:15:22,298 filelock: Attempting to acquire lock 140648683333072 on /home/heimes/.local/share/instructlab/models/.huggingface/download/merlinite-7b-lab-Q4_K_M.gguf.lock
DEBUG 2024-07-15 16:15:22,299 filelock: Lock 140648683333072 acquired on /home/heimes/.local/share/instructlab/models/.huggingface/download/merlinite-7b-lab-Q4_K_M.gguf.lock
```

**Comment by leseb** [comment]
Almost fixed with https://github.com/instructlab/instructlab/pull/1741
