### ISSUE TITLE
should annotate the types of `evaluate.py:launch_server`

### ISSUE THREAD

**Issue by JamesKunstle** [instructlab/instructlab#1745]
I passed the a `model_name` of type `pathlib.Path` to `launch_server`. This is then added to the vllm arguments via `eval_serve.vllm.vllm_args.extend(["--served-model-name", model_name])`. However, this breaks code below:

```
if any(
                s == tps_prefix or s.startswith(tps_prefix + "=")
                for s in eval_serve.vllm.vllm_args
            ):
```

Because `pathlib.Path().startswith()` doesn't exist, and the Path is in the `vllm_args`.

**Comment by JamesKunstle** [comment]
@alinaryan @alimaredia @danmcp

**Comment by leseb** [comment]
@JamesKunstle did you mean `--model`? Click has it set as a String, not a Path. Can you add more details on how we can repro this? 

What you described makes sense, I'm just not sure I understand how it was triggered. Thanks

**Comment by JamesKunstle** [comment]
This is when using `launch_server` directly. `model_name` wasn't type-checked by mypy when I passed a pathlib.Path object, so if the intention is that it should accept str model_name's, it could be annotated to enforce this.

**Comment by leseb** [comment]
Ok, understood. Agreed on the annotation.
