### ISSUE TITLE
Documentation for running on Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by mdevino** [instructlab/instructlab#1757]
**Is your feature request related to a problem? Please describe.**

Hello, while InstructLab is not supported in Windows, I managed to run it with GPU acceleration (NVIDIA) using an Arch Linux WSL distribution.

Is there an interest in creating a setup guide for this?

If so, I could work on that. I'd just need some guidance on where this would fit in the project (somewhere in the existing md files, or a brand new one?).

**Comment by bjhargrave** [comment]
Consider writing a new Discussion <https://github.com/instructlab/instructlab/discussions/new/choose> with your information.

**Comment by rushil-x-gupta** [comment]
I've already written a tutorial for setting up and running InstructLab on Windows using WSL, I am more than happy to contribute it to this project!

**Comment by mdevino** [comment]
Hi @bjhargrave. I see @rushil-x-gupta already started working on this [here](https://github.com/instructlab/instructlab/pull/1920). Should we reopen the story?
