### ISSUE TITLE
Remove --legacy train

### ISSUE THREAD

**Issue by RobotSail** [instructlab/instructlab#1760]
We want to drop support for this training mode and instead defer to the new training library.

**Comment by RobotSail** [comment]
@tiran Would like your thoughts on this.

**Comment by tiran** [comment]
Lot's of thoughts:

- What is legacy training and what is new training? Not everybody is familiar with the terms. I guess you are talking about PyTorch `linux_train` vs. `instructlab.training` code?
- Why do you want to remove legacy training? What are the benefits for this project?
- What's the deprecation policy and time line?
- Why do you want to remove it in 0.18? What are the risks to wait for 0.19?
- What are the benefits and drawbacks for our users? Can they still do low-fidelity training easily on their local machine? Is it going to be faster or slower?
- Does the new training work on the same hardware as the legacy training? Is training on CPU, CUDA, Intel Gaudi, and AMD ROCm implemented and tested?
- Does the new code provide same debugging and introspection features? `linux_train` lists hardware properties of CUDA, ROCm, and Gaudi devices.
- What's the risk and impact on the community, documentation, and previous presentations? Will the demos from Summit and my DevConf.CZ talk still apply?


I'm a big fan of the [Python Enhancement Proposal](https://peps.python.org/) structure for change proposals. Additionally to technical details, a PEP has abstract, "rational and motivation", goals/non-goals, benefits/risks, "how to teach", and "rejected ideas".

**Comment by tiran** [comment]
I have created https://github.com/instructlab/dev-docs/issues/118

**Comment by cdoern** [comment]
@RobotSail @tiran I can look at this today if no one has begun working on it

**Comment by cdoern** [comment]
the big blocker here is: does CPU training work via the library? if not, we cannot remove legacy training

**Comment by tiran** [comment]
> @cdoern What would be the reason for keeping CPU training?

For starters CI and local testing on a laptop without GPU?

**Comment by RobotSail** [comment]
> For starters CI and local testing on a laptop without GPU?

The reason I asked is that our benchmarks when training with a CPU in full-training have been very time-consuming before any results are evident. But from our conversation today, it sounds like legacy CPU training can finish an epoch in 10 minutes, which makes it worthwhile to keep.

**Comment by nathan-weinberg** [comment]
Superseded by https://github.com/instructlab/instructlab/issues/2233?

**Comment by alinaryan** [comment]
Closed as complete.
