### ISSUE TITLE
functional test creates a temporary directory for each run

### ISSUE THREAD

**Issue by leseb** [instructlab/instructlab#1774]
Since #1471, the directory structure has changed and the functional test was altered to setup the new directory and create a temporary directory for the test data.
While this makes sense when running on a fresh new runner, this makes the local test quite annoying since:

* a new temp is created
* a model is downloaded in this directory

Solution to accommodate local testing:

* allow to override `TEST_DIR` from `scripts/functional-tests.sh`
* remove or make the trap (`rm -rf "${TEST_DIR}"`) optional

**Comment by tiran** [comment]
Fixing #1182 would also solve the problem. HF used to cache downloaded models in `~/.cache/huggingface` and then symlink the model files.

**Comment by leseb** [comment]
> Fixing #1182 would also solve the problem. HF used to cache downloaded models in `~/.cache/huggingface` and then symlink the model files.

Looks like this won't be ready anytime soon :/
