### ISSUE TITLE
Create notifications on failures from periodic test workflows

### ISSUE THREAD

**Issue by russellb** [instructlab/instructlab#1806]
PR #1805 makes one of our e2e workflows run periodically. We should turn something on that proactively notifies people when this fails. We can use a slack notification action to post to InstructLab slack as one option.

**Comment by nathan-weinberg** [comment]
Slack has an official GitHub Action we could leverage: https://github.com/slackapi/slack-github-action

**Comment by jjasghar** [comment]
`#cli-e2e-results` has been created.

**Comment by nathan-weinberg** [comment]
I'm looking into implementing this with the above action using Technique 2 (since we do not have a paid Slack instance): https://github.com/slackapi/slack-github-action?tab=readme-ov-file#technique-2-slack-app
