### ISSUE TITLE
Requirement conflict for `instructlab-training`

### ISSUE THREAD

**Issue by tiran** [instructlab/instructlab#1815]
**Describe the bug**

The base requirements and `instructlab[cuda]` requirements disagree on the minimum version of instructlab-training.

https://github.com/instructlab/instructlab/blob/a2a3225f3ccc8e517490f06ee814d610e244d30f/requirements.txt#L16

https://github.com/instructlab/instructlab/blob/a2a3225f3ccc8e517490f06ee814d610e244d30f/requirements-cuda.txt#L1

**Expected behavior**
Base requirements's version specifiers should a superset of the version specifiers in optional dependencies. An optional requirement can set a higher minimum version of lower maximum version, but it should never allow a version outside the base requirement's specifier set.

**Additional context**
Untested: The version specifier in CUDA requirements may not be necessary. pip should do the right thing and automatically combine `instructlab-training>=0.3.0` and `instructlab-training[cuda]` as `instructlab-training[cuda]>=0.3.0`.

**Comment by ktam3** [comment]
This has been fixed in 0.18.3
