### ISSUE TITLE
Please add command line argument for listening to different IPs, e.g. "0.0.0.0"

### ISSUE THREAD

**Issue by VfBfoerst** [instructlab/instructlab#1823]
Hello :)  
  
**Is your feature request related to a problem? Please describe.**
After setting up instructlab via container (Podman), I had to edit the code directly so the server would listen to 0.0.0.0. This was needed because of the port-forwarding of podman. So it must listen to 0.0.0.0 to get access from remote to the api. 

**Describe the solution you'd like**
A command-line option like "--host 0.0.0.0" and "--port 8000" would be a nice solution i think:  
```bash
ilab model serve --host 0.0.0.0 --port 8000
```
Additionally, there could be ENVs set which lead to the same result, e.g.  
```bash
ILAB_HOST=0.0.0.0
ILAB_PORT=8000
```

Thank you very much, this project seems to be pretty cool :)  
Cheers.

**Comment by leseb** [comment]
https://github.com/instructlab/instructlab/pull/1446

**Comment by nathan-weinberg** [comment]
Closing this as a dup of https://github.com/instructlab/instructlab/issues/2604

Once that PR is in the final issue will be closed as well
