### ISSUE TITLE
ilab wrapper lack once you start dealing with paths

### ISSUE THREAD

**Issue by eranco74** [instructlab/instructlab#1824]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Info (please complete the following information):**
 - Hardware Specs: [e.g. Apple M2 Pro Chip, 16 GB Memory, etc.]
 - OS Version: [e.g. Mac OS 14.4.1, Fedora Linux 40]
 - Python Version: [output of `python --version`]
 - InstructLab Version: [output of `ilab --version`]

**Additional context**

**Comment by leseb** [comment]
Please fill out the reporting template accordingly. It's difficult to understand what the issue is. Thanks!

**Comment by nathan-weinberg** [comment]
+1

**Comment by nathan-weinberg** [comment]
Closing due to lack of traction, feel free to reopen with the full debug info
