### ISSUE TITLE
`pip install instructlab -C cmake.args="..."` does not work reliable

### ISSUE THREAD

**Issue by tiran** [instructlab/instructlab#1829]
**Describe the bug**
I have had multiple occasions where `pip install instructlab -C cmake.args="..."` did not pass `CMAKE_ARGS` correctly to llama-cpp-python. Most recently I ran into the issue in PR #1826.

**To Reproduce**
unclear

**Expected behavior**
Our installation instructions should work all the time and produce reliable results.

**Additional context**
Maybe we should abandon the cleaner but less reliable  `-C cmake.args="..."` approach and use `CMAKE_ARGS` env var?

**Comment by ktam3** [comment]
Closing in favor of #1873
