### ISSUE TITLE
Remove usage of lambda for DEFAULTS

### ISSUE THREAD

**Issue by RobotSail** [instructlab/instructlab#1838]
When the persistent storage system was first introduced, we relied on a system which would lazy-load the variables and used something like `Field(default_factory=lambda: DEFAULTS.MODELS)` for setting the config defaults so that we wouldn't read the value of the `HOME` variable until test time.
After the integration of the `tmp_path_home` fixture and its usage in the `cli_runner` fixture, this way of declaring defaults for config structures should technically no longer be required. 

We should look into seeing whether we can remove the default values for these lambdas, and remove them if possible.

For example, see the following code in [configuration.py](https://github.com/instructlab/instructlab/blob/e6744d252ceeab4bb0d80091313bfba3e9fe6d91/src/instructlab/configuration.py#L239): https://github.com/instructlab/instructlab/blob/e6744d252ceeab4bb0d80091313bfba3e9fe6d91/src/instructlab/configuration.py#L239

**Comment by nathan-weinberg** [comment]
Think this is a dup of https://github.com/instructlab/instructlab/issues/1684?

**Comment by RobotSail** [comment]
@nathan-weinberg yes, I didn't realize we already had an issue up for this, closing.
