### ISSUE TITLE
Update use of generate_data to pass in openai client

### ISSUE THREAD

**Issue by derekhiggins** [instructlab/instructlab#1846]
Once the minimum version of sdg includes https://github.com/instructlab/sdg/pull/114

we should update the call to  generate_data to pass in the openai client and stop passing in the extra params, 
these can then be removed from the sdg API.

**Comment by tiran** [comment]
I can update my old #1658 to use the new feature.

**Comment by derekhiggins** [comment]
> I can update my old #1658 to use the new feature.

Thanks @tiran
