### ISSUE TITLE
Move StoppingCriteriaSub from notebook to code base

### ISSUE THREAD

**Issue by rawkintrevo** [instructlab/instructlab#185]
#169 Merged fast so we could cut a release. 

Reviewing this morning:

```
from transformers import StoppingCriteria, StoppingCriteriaList

class StoppingCriteriaSub(StoppingCriteria):

    def __init__(self, stops = [], encounters=1):
        super().__init__()
        self.stops = [stop.to("cuda") for stop in stops]

    def __call__(self, input_ids: torch.LongTensor, scores: torch.FloatTensor, **kwargs) -> bool:
        for seq in input_ids:
            for stop in self.stops:
                if stop == seq[-1]:
                    return True
        return False
```

This should be in the code base, not the notebook. - Everything else on this looks really good- this is my only nit. 

cc: @xukai92

**Comment by nathan-weinberg** [comment]
@rawkintrevo are you still intending to work on this?

**Comment by rawkintrevo** [comment]
@nathan-weinberg I'll have to go back and look. A lot changed in the code base since Mar1. But supposing that moving that cell to a utils.py file would still work, yes I can do this.

**Comment by rawkintrevo** [comment]
But to be clear, I haven't started, and am on other projects now, if someone else wants to take it, it won't hurt my feels.

**Comment by nathan-weinberg** [comment]
@rawkintrevo I'm going to close this for now but please feel free to reopen in the future!
