### ISSUE TITLE
Lock down major.minor versions in requirements.txt

### ISSUE THREAD

**Issue by n1hility** [instructlab/instructlab#1851]
In the run up to 0.18.0 we should lock down all of our deps to minor versions in our requirements file to prevent surprise updates coming in (e.g. like torch 2.4).

**Comment by bjhargrave** [comment]
See also https://github.com/instructlab/instructlab/pull/1425

**Comment by n1hility** [comment]
I'm closing this in favor of using constraints per the proposal in #122

**Comment by nathan-weinberg** [comment]
@n1hility think you wanted to link https://github.com/instructlab/dev-docs/pull/122
