### ISSUE TITLE
`pip install ./instructlab[cuda]` fails with `No module named 'packaging'` while installing flash_attn-2.6.2

### ISSUE THREAD

**Issue by fcanogab** [instructlab/instructlab#1864]
**Describe the bug**
While executing `$ pip install ./instructlab[cuda]` on Fedora 40 the execution failed and I got this error:

Collecting flash-attn>=2.4.0 (from instructlab-training[cuda]>=0.3.0; extra == "cuda"->instructlab==0.18.0a8.dev8)
  Downloading flash_attn-2.6.2.tar.gz (2.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 5.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8bjvvk17/flash-attn_797445e0bbf24048a31f86c40902a74b/setup.py", line 11, in <module>
          from packaging.version import parse, Version
      ModuleNotFoundError: No module named 'packaging'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**To Reproduce**
1. `$ git clone https://github.com/instructlab/instructlab.git`
2. `$ pip install ./instructlab[cuda]`

**Expected behavior**
The installation of instructlab finishes successfully.

**Device Info (please complete the following information):**
 - Hardware Specs: Nvidia RTX 4090
 - OS Version: Fedora Linux 40
 - Python Version: Python 3.11.9
 - InstructLab Version: N/A
 - InstructLab GitHub last commit hash: 3892209dd2564a8aab0935488aa7b9061c1858f4

**Comment by fcanogab** [comment]
Maybe related to:
- https://github.com/instructlab/training/issues/147
- https://github.com/instructlab/instructlab/issues/1821

However, in those cases it seems the error is related to `torch` and here the error is related to `packaging`.

**Comment by tiran** [comment]
It is a packaging bug in flash-attn. We have reported the issue to upstream and suggested this workaround, https://github.com/Dao-AILab/flash-attention/pull/958 . The fix has not landed, yet.

As a workaround, first install instructlab without cuda dependencies, then install again with cuda dependencies.

**Comment by tiran** [comment]
```console
. venv/bin/activate
cd instructlab
CMAKE_ARGS="-DLLAMA_CUDA=on" pip install .
pip install packaging wheel setuptools-scm
pip install .[cuda]
```

**Comment by fcanogab** [comment]
This worked, thank you.

**Comment by nathan-weinberg** [comment]
Closing in favor of https://github.com/instructlab/instructlab/issues/1821
