### ISSUE TITLE
Model serving with vLLM seems to be broken on Mac

### ISSUE THREAD

**Issue by jaideepr97** [instructlab/instructlab#1866]
**Describe the bug**

model serving with vLLM seems to be broken when supplied with a safetensors model directory even if supplying `--backend vllm` explicitly. Here is the observed output:
```
(venv) ➜  instructlab ilab model serve --backend vllm --model-path /Users/jrao/Library/Caches/instructlab/models/instructlab/merlinite-7b-lab 
Failed to determine backend: Cannot determine which backend to use: 
```

**To Reproduce**
1. Run the above command 

**Expected behavior**

vLLM server should start up without issue 

**Screenshots**

**Device Info (please complete the following information):**
 - Hardware Specs: Apple M3 Pro, 36GB memory 
 - OS Version: macOS Sonoma 14.5
 - Python Version: 3.11.9
 - InstructLab Version: 0.18.0a8.dev8

**Additional context**

**Comment by jaideepr97** [comment]
closing as I was reminded that vLLM does not support mac at all

**Comment by leseb** [comment]
That doesn't change the fact that the exception message is not fw'ed correctly/
