### ISSUE TITLE
Cannot run non quantized training due to enum error

### ISSUE THREAD

**Issue by relyt0925** [instructlab/instructlab#1891]
**Describe the bug**

A user is forced to specify a string value for --lora-quantize-dtype. The problem with this is even though there is a None enum for that value it can never actually be specified in training because a user is forced to specify a string value in the config for that value example below

```
Error: 1 errors in /var/instructlabbigdisk/config.yaml:
- missing train->lora_quantize_dtype: field required

ilab  model train  --data-path /var/instructlabbigdisk/date/messages_Mixtral-8x7B-Instruct-v0_2024-07-26T02_06_02.jsonl --model-path /var/instructlabbigdisk/models/models/instructlab/granite-7b-lab/ --ckpt-output-dir /var/instructlabbigdisk/.local/share/instructlab/checkpoints/ --device cuda --gpus 8 --is-padding-free true --max-batch-len 2 --effective-batch-size 16 --save-samples 13 --num-epochs 6

pydantic_core._pydantic_core.ValidationError: 1 validation error for LoraOptions
quantize_data_type
  Input should be 'nf4' or None [type=enum, input_value='fp16', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/enum

ilab  model train  --data-path /var/instructlabbigdisk/date/messages_Mixtral-8x7B-Instruct-v0_2024-07-26T02_06_02.jsonl --model-path /var/instructlabbigdisk/models/models/instructlab/granite-7b-lab/ --ckpt-output-dir /var/instructlabbigdisk/.local/share/instructlab/checkpoints/ --device cuda --gpus 8 --is-padding-free true --max-batch-len 2 --effective-batch-size 16 --save-samples 13 --num-epochs 6 --lora-quantize-dtype None

pydantic_core._pydantic_core.ValidationError: 1 validation error for LoraOptions
quantize_data_type
  Input should be 'nf4' or None [type=enum, input_value='None', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/enum
```

The enum value needs to be adjusted to enable a user a mode of specifying a non quantized training run (relevant code is here):
https://github.com/instructlab/instructlab/blob/main/src/instructlab/model/train.py#L227-L232
https://github.com/instructlab/instructlab/blob/c6e41839076a96b33e84c473f87526ac9ac5da36/src/instructlab/configuration.py#L687
https://github.com/instructlab/training/blob/eea8521f4665d3d4e17a2c9c3545da22dd9d1438/src/instructlab/training/config.py#L84
https://github.com/instructlab/training/blob/eea8521f4665d3d4e17a2c9c3545da22dd9d1438/src/instructlab/training/config.py#L37

Additionally the other lora training args all need a path to be None/optional to properly enable full training before/after going into the map_train_to_library function

**To Reproduce**
Steps to reproduce the behavior: try and run non quantized training by specifying None for lora args and you will get the validation error below
```
ilab  model train  --data-path /var/instructlabbigdisk/date/messages_Mixtral-8x7B-Instruct-v0_2024-07-26T02_06_02.jsonl --model-path /var/instructlabbigdisk/models/models/instructlab/granite-7b-lab/ --ckpt-output-dir /var/instructlabbigdisk/.local/share/instructlab/checkpoints/ --device cuda --gpus 8 --is-padding-free true --max-batch-len 2 --effective-batch-size 16 --save-samples 13 --num-epochs 6 --lora-quantize-dtype None

pydantic_core._pydantic_core.ValidationError: 1 validation error for LoraOptions
quantize_data_type
  Input should be 'nf4' or None [type=enum, input_value='None', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/enum
```

**Expected behavior**

There should be a path for a user to specify that they do not want to do quantized training. This was lost when config defaults were forced and the cli for training wasn't updated to enable passing the None value for lora-quantized-dtype

**Screenshots**

**Device Info (please complete the following information):**
 ```
[root@djtest-rhelai-july24 ~]# ilab system info
sys.version: 3.11.7 (main, Jul  4 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)]
sys.platform: linux
os.name: posix
platform.release: 5.14.0-427.24.1.el9_4.x86_64
platform.machine: x86_64
os-release.ID: rhel
os-release.VERSION_ID: 9.4
os-release.PRETTY_NAME: Red Hat Enterprise Linux 9.4 (Plow)
instructlab.version: 0.18.0a6
instructlab-dolomite.version: 0.1.1
instructlab-eval.version: 0.1.0
instructlab-quantize.version: 0.1.0
instructlab-schema.version: 0.3.1
instructlab-sdg.version: 0.2.0
instructlab-training.version: 0.3.0
torch.version: 2.3.0
torch.backends.cpu.capability: AVX512
torch.version.cuda: 12.4
torch.version.hip: None
torch.cuda.available: True
torch.backends.cuda.is_built: True
torch.backends.mps.is_built: False
torch.backends.mps.is_available: False
torch.cuda.bf16: True
torch.cuda.current: 0
torch.cuda.0.name: NVIDIA A100-SXM4-80GB
torch.cuda.0.free: 78.7
torch.cuda.0.total: 79.1
torch.cuda.0.capability: 8.0
torch.cuda.1.name: NVIDIA A100-SXM4-80GB
torch.cuda.1.free: 78.7
torch.cuda.1.total: 79.1
torch.cuda.1.capability: 8.0
torch.cuda.2.name: NVIDIA A100-SXM4-80GB
torch.cuda.2.free: 78.7
torch.cuda.2.total: 79.1
torch.cuda.2.capability: 8.0
torch.cuda.3.name: NVIDIA A100-SXM4-80GB
torch.cuda.3.free: 78.7
torch.cuda.3.total: 79.1
torch.cuda.3.capability: 8.0
torch.cuda.4.name: NVIDIA A100-SXM4-80GB
torch.cuda.4.free: 78.7
torch.cuda.4.total: 79.1
torch.cuda.4.capability: 8.0
torch.cuda.5.name: NVIDIA A100-SXM4-80GB
torch.cuda.5.free: 78.7
torch.cuda.5.total: 79.1
torch.cuda.5.capability: 8.0
torch.cuda.6.name: NVIDIA A100-SXM4-80GB
torch.cuda.6.free: 78.7
torch.cuda.6.total: 79.1
torch.cuda.6.capability: 8.0
torch.cuda.7.name: NVIDIA A100-SXM4-80GB
torch.cuda.7.free: 78.7
torch.cuda.7.total: 79.1
torch.cuda.7.capability: 8.0
llama_cpp_python.version: 0.2.79
llama_cpp_python.supports_gpu_offload: True
[root@djtest-rhelai-july24 ~]# 
```

**Additional context**

Occuring on all v0.18 versions of CLI

**Comment by nathan-weinberg** [comment]
@relyt0925 is this an upstream bug or related to RHEL AI? if just the latter please open up a Jira ticket in the RHEL AI project and close this, thank you

**Comment by relyt0925** [comment]
Id say upstream if you expect to be able to run full scale training period (although I believe RHEL AI is currently the only environment it can be done in as of today.

**Comment by relyt0925** [comment]
@nathan-weinberg

**Comment by nathan-weinberg** [comment]
(No need for additional comment with a tag, I get the notifications either way :wink:) Full scale training is supported upstream, though full support won't be a guarantee until we release 0.18.0. 

Can you please update your bug with upstream context? RHEL AI details aren't really useful here - better to complete the reproduce/device info steps with native InstructLab (e.g. using `ilab system info` for the latter)

**Comment by relyt0925** [comment]
sorry for the extra noise! yep will do

**Comment by nathan-weinberg** [comment]
Np! Appreciate the bug! :smile:

**Comment by relyt0925** [comment]
(updated with system info and removed RHEL AI references)

**Comment by ktam3** [comment]
@relyt0925 - could you see if this is now fixed with the new .18.3 release? If so, please close!

**Comment by relyt0925** [comment]
I will check: it was still there in the instructlab v0.18.2 release and I don't see any changes between .2 and .3 to change that @ktam3

**Comment by ktam3** [comment]
ack, ty!

**Comment by relyt0925** [comment]
👍 just to note again: I think the key piece is all the Lora parameters need to effectively be able to have a None value to allow the system to do full scale fine tuning

**Comment by JamesKunstle** [comment]
I just looked at this- you're totally right. Setting `'None'` should parse to `None` so the model isn't quantized. Good catch. Will start working on this.

**Comment by relyt0925** [comment]
this has been fixed!
