### ISSUE TITLE
Standardize directory structures created from model downloads

### ISSUE THREAD

**Issue by jaideepr97** [instructlab/instructlab#1894]
**Is your feature request related to a problem? Please describe.**
Currently, there are a number of places where we perform model downloads. We support Hugging Face downloads as well as OCI downloads, and we also download models implicitly during `ilab model train` if the model is not detected. The locations where these models get downloaded to, and the subdirectory structure created for those are not yet entirely standardized. Hugging Face downloads from the `instructlab` org are saved to `XDG_CACHE_HOME/instructlab/<model-name>` for eg, but OCI downloaded models are just saved to  `XDG_CACHE_HOME/<model-name>`. Further, the models downloaded from `ilab model train` on macOS just get saved to the instructlab working directory when it does not see a model present there already (when in fact the same model may have already been downloaded to `XDG_CACHE_HOME`)

This leads to inconsistency and also unnecessary duplication of downloads 

**Describe the solution you'd like**
All model download destination paths should follow a standard structure. I propose that they should all replicate the URL structure of the repository that hosts them. 
For eg: `quay.io/ai-labs/models/granite-7b-lab` should get downloaded to `XDG_CACHE_HOME/instructlab/models/quay.io/ai-labs/models/granite-7b-lab` and `instructlab/merlinite-7b-lab` on HF should get downloaded to `XDG_CACHE_HOME/instructlab/models/instructlab/merlinite-7b-lab`

This would ensure that the destination path is always consistent, and we would avoid duplicate downloads because the hugging face downloader and skopeo both check the supplied destination directory first, and skip the download if they see it exists already. This would also follow some established norms from other projects and make it intuitive for users to find the models easily later 

**Additional context**
This might break `ilab model list`

**Comment by ktam3** [comment]
Related to #2111

**Comment by jaideepr97** [comment]
closing in favor of https://github.com/instructlab/instructlab/issues/2371
