### ISSUE TITLE
train checkpoints are not copied globally

### ISSUE THREAD

**Issue by alinaryan** [instructlab/instructlab#1907]
Profile issue. Train checkpoints don’t get copied to global, they get copied to local dir. 
Allow the caller to set the output directory and the pattern they would like to save it as(add a prefix or whatever scheme they would like to use)

**Comment by cdoern** [comment]
this isn't really a bug but an error with the defaults in the train profile. Will be dealt with via #1945

**Comment by nathan-weinberg** [comment]
Can we close this since the above PR merged?

**Comment by alinaryan** [comment]
Closed as part of #1945
