### ISSUE TITLE
set train profile keys as optional

### ISSUE THREAD

**Issue by alinaryan** [instructlab/instructlab#1908]
`ilab model train` errors when train profile is missing keys that are set by default (should be made optional in the training class)

@cdoern can you add the exact keys that are erroring?

**Comment by cdoern** [comment]
this will be handled by #1945

**Comment by mairin** [comment]
#1945 is no longer blocking. #1945 allows user to specify a partial config, and ilab will populate the rest of them for you. it is this feature that would address this issue.
