### ISSUE TITLE
`ilab data generate` needs a --gpus flag

### ISSUE THREAD

**Issue by cdoern** [instructlab/instructlab#1921]
It is impossible to run `ilab data generate` on multiple gpus via the CLI without starting a server first via `ilab model serve`. Since we support implicit server launching, we need to add this flag

**Comment by alimaredia** [comment]
It is possible to set the number of GPUs by setting the vllm args of the `teacher` section of the generate section of the config.

How would you feel about move adding the `--gpus` flag in `ilab data generate` from the `0.18` to the `0.19` release.

CC: @danmcp
