### ISSUE TITLE
Create Instructlab Train Profiles

### ISSUE THREAD

**Issue by ktam3** [instructlab/instructlab#1929]
Training profiles per HW profile

- Render training profiles in code [--train-profile flag]
- Golden train and environment config needed
- Downstream warning for ilab config overwrite ~/. Train files (local)
- Interactive train profile select and logic

**Comment by booxter** [comment]
@ktam3 should this be tracked in the upstream project tracker? sounds like a Red Hat specific requirement.

**Comment by ktam3** [comment]
Discussed with Charlie and he wanted a GitHub tracker for this
