### ISSUE TITLE
ilab serve is returning 503 Service Unavailable when doing few requests quickly one after another

### ISSUE THREAD

**Issue by fcanogab** [instructlab/instructlab#1950]
**Describe the bug**
The instructlab API is returning a 503 Service Unavailable in a consistent way just by making few requests (2 or 3 is enough) quickly to the API.

**To Reproduce**
Just make few request quickly to the API. Try few times if it does not happen the first time, but in 2 or 3 tries it happens.
1. Execute ilab serve
2. In another terminal, execute this script:

```
from openai import OpenAI

client = OpenAI(
    base_url="http://localhost:8000/v1",
    api_key="token-abc123"
)

completion = client.chat.completions.create(
    model="/home/user/.cache/instructlab/models/merlinite-7b-lab-Q4_K_M.gguf",
    messages=[
        {"role": "user", "content": "Hello!"}
    ]
)

for i in range(2):
    print(completion.choices[0].message.content)

```
The execution is blocked. If you go now to https://127.0.0.1:8000, it returns Service Unavailable.
If you cancel the execution of the script which has been blocked and wait some seconds, you go again to https://127.0.0.1:8000 and it may work.

**Expected behavior**
ilab serve should support a bigger number of quick connections without getting blocked.

**Device Info (please complete the following information):**
 - Hardware Specs: Nvidia RTX 4090
 - OS Version: Fedora Linux 40
 - Python Version: Python 3.11.9
 - InstructLab Version: ilab, version 0.18.0b1

**Comment by ktam3** [comment]
@fcanogab - could you try this with the latest version .18.3?

**Comment by fcanogab** [comment]
@ktam3 I confirm that I cannot reproduce this in 0.18.3. It seems fixed. Thank you!

**Comment by ktam3** [comment]
great thanks! Closing as fixed!
