### ISSUE TITLE
Fix: `ilab model train --strategy lab-multiphase` test in `basic_workflow_test.sh`

### ISSUE THREAD

**Issue by JamesKunstle** [instructlab/instructlab#1970]
**Describe the bug**
We merged #1732 without a complete test.

**Comment by nathan-weinberg** [comment]
@JamesKunstle can I assign this to you?

**Comment by nathan-weinberg** [comment]
@JamesKunstle just checking in to see if this is still relevant

**Comment by alimaredia** [comment]
Closed by https://github.com/instructlab/instructlab/pull/2291
