### ISSUE TITLE
Lora target modules are being converted into a tuple

### ISSUE THREAD

**Issue by RobotSail** [instructlab/instructlab#2021]
**Describe the bug**

The `lora_target_modules` field is originally created as a `list` but at some point down the line gets converted into a `tuple` before making it to training. 

It seems like root cause is something to do with the complex click parameter parsing logic that was introduced.

**To Reproduce**

1. Create a new ilab config
2. Try to run ilab model train

**Comment by booxter** [comment]
Can you please give more details, like a traceback, error message?
