### ISSUE TITLE
`ilab model download` reports confusing error when downloading non-GGUF repo without `.safetensors` file

### ISSUE THREAD

**Issue by lenticularis39** [instructlab/instructlab#2022]
**Describe the bug**
Note that currently,  `ilab model download` errors out on not finding a file `merlinite-7b-lab-Q4_K_M.gguf` when trying to download a non-GGUF repo that does not have a `.safetensors` file. This might be confusing to the user, who expects the whole repo to be downloaded in such cases, not InstructLab looking for a specific file.

**To Reproduce**
1. Run `ilab model download --repository=UnicomLLM/Unichat-llama3-Chinese-8B-28K`. (This is a repo containing the model in `.bin` format).
2. `ilab model download` errors out with `Entry Not Found for url: https://huggingface.co/UnicomLLM/Unichat-llama3-Chinese-8B-28K/resolve/main/merlinite-7b-lab-Q4_K_M.gguf.`, confusing the user because this is not a GGUF repo, and InstructLab can download other non-GGUF repos, like `instructlab/granite-7b-lab`.

**Expected behavior**
Error that the repo does not contain a `.safetensors` file nor a GGUF file, and thus the download is not supported.

**Screenshots**

**Device Info (please complete the following information):**
 - Hardware Specs: ThinkPad T14s Gen 2i
 - OS Version: Fedora 40
 - Python Version: Python 3.12.4
 - InstructLab Version: ilab, version 0.17.1

**Additional context**
It is unclear from the interface that there are two code paths: one when there is a `.safetensors` file, then, the repo is considered a non-GGUF one and the whole repo is downloaded, and the other one where there is no such file where the repo is considered a GGUF repo and InstructLab automatically tries to download a GGUF file.

**Comment by lenticularis39** [comment]
Fixed. Sorry, I was a bit too quick in filing the issue.

**Comment by nathan-weinberg** [comment]
Thank you! I see you're using 0.17.1 - looking at the issue I think this _may_ be fixed in current `main` - we are planning to cut a 0.18.0 soon, but if you want to you can try this on the current `main` branch to see if it's an issue there.

**Comment by cdoern** [comment]
We need to expand `ilab model download` to understand `.bin` models, this is a pretty trivial fix and I can make a PR for it
