### ISSUE TITLE
Train profile list is confusing

### ISSUE THREAD

**Issue by jjasghar** [instructlab/instructlab#2028]
**Describe the bug**
Looking at the option for `ilab config init` the train profile is not clear.

**To Reproduce**
When you come to this option:
```bash
Please choose a train profile to use:
[0] No profile (CPU-only)
[1] A100_H100_x2.yaml
[2] A100_H100_x4.yaml
[3] A100_H100_x8.yaml
[4] L40_x4.yaml
[5] L40_x8.yaml
[6] L4_x8.yaml
```

If you are training on your local laptop, you don't understand what any of
these option are. From the #users thead, if you are doing _non_ Nvidia
work you should choose "CPU-only." This isn't clear.

**Expected behavior**
Clear choice with an obvious understanding of which to use.

**Comment by nathan-weinberg** [comment]
@cdoern what simple fix might I be able to do here that won't conflict with your profile work? just a reworking of the text?
