### ISSUE TITLE
ilab serve --model-path usage is weird now

### ISSUE THREAD

**Issue by jjasghar** [instructlab/instructlab#2029]
**Describe the bug**
With moving everything under `~/Library/Application Support/instructlab`
in order to use `ilab model serve` you have to do something like the following:
```bash
ilab model serve --model-path /Users/jjasghar/Library/Caches/instructlab/models/granite-7b-lab-Q4_K_M.gguf
```

This is not good, with the default shell is `zsh` or if someone is using `bash` if they
have a " " in the name this will only bring frustration.

This ties in with the `taxonomy` default place as:
```bash
Path to taxonomy repo [/Users/jjasghar/Library/Application Support/instructlab/taxonomy]:
```

This is very unintuitive,and if we want people to be able to access the `yaml`s there,
this is going to cause a lot of questions.

**Comment by bjhargrave** [comment]
See https://github.com/instructlab/instructlab/issues/1747

**Comment by jjasghar** [comment]
Closing per #1747. I'll comment there from now on.
