### ISSUE TITLE
~ expansion in config doesn't work within args lists using key=value

### ISSUE THREAD

**Issue by danmcp** [instructlab/instructlab#2037]
**Describe the bug**
As an example:

This works:

```
vllm_args:
      - --lora-modules
      - skill-classifier-v3-clm=$HOME/.cache/instructlab/models/skills-adapter-v3
      - text-classifier-knowledge-v3-clm=$HOME/.cache/instructlab/models/knowledge-adapter-v3
```

and replaces $HOME as expected but this does not

```
vllm_args:
      - --lora-modules
      - skill-classifier-v3-clm=~/.cache/instructlab/models/skills-adapter-v3
      - text-classifier-knowledge-v3-clm=~/.cache/instructlab/models/knowledge-adapter-v3
```

The reason why is that os.path.expanduser only works with a ~ at the beginning of a string.

**To Reproduce**
1. Add the above example into your config
2. ilab config show

**Expected behavior**
~ in vllm_args is replaced with expanded home directory

**Version**

Found in:
v0.18.0rc5

**Comment by danmcp** [comment]
It's not clear whether we should fix this issue given we can't differentiate between cases we need to resolve ~ ahead of time vs when it should be passed as an arg to the subcommand.  Currently we have the option with $HOME or ~ to handle it before or pass the ~ onward.

**Comment by nathan-weinberg** [comment]
@danmcp do you know if this is still an issue?

**Comment by danmcp** [comment]
> @danmcp do you know if this is still an issue?

The behavior is still the same.  And it's still debatable whether we should change it.  Maybe best to close and reopen if we find a case where it actually needs to be changed.
