### ISSUE TITLE
pip install 'instructlab[cpu]' installs version 0.17.1

### ISSUE THREAD

**Issue by mansam-ger** [instructlab/instructlab#2047]
**Describe the bug**
```
user@linux:~/instructlab> python3 -m venv --upgrade-deps venv
user@linux:~/instructlab> source venv/bin/activate
(venv) user@linux:~/instructlab> pip cache remove llama_cpp_python
Files removed: 1
(venv) user@linux:~/instructlab> pip install 'instructlab[cpu]' \
>    --extra-index-url=https://download.pytorch.org/whl/cpu \
>    -C cmake.args="-DLLAMA_NATIVE=off"
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu
Collecting instructlab[cpu]
  Using cached instructlab-0.17.1-py3-none-any.whl.metadata (31 kB)
WARNING: instructlab 0.17.1 does not provide the extra 'cpu'
```

[...]
ilab --version shows
ilab, version 0.17.1

upgrade with pip stays at 0.17.1

**To Reproduce**
1. do a clean install

**Expected behavior** 
install the latest version

**Screenshots**

**Device Info (please complete the following information):**
 - Hardware Specs: Intel core ultra 7
 - OS Version: Fedora Linux 40
 - Python Version: 3.11.9
 - InstructLab Version: 0.17.1

**Comment by nathan-weinberg** [comment]
@mansam-ger 0.17.1 is the latest released version - what behavior are you expecting?

**Comment by mansam-ger** [comment]
I anticipated that version 0.18 ist out because in the short guide there is the command "ilab model list". The command fails for me. I took a look in the changelog and there is the command listed as a new feature for 0.18 . 

@nathan-weinberg

**Comment by nathan-weinberg** [comment]
@mansam-ger 0.18.0 is not out - you are welcome to try one of the pre-release versions if you'd like - it's sound like this is not a bug so can we close this?

**Comment by mansam-ger** [comment]
yes thank you

**Comment by romeosdibm** [comment]
0.19 is out and still the default version is 0.17

**Comment by nathan-weinberg** [comment]
@romeosdibm can you describe the behavior?

**Comment by romeosdibm** [comment]
@nathan-weinberg  simple: running this command on macos pip install 'instructlab[mps]', downloads v0.17 by default.

Also another issue if I tried to be specific on the version using ==0.19 I get an error Could not find a version that satisfies the requirement torch<2.4.0,>=2.3.0 (from instructlab)

**Comment by nathan-weinberg** [comment]
@romeosdibm and you've done this in a fresh virtual environment?

**Comment by romeosdibm** [comment]
@nathan-weinberg yes

**Comment by bjhargrave** [comment]
This odd behavior has been observed when someone has both a conda and venv environment active at the same time. The prompt will have something like `(venv) (base)` in it showing two active environments.

**Comment by romeosdibm** [comment]
@bjhargrave possibly let me check that.

**Comment by romeosdibm** [comment]
no luck, uninstalled conda 

@bjhargrave @nathan-weinberg 

python3 -m venv --upgrade-deps venv
 source venv/bin/activate
 pip cache remove llama_cpp_python
 pip install 'instructlab[mps]'

(venv) xx@xx-MBP instructlab % ilab --version
ilab, version 0.17.1
(venv) xx@xx-MBP instructlab %

**Comment by bjhargrave** [comment]
@romeosdibm Slack me tomorrow and we will sort this out.
