### ISSUE TITLE
don't require --judge-model for mt_bench_branch if already set in the config 

### ISSUE THREAD

**Issue by alinaryan** [instructlab/instructlab#2056]
The mt_bench_branch evaluation benchmark should not require the --judge-model flag when there is a judge model field specified in the config. However, the command is currently failing because it does not read the judge_model field from the config and instead returns an error, instructing the user to specify the judge model using the --judge-model flag.

**Steps to Reproduce**
Use a downstream config with the judge model field properly defined.
Run the eval mt_bench_branch benchmark without specifying the --judge-model flag.
**Expected Behavior**
The benchmark should read the judge model field from the config and proceed without requiring the --judge-model flag.

**Actual Behavior**
The command errors out and instructs the user to specify the judge model using the --judge-model flag, despite it being present in the downstream config.

**Possible Solution**
Ensure that the judge_model field in the config is correctly parsed and used by the benchmark, eliminating the need for the --judge-model flag. Need further investigation into the eval repo

**Comment by danmcp** [comment]
I tried this an wasn't able to recreate:

time ilab model evaluate --model /home/ec2-user/.cache/instructlab/models/instructlab/granite-7b-lab/ --benchmark mt_bench
```
Using local model found at '/home/ec2-user/.cache/instructlab/models/instructlab/granite-7b-lab' for '--model'
Using local model found at '/home/ec2-user/.cache/instructlab/models/instructlab/granite-7b-lab' for '--judge-model'
...
```

with my config as:
```
  mt_bench:
    judge_model: /home/ec2-user/.cache/instructlab/models/instructlab/granite-7b-lab/
```

What was the setup for the failing test?

**Comment by ktam3** [comment]
@alinaryan - could you follow up on this?

**Comment by alinaryan** [comment]
I have not been able to reproduce this again. I suspect we were using a faulty config when this was found during one of the e2e runs. Will reopen if we come across this again.
