### ISSUE TITLE
Log file for serving

### ISSUE THREAD

**Issue by alimaredia** [instructlab/instructlab#2080]
This feature request has to do with logging the output of `ilab model serve` to a file and the out put of other `ilab` commands that serve models under the hood.

1. Verify the `--log-file` flag for ilab model serve works
2. Send background vllm serving output to a file instead of to /dev/null
3. Design and add config variables and flags to all commands that do background serving

**Comment by leseb** [comment]
`log_file` is broken since each module as its own logger instance.

**Comment by leseb** [comment]
Taking over as agreed offline.

**Comment by ktam3** [comment]
@leseb - do you have any new updates on this?

**Comment by leseb** [comment]
> @leseb - do you have any new updates on this?

PR was posted a while ago and I'm still waiting to get some reviews https://github.com/instructlab/instructlab/pull/2084 :)

**Comment by ktam3** [comment]
Ack, let me see if I can get some movement on this
