### ISSUE TITLE
Yaml formatting allow more than 120 character lines

### ISSUE THREAD

**Issue by KodieGlosserIBM** [instructlab/instructlab#2100]
**Describe the solution you'd like**
Currently today, taxonomy files do not support a line length longer than 120 characters:

```
38:121: [warning] line too long (227 > 120 characters) (line-length)

90:121: [warning] line too long (306 > 120 characters) (line-length)
92:121: [warning] line too long (305 > 120 characters) (line-length)
```

The client has tables in md format that stretch longer than 120 characters and it has the potential to compromise the data when trying to format these files to meet the 120 character limit. 

The request is to push the line limit to 2000 characters (or make it configurable).

**Comment by bjhargrave** [comment]
Please see https://github.com/instructlab/schema/pull/45. This depends upon https://github.com/instructlab/instructlab/pull/1962 and https://github.com/instructlab/sdg/pull/62 being merged.

**Comment by bjhargrave** [comment]
instructlab-schema [v0.4.1](https://github.com/instructlab/schema/releases/tag/v0.4.1) has been released.

> This depends upon #1962 and [instructlab/sdg#62](https://github.com/instructlab/sdg/pull/62) being merged.

These have been merged. So when the next release of instructlab and instructlab-sdg are made, they will no longer lint line length.

**Comment by bjhargrave** [comment]
Closing as all the PRs are now merged.
