### ISSUE TITLE
Print full scores along with delta for MMLU-Branch scores

### ISSUE THREAD

**Issue by alimaredia** [instructlab/instructlab#2124]
Currently an MMLU-Run has the following output.

```
# KNOWLEDGE EVALUATION REPORT

## BASE MODEL
/home/ec2-user/.cache/instructlab/models/instructlab/granite-7b-lab

## MODEL
/home/ec2-user/models/4x-a10-np-4

### AVERAGE:
+0.08 (across 1)

### IMPROVEMENTS:
1. knowledge_pheonix (+0.08)

real    6m33.259s
user    2m45.545s
sys     0m44.396s
```

The user would benefit by does showing the full scores for each of the models, not just the deltas.

**Comment by bjhargrave** [comment]
We should do this for all scores not just MMLU-Branch.

**Comment by danmcp** [comment]
> We should do this for all scores not just MMLU-Branch.

https://github.com/instructlab/instructlab/issues/2125

That's the corresponding issue for mt_bench_branch.  Which I think covers all the current cases.

**Comment by alimaredia** [comment]
This issue should be closed by the merging of https://github.com/instructlab/instructlab/pull/2316
