### ISSUE TITLE
Potentially appending multiple model's answers to same file with mt-bench

### ISSUE THREAD

**Issue by JamesKunstle** [instructlab/instructlab#2148]
**Describe the bug**
A few people have noticed that when running mt-bench with phased-training, the progress bar is `[x/320]` rather than the expected `[y/160]`. This shouldn't be a random display artifact.

**To Reproduce**
1. Run `ilab model train --strategy lab-multiphase ...`
2. During MT-Bench, the error _may_ occur. 

**Expected behavior**
The progress bar should be `[y/160]` rather than out of 320.

This hasn't been consistently reproduced yet.

**Comment by ktam3** [comment]
test comment

**Comment by JamesKunstle** [comment]
Fixed by https://github.com/instructlab/eval/pull/110
