### ISSUE TITLE
Optimize DeepSpeed for Gaudi

### ISSUE THREAD

**Issue by ktam3** [instructlab/instructlab#2222]
https://docs.habana.ai/en/latest/PyTorch/DeepSpeed/DeepSpeed_User_Guide/DeepSpeed_User_Guide.html

**Comment by tiran** [comment]
We are going to focus on FSDP and not use Gaudi's DeepSpeed fork in next version.

**Comment by ktam3** [comment]
Ack thanks for verifying @tiran . Will take this out of the current sprint

**Comment by ktam3** [comment]
Not doing deepspeed w/ gaudi , closed
