### ISSUE TITLE
Switch default model from Merlinite to Granite

### ISSUE THREAD

**Issue by nathan-weinberg** [instructlab/instructlab#2238]
InstructLab has moved pretty heavily towards being a Granite-first project, yet many of the config defaults for models remain to be Merlinite. Opening this issue to start the conversation of switching over to Granite quanitized GGUFs and Safetensors, where applicable.

Merlinite can still be used in things like CI.

If folks agree I can convert this issue from a `question` to a `refactor` and implement it.

**Comment by maxdebayser** [comment]
Sorry, I should have searched more before opening a duplicate issue. But I think that some of the points I raised in that issue were relevant. Especially this one:

When you are a new user and start playing with `ilab model chat` and you find some gap in the knowledge of that model, it's very confusing that the knowledge that you add is then used to train another model. Is there a technical reason to use two different models?

I know that there are technical limitations and that you can't train with the gguf model. But the quantized model should be based on the same unquantized model.
