### ISSUE TITLE
 Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.   │ exit code: 1

### ISSUE THREAD

**Issue by pvrbharg** [instructlab/instructlab#2308]
**Describe the bug**

Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.   │ exit code: 1
+++
Building wheels for collected packages: llama-cpp-python, rouge-score
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      *** scikit-build-core 0.10.7 using CMake 3.30.3 (wheel)
      *** Configuring CMake...
      loading initial cache file /tmp/tmpgc8ep8aj/build/CMakeInit.txt
      CMake Error at /tmp/pip-build-env-wa3b_s_j/normal/lib64/python3.12/site-packages/cmake/data/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:49 (message):
        Could not find compiler set in environment variable CC:

        gcc.
      Call Stack (most recent call first):
        CMakeLists.txt:3 (project)

      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!

      *** CMake configuration failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
  Building wheel for rouge-score (pyproject.toml) ... done
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24948 sha256=b9573f5e523cf6904b6fd916fe2589dfaba7c25914d182b6e27287458dcc26c4
  Stored in directory: /home/bvperepa/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge-score
Failed to build llama-cpp-python
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (llama-cpp-python)
+++

**To Reproduce**
$ mkdir instructlab && cd instructlab 
$ python3 -m venv --upgrade-deps venv
$ source venv/bin/activate
$ pip cache remove llama_cpp_python
$ pip install 'instructlab[mps]==0.17.1'

**Expected behavior**
Normal build of iLab

**Device Info (please complete the following information):**
Lenovo P15 running Fedora40 under VMWare Workstation Pro 17.6
cat /etc/os-release
NAME="Fedora Linux"
VERSION="40 (Workstation Edition)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Workstation Edition"
VARIANT_ID=workstation
 uname -srm
Linux 6.10.10-200.fc40.x86_64 x86_64
 python --version
Python 3.12.6
**Additional context**
Trying to setup iLab version of 0.17.1

**Comment by pvrbharg** [comment]
Never mind - by following this command from https://github.com/instructlab/instructlab?tab=readme-ov-file#install-using-pytorch-without-cuda-bindings-and-no-gpu-acceleration

sudo dnf install gcc gcc-c++ make git python3.12 python3.12-devel

I am able to build the iLab and able to succeed.

We can close this issue. Thank you!

**Comment by sthirugn** [comment]
> Never mind - by following this command from https://github.com/instructlab/instructlab?tab=readme-ov-file#install-using-pytorch-without-cuda-bindings-and-no-gpu-acceleration
> 
> sudo dnf install gcc gcc-c++ make git python3.12 python3.12-devel
> 
> I am able to build the iLab and able to succeed.
> 
> We can close this issue. Thank you!

I hit this compiler not set error. I can confirm that using python 3.12 as indicated resolved the issue in my Fedora 40.

```
# cat /etc/redhat-release
Fedora release 40 (Forty)

# rpm -qa | grep gcc
libgcc-14.2.1-3.fc40.x86_64
gcc-14.2.1-3.fc40.x86_64
gcc-c++-14.2.1-3.fc40.x86_64

#python --version
Python 3.12.8

```
