### ISSUE TITLE
ilab model train --pipeline simple, on v0.19 fails on Mac with ValueError: too many values to unpack

### ISSUE THREAD

**Issue by ahmed-azraq** [instructlab/instructlab#2356]
**Describe the bug**
ilab model train fails on Mac with InstructLab version 0.19 with "ValueError: too many values to unpack".

**To Reproduce**

1. ilab --version
ilab, version 0.19.0

2. % ilab model train --pipeline simple
[INFO] Loading
special_tokens_map.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 655/655 [00:00<00:00, 1.45MB/s]
generation_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 314kB/s]
model.safetensors.index.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23.9k/23.9k [00:00<00:00, 25.8MB/s]
config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 609/609 [00:00<00:00, 4.38MB/s]
added_tokens.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 119/119 [00:00<00:00, 541kB/s]
tokenizer_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.27k/2.27k [00:00<00:00, 8.79MB/s]
tokenizer.model: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500k/500k [00:00<00:00, 1.76MB/s]
tokenizer.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.84M/1.84M [00:00<00:00, 3.16MB/s]
model-00001-of-00003.safetensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.94G/4.94G [02:39<00:00, 31.0MB/s]
model-00002-of-00003.safetensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.95G/4.95G [02:40<00:00, 30.8MB/s]
model-00003-of-00003.safetensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.59G/3.59G [12:01<00:00, 4.98MB/s]
Fetching 11 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [12:02<00:00, 65.66s/it]
config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 609/609 [00:00<00:00, 4.17MB/s]
tokenizer_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.27k/2.27k [00:00<00:00, 4.64MB/s]
tokenizer.model: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500k/500k [00:00<00:00, 10.1MB/s]
tokenizer.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.84M/1.84M [00:00<00:00, 3.17MB/s]
added_tokens.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 119/119 [00:00<00:00, 243kB/s]
special_tokens_map.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 655/655 [00:00<00:00, 2.26MB/s]
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565 - if you loaded a llama tokenizer from a GGUF file you can ignore this message.
dtype=mlx.core.float16
[INFO] Quantizing
Using model_type='llama'
Loading pretrained model
Using model_type='llama'
Total parameters 1165.829M
Trainable parameters 2.097M
Loading datasets
*********

ᕙ(•̀‸•́‶)ᕗ  Training has started! ᕙ(•̀‸•́‶)ᕗ 

*********
Epoch 1: Iter 1: Val loss 3.961, Val took 40.321s
Iter 010: Train loss 3.318, It/sec 0.212, Tokens/sec 88.791
Epoch 1: Iter 10: Val loss 2.477, Val took 41.355s
Traceback (most recent call last):
  File "/Users/ahmedazraq/Documents/instructlab/venv/bin/ilab", line 8, in <module>
    sys.exit(ilab())
             ^^^^^^
  File "/Users/ahmedazraq/Documents/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedazraq/Documents/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/ahmedazraq/Documents/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedazraq/Documents/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedazraq/Documents/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedazraq/Documents/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedazraq/Documents/instructlab/venv/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedazraq/Documents/instructlab/venv/lib/python3.11/site-packages/instructlab/clickext.py", line 319, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedazraq/Documents/instructlab/venv/lib/python3.11/site-packages/instructlab/model/train.py", line 730, in train
    load_and_train(
  File "/Users/ahmedazraq/Documents/instructlab/venv/lib/python3.11/site-packages/instructlab/train/lora_mlx/lora.py", line 306, in load_and_train
    train_model(
  File "/Users/ahmedazraq/Documents/instructlab/venv/lib/python3.11/site-packages/instructlab/train/lora_mlx/lora.py", line 204, in train_model
    a, b = adapter_file.split(".")
    ^^^^
ValueError: too many values to unpack (expected 2)

**Device Info (please complete the following information):**
 - Hardware Specs: [e.g. Apple M2 Pro Chip, 16 GB Memory, etc.]: Apple M1 Pro, 16 GB RAM
 - OS Version: [e.g. Mac OS 14.4.1, Fedora Linux 40]: 14.6.1 (23G93)
 - Python Version: [output of `python --version`]: Python 3.11.10
 - InstructLab Version: [output of `ilab system info`]:
  ilab system info
sys.version: 3.11.10 (main, Sep  7 2024, 01:03:31) [Clang 15.0.0 (clang-1500.3.9.4)]
sys.platform: darwin
os.name: posix
platform.release: 23.6.0
platform.machine: arm64
platform.node: Ahmeds-MBP
platform.python_version: 3.11.10
platform.cpu_brand: Apple M1 Pro
instructlab.version: 0.19.0
instructlab-dolomite.version: 0.1.1
instructlab-eval.version: 0.3.1
instructlab-quantize.version: 0.1.0
instructlab-schema.version: 0.4.1
instructlab-sdg.version: 0.3.0
instructlab-training.version: 0.5.0
torch.version: 2.3.1
torch.backends.cpu.capability: NO AVX
torch.version.cuda: None
torch.version.hip: None
torch.cuda.available: False
torch.backends.cuda.is_built: False
torch.backends.mps.is_built: True
torch.backends.mps.is_available: True
llama_cpp_python.version: 0.2.79
llama_cpp_python.supports_gpu_offload: True

**Additional context**
 % ls -alt /Users/ahmedazraq/.local/share/instructlab/datasets
total 11544
-rw-r--r--   1 ahmedazraq  staff    19588 Oct  1 20:04 test.jsonl
drwxr-xr-x  15 ahmedazraq  staff      480 Oct  1 20:04 .
-rw-r--r--   1 ahmedazraq  staff    42464 Oct  1 20:04 valid.jsonl
-rw-r--r--   1 ahmedazraq  staff   165116 Oct  1 20:04 train.jsonl
-rw-r--r--   1 ahmedazraq  staff     9569 Oct  1 20:04 test_gen.jsonl
-rw-r--r--   1 ahmedazraq  staff    99962 Oct  1 20:04 train_gen.jsonl
drwxr-xr-x   9 ahmedazraq  staff      288 Oct  1 20:03 ..
-rw-r--r--@  1 ahmedazraq  staff  2884823 Oct  1 19:53 skills_train_msgs_2024-10-01T19_42_08.jsonl
-rw-r--r--   1 ahmedazraq  staff      379 Oct  1 19:53 skills_recipe_2024-10-01T19_42_08.yaml
-rw-r--r--   1 ahmedazraq  staff  2426399 Oct  1 19:53 knowledge_train_msgs_2024-10-01T19_42_08.jsonl
-rw-r--r--   1 ahmedazraq  staff      379 Oct  1 19:53 knowledge_recipe_2024-10-01T19_42_08.yaml
-rw-r--r--   1 ahmedazraq  staff   120617 Oct  1 19:53 messages_merlinite-7b-lab-Q4_K_M_2024-10-01T19_42_08.jsonl
-rw-r--r--   1 ahmedazraq  staff    99962 Oct  1 19:53 train_merlinite-7b-lab-Q4_K_M_2024-10-01T19_42_08.jsonl
drwxr-xr-x   6 ahmedazraq  staff      192 Oct  1 19:53 node_datasets_2024-10-01T19_42_08
-rw-r--r--   1 ahmedazraq  staff     9569 Oct  1 19:42 test_merlinite-7b-lab-Q4_K_M_2024-10-01T19_42_08.jsonl

**Comment by ahmed-azraq** [comment]
I did a code workaround on `lora.py` to split based on the last occurence of `.`  using rsplit and the training is now completed. 🎉 

<img width="715" alt="image" src="https://github.com/user-attachments/assets/cead2f76-3a33-4208-ac56-1810c3483ed0">
<img width="999" alt="image" src="https://github.com/user-attachments/assets/be7ea083-2c1f-4bcb-99b8-dac2a91dc00b">

**Comment by bjhargrave** [comment]
Perhaps you can make a PR with the fix?

**Comment by ahmed-azraq** [comment]
Hi @bjhargrave yeah sure.. will do it now.
