### ISSUE TITLE
Large E2E CI job failing in Eval

### ISSUE THREAD

**Issue by nathan-weinberg** [instructlab/instructlab#2427]
we are seeing the following error on the Large E2E CI job

```bash
Invalid Tasks Dir: /root/.local/share/instructlab/datasets/node_datasets_2024-10-09T16_14_00
```
see more here: https://github.com/instructlab/instructlab/actions/runs/11258106253/job/31304049977

cc @alimaredia @danmcp

**Comment by danmcp** [comment]
Need to know what's in the dir, looks like lm_eval can't find the format it's expecting

**Comment by nathan-weinberg** [comment]
Cron job succeeded with new SDG version including @alimaredia's fix - closing this.
