### ISSUE TITLE
Getting Connection error while trying to chat using model

### ISSUE THREAD

**Issue by kushalpuri0817** [instructlab/instructlab#2444]
**Describe the bug**

**ERROR 2024-10-13 10:36:27,280 llama_cpp:0: flush ggml_metal_graph_compute_block_invoke: error: unsupported op 'RMS_NORM'
GGML_ASSERT: /private/var/folders/ww/9jll0gj14_n0hg195p6wtz140000gn/T/pip-install-75_w3ko1/llama-cpp-python_4c039b455a38430db01204aed6178d6f/vendor/llama.cpp/ggml-metal.m:910: !"unsupported op"
Abort trap: 6**

**To Reproduce**
1. Go to terminal and type :  ilab model serve

2. Go to another terminal and type : ilab model chat
3. send any messag
4. See connection error

**Expected behavior**
it should respond back with message
**Screenshots**
<img width="1362" alt="image" src="https://github.com/user-attachments/assets/8d756de4-7abc-4019-8e99-e06360677013">

**Device Info (please complete the following information):**
 - Hardware Specs: [e.g. Apple M2 Pro Chip, 16 GB Memory, etc.] : 2.2 GHz 6-Core Intel Core i7
 - OS Version: [e.g. Mac OS 14.4.1, Fedora Linux 40] : Sonoma 14.6.1
 - Python Version: [output of `python --version`] : 3.10.4
 - InstructLab Version: [output of `ilab system info`] : instructlab.version: 0.17.1
sys.version: 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)]
sys.platform: darwin
os.name: posix
platform.release: 23.6.0
platform.machine: x86_64
torch.version: 2.2.2
torch.backends.cpu.capability: AVX2
torch.version.cuda: None
torch.version.hip: None
torch.cuda.available: False
torch.backends.cuda.is_built: False
torch.backends.mps.is_built: True
torch.backends.mps.is_available: True
llama_cpp_python.version: 0.2.75
llama_cpp_python.supports_gpu_offload: True

**Additional context**

**Comment by bjhargrave** [comment]
You are using an Intel Mac, which is not supported, and InstructLab 0.17, which is 4 months old (0.19.3 is the current release) and uses an older version of llama_cpp. 

I would suggest updating to the current 0.19.3 release of InstructLab and trying again.

**Comment by kushalpuri0817** [comment]
Thanks, i tried to upgrade to the latest version using this command ``` pip install instructlab --upgrade ``` but it didnt upgrade after i ran ` ilab sysinfo` command : instructlab.version: 0.17.1
sys.version: 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)]
sys.platform: darwin
os.name: posix
platform.release: 23.6.0
platform.machine: x86_64
torch.version: 2.2.2
torch.backends.cpu.capability: AVX2
torch.version.cuda: None
torch.version.hip: None
torch.cuda.available: False
torch.backends.cuda.is_built: False
torch.backends.mps.is_built: True
torch.backends.mps.is_available: True
llama_cpp_python.version: 0.2.75
llama_cpp_python.supports_gpu_offload: True

**Comment by bjhargrave** [comment]
People have installed ilab outside of a venv, so upgrading does not work. When your venv is deactivated, `ilab` should not work. If it does, then you need to uninstall, create a new venv (delete the folder of the old one first), activate the new venv, and then install InstructLab.

**Comment by kushalpuri0817** [comment]
not sure if i understood completely but i tried to delete the folder venv and install again **using the commands below** but stilll the version is old. Even, i tried to remove the instructlab folder altogether and rerun all the commands but the version is still the old one as mentioned above.

>>  python3 -m venv --upgrade-deps venv
>>  source venv/bin/activate
>>   CMAKE_ARGS="-DLLAMA_METAL=off" pip install instructlab

**Comment by bjhargrave** [comment]
> not sure if i understood completely

Deactivate any active venv with the `deactivate` command. The see if `ilab --version` works.

```shell
➜  instructlab env:(instructlab) git:(main) ilab --version
ilab, version 0.19.0rc2.dev73
➜  instructlab env:(instructlab) git:(main) deactivate
➜  instructlab git:(main) ilab --version
zsh: command not found: ilab
```

If `ilab` still works after you have deactivated the venv, then you have installed InstructLab outside of a virtual environment and need to uninstall it first.
