### ISSUE TITLE
AMD ROCm 6.2: Update to torch-2.4.1

### ISSUE THREAD

**Issue by prarit** [instructlab/instructlab#2446]
**Is your feature request related to a problem? Please describe.**
AMD ROCm 6.2 requires torch-2.4.1 and cannot be used with the existing instructlab which bounds torch support to torch-2.4.0.

**Describe the solution you'd like**
instructlab should support at a minimum torch-2.4.1

**Additional context**
This is not a trivial change and requires testing of the resulting AMD images.

**Comment by nathan-weinberg** [comment]
How does this differ from https://github.com/instructlab/instructlab/issues/2437?

**Comment by JamesKunstle** [comment]
We bumped torch to <2.5 in the upstream!
