### ISSUE TITLE
TGIS (text-generation-inference) path for running serve

### ISSUE THREAD

**Issue by markstur** [instructlab/instructlab#252]
We had a prototype using TGIS, but it is not in repo because we want one simple path, but maybe now is the time since it has been asked for.

It would probably be stashed as an advanced path -- keeping the simple path simple -- but sharing it in a subdir is a good start if it is ready to share.

**Comment by nathan-weinberg** [comment]
Closing since my last question went unanswered and the issue is now stale - that being said happy to reopen if this is something we will want.
