### ISSUE TITLE
System profile prompting has inconsistent numbering

### ISSUE THREAD

**Issue by nathan-weinberg** [instructlab/instructlab#2608]
**What is the current experience of ilab you've found issue with?**
We have several menus where `[0]` is the "default" option but users can't actually see what it is and get misleading or confusing behavior if they select it

Example below - I hit enter without picking a number, and ilab assumed I picked NVIDIA.

```bash
Please choose a system profile.
 Profiles set hardware-specific defaults for all commands and sections of the configuration.
First, please select the hardware vendor your system falls into
[1] AMD
[2] APPLE
[3] INTEL
[4] NVIDIA
Enter the number of your choice [0]: 
[1] NVIDIA A100 X2
[2] NVIDIA A100 X4
[3] NVIDIA A100 X8
[4] NVIDIA H100 X2
[5] NVIDIA H100 X4
[6] NVIDIA H100 X8
[7] NVIDIA L4 X8
[8] NVIDIA L40S X4
[9] NVIDIA L40S X8
Enter the number of your choice [hit enter for hardware defaults] [0]: 
No profile selected - any hardware acceleration for training must be configured manually.
```

**How do you think the described experience should be?**
The first menu should list `[0] None of the below` and default to exiting early with no profile selected with the same message we give for the second menu, i.e. `No profile selected - any hardware acceleration for training must be configured manually.`

The second menu should list `[0] Hardware defaults (no profile)`

**What is the benefit of the change you are proposing?**
Much less confusing experience for the user

**Comment by nathan-weinberg** [comment]
cc @cdoern @JustinXHale curious y'alls thoughts on this

**Comment by JustinXHale** [comment]
I agree the messaging is very confusing @nathan-weinberg. There are a few things that could be done here:

- Clearer messaging: ex. _Enter the number of your chose or [0] for no selection_
- Add [0] to the menu[0 for none/skip] in the menu

**Comment by cdoern** [comment]
Yeah, this is a bug. 

Though, i don't think having a [0] None option makes sense. 

If a user doesn't have an intel, amd, mac, Nvidia machine..... what do they have? Those are the only hw configurations we support. 


The `no profile` option REALLY confused QE and users with training profiles. I don't think it makes sense to have here.
