### ISSUE TITLE
Implement command to push models to HuggingFace

### ISSUE THREAD

**Issue by cdoern** [instructlab/instructlab#2642]
the HuggingFace API allows for uploading both files and folders: https://huggingface.co/docs/huggingface_hub/main/en/guides/upload

This API should be used to push both GGUF and Safetensor/.bin directories to hf. 

using the new `--model` standards, the flag should be able to figure out if this is a GGUF, a folder of safetensors, or a .bin folder.

The interface used in this command should be extendable, similarly to the download one, so that other backends like OCI can easily be added in.

**Comment by nathan-weinberg** [comment]
Some of this code can be reused as well for the initial wrapping: https://github.com/aldopareja/orchestrator/tree/main/publisher

I will be working on a single PR for this in conjunction with skeletoning some stuff out for https://github.com/instructlab/instructlab/issues/2672
