### ISSUE TITLE
Add Success Confirmation and Consistent Color Feedback for Installation Completion

### ISSUE THREAD

**Issue by JustinXHale** [instructlab/instructlab#2650]
### Issue

Add Success Confirmation and Consistent Color Feedback for Installation Completion

### Overview

The CLI currently lacks a clear success message after installation, which may leave users uncertain if the process completed correctly. Additionally, success messages lack color coding, unlike warnings, making completion less visually intuitive. This enhancement proposes adding a green-colored success confirmation (e.g., “Installation completed successfully”) along with optional "Next Steps" guidance (e.g., "Run ilab config init") to improve user clarity, consistency, and flow.

![image](https://github.com/user-attachments/assets/fcfac556-878f-4b77-b7ce-f66af1e34811)

### Observations

1. **Lack of Success Confirmation:**

    * The output ends without any clear confirmation of successful installation, which could leave users uncertain about whether the process completed as intended.
2. __Inconsistent Color Usage__:
    * There’s color coding for warnings but not for success, which might make it less intuitive for users to identify successful completion. Color feedback is generally useful for guiding users’ attention.

### 

### Suggestions for CLI Enhancement

1. __Add a Clear Success Message__:
    * A confirmation message, such as __"Installation completed successfully"__, could be added at the end of the installation process. This message would provide clarity and reassure users that everything went as planned.
2. __Use Color for Success Messages__:
    * Since warnings are already color-coded, using a distinct color (such as __green__ for success) would improve consistency and reinforce visual cues. Colorful feedback helps users quickly identify the outcome, aligning with standard CLI practices for accessible and intuitive feedback.
        1. __Suggestion__: Implement a green color for success confirmation. If the CLI supports ANSI colors, you could display success messages in green, while keeping warnings in red/yellow.
            1. Without ANSI colors, consider alternative ways to emphasize messages, such as:
                1. Using symbols (e.g., ✅ Success instead of color-coding).
                2. Using uppercase letters or separators to distinguish messages. [SUCCESS] or [ERROR]
3. __Align with User Motivation and Usability__:
    * As noted in the feedback, adding a success confirmation helps maintain user motivation. Clear completion indicators keep users engaged and reduce the likelihood of confusion or re-running commands unnecessarily.
        2. __Consider__ including a brief next step or “What’s next?” message after installation, guiding users to configure or initialize InstructLab if required.

### 

### Example Output

After a successful installation, the CLI could display something like:

```
✅ Installation completed successfully.
Next Steps: Run `ilab config init` to initialize your configuration.
```

Instead of stopping at “Installation completed successfully,” adding __“Next Steps: Run ilab config init to initialize your configuration”__ immediately empowers users to continue smoothly, ensuring they’re fully set up without unnecessary friction.

**Comment by cdoern** [comment]
I don't know if we have control over `pip` commands as this is a python package installer. 

if we were to switch to a custom `setup.py` system (this is typically considered an out of date method for python projects) we may be able to expose something like this. Otherwise, we are stuck with pip's behaviors.
