### ISSUE TITLE
Enhance ilab model list Command with Model Categories and Descriptions

### ISSUE THREAD

**Issue by JustinXHale** [instructlab/instructlab#2652]
# Issue

Enhance `ilab model list` Command with Model Categories and Descriptions

## Overview
The current `ilab model list` command displays downloaded models but lacks categorization or descriptions, which could help users understand the purpose of each model. This enhancement proposes adding a column to specify the model category (e.g., Interaction, Teacher, Testing/Fine-Tune) and displaying brief descriptions of each category when running the command. This would improve usability and provide more context to users about the models.

![image](https://github.com/user-attachments/assets/89018520-70a7-4961-8cda-503221e3b640)

### Lack of Model Category
- Users may find it unclear what each model’s role is without categorization, making it harder to identify which models are suited for specific tasks.

### No Context for Model Types
- Users may not know the purpose of each model type (e.g., Interaction, Teacher, Testing/Fine-Tune) without additional guidance, potentially leading to confusion or misapplication.

### Add a Model Category Column
- Include a column in the `ilab model list` output to specify each model's category. This column could list categories like Interaction Model, Teacher Model, or Testing/Fine-Tune Model.
  - **Example:** Adding a Category column between Model Name and Last Modified.

### Display Category Descriptions
- Upon the first run of `ilab model list`, provide a brief description of each category to help users understand the purpose of each model type.
  - **Example Descriptions:**
    - **Interaction Model:** Designed for interactive tasks, such as responding to user inputs or real-time interactions.
    - **Teacher Model:** Used for generating training data, often serving as a reference for supervised learning tasks.
    - **Testing/Fine-Tune Model:** Optimized for fine-tuning or testing specific tasks, allowing customization for particular use cases.

## Example Enhanced Output (with New Column)

```plaintext
Available Model Categories:
- Interaction Model: Designed for interactive tasks, such as responding to user inputs or real-time interactions.
- Teacher Model: Used for generating training data, often serving as a reference for supervised learning tasks.
- Testing/Fine-Tune Model: Optimized for fine-tuning or testing specific tasks, allowing customization for particular use cases.

+--------------------------------------------+---------------------+---------+----------------------+
| Model Name                                  | Last Modified       | Size    | Category             |
+--------------------------------------------+---------------------+---------+----------------------+
| model 1                                     | 2024-11-04 16:52:37 | 4.1 GB  | Interaction Model    |
| model 2                                     | 2024-11-04 16:54:39 | 4.1 GB  | Teacher Model        |
| model 3                                     | 2024-11-04 16:55:10 | 2.5 GB  | Testing/Fine-Tune    |
+--------------------------------------------+---------------------+---------+----------------------+
```

```
Available Models

Available Model Categories:
- Interaction Model: Designed for interactive tasks, such as responding to user inputs or real-time interactions.
- Teacher Model: Used for generating training data, often serving as a reference for supervised learning tasks.
- Testing/Fine-Tune Model: Optimized for fine-tuning or testing specific tasks, allowing customization for particular use cases.

+--------------------------------------------+---------------------+---------+
| Model Name                                  | Last Modified       | Size    |
+--------------------------------------------+---------------------+---------+

Teacher Models:
| model 1                                     | 2024-11-04 16:52:37 | 4.1 GB  |
| model 2                                     | 2024-11-04 16:54:39 | 4.1 GB  |

Interaction Models:
| model 3                                     | 2024-11-04 16:55:10 | 2.5 GB  |
| model 4                                     | 2024-11-04 16:57:20 | 3.2 GB  |

Testing/Fine-Tune Models:
| model 5                                     | 2024-11-04 17:00:05 | 2.8 GB  |
+--------------------------------------------+---------------------+---------+
```
### Improves User Understanding
- Adding categories and descriptions helps users quickly understand the purpose of each model and select the appropriate one for their needs.

### Enhances Usability and Clarity
- This enhancement makes the `ilab model list` output more informative, reducing the learning curve for new users and preventing misapplication of models.

### Streamlines Workflow
- By providing immediate context, users can identify relevant models without needing to consult external documentation, making workflows more efficient.

**Comment by reidliu41** [comment]
seems working in here [1985](https://github.com/instructlab/instructlab/pull/1895) about list
