### ISSUE TITLE
Clarify Default Selection and Profile Options in ilab config init Command

### ISSUE THREAD

**Issue by JustinXHale** [instructlab/instructlab#2653]
# Issue

Clarify Default Selection and Profile Options in `ilab config init` Command

## Overview
The `ilab config init` command includes a prompt to select a hardware profile for training but lacks clear guidance on the default option, especially concerning `[0] No profile`. Users may be uncertain about what pressing Enter does by default and what the implications are of choosing "No profile." Simplifying the language and adding context to the profile options would enhance readability and provide users with a clearer understanding of hardware acceleration options.

![image](https://github.com/user-attachments/assets/8e0f198a-b822-4d7b-bb3c-a33054960bdc)

## Observations

1. **Lack of Clear Default Option Guidance**  
   The prompt states “Enter the number of your choice [hit enter for hardware defaults] [0],” but it’s not clear to users what pressing Enter will do, particularly concerning the `[0] No profile` option.

2. **Insufficient Explanation for “No Profile”**  
   Users may not understand the implications of selecting `[0] No profile`, which requires manual configuration for hardware acceleration. Additional context would help users make informed decisions.

3. **Technical Language**  
   Phrases like “assist with the complexity of configuring InstructLab training” could be simplified for better readability.

## Suggestions for CLI Enhancement

1. **Add Clearer Default Option Indicator**  
   Modify the prompt to specify that pressing Enter will select `[0] No profile`, reducing potential confusion.
   - **Suggestion:** Change “Enter the number of your choice [hit enter for hardware defaults] [0]” to “Enter the number of your choice [Press Enter to select [0] No profile]”.

2. **Provide Additional Context for “No Profile”**  
   Next to `[0] No profile`, add a brief explanation of what it means for training without hardware-specific optimization.
   - **Suggestion:** Add a line such as “No hardware-specific optimization; manual configuration required for hardware acceleration.”

3. **Simplify Technical Language**  
   Use simpler language to describe the purpose of training profiles to reduce cognitive load.
   - **Suggestion:** Replace “assist with the complexity of configuring InstructLab training” with “help configure InstructLab training.”

## Example Output
```
Please choose a train profile to use.
Train profiles help configure InstructLab training for specific GPU hardware.
You can still use hardware acceleration even if your hardware is not listed.
[0] No profile  -  manual configuration required.
[1] Nvidia A100/H100 x2 (A100_H100_x2.yaml)
[2] Nvidia A100/H100 x4 (A100_H100_x4.yaml)
[3] Nvidia A100/H100 x8 (A100_H100_x8.yaml)
[4] Nvidia L40 x4 (L40_x4.yaml)
[5] Nvidia L40 x8 (L40_x8.yaml)
[6] Nvidia L4 x8 (L4_x8.yaml)
Enter the number of your choice [Press Enter to select `[0] No profile`]: 0
No profile selected - any hardware acceleration for training must be configured manually.
--------------------------------------------------------
✅ Initialization completed successfully!
You’re ready to start using `ilab`. Enjoy!
--------------------------------------------------------

```

**Comment by cdoern** [comment]
hey @JustinXHale, the output attached is for `training profiles` which are deprecated as of 0.21. Please find attached an image of the new system profile output. I hope it makes more sense:

<img width="918" alt="Screenshot 2024-11-15 at 9 38 03 PM" src="https://github.com/user-attachments/assets/72e49711-354a-4718-8a0c-f61c6429298a">

**Comment by cdoern** [comment]
I could see an argument to be made that `[0]` should have more info right off the bat. However, system profiles are a bit easier to understand than training profiles in that: if the user isn't choosing AMD, Intel, Apple, Nvidia.... then choosing [0] must logically indicate `"I don't want any of this hardware pre-configuration"`

let me know what you think makes sense here.

**Comment by JustinXHale** [comment]
@cdoern I think saying No System Profile is good.
