### ISSUE TITLE
Issue with documentation on readme regarding GPU (shows --device cpu)

### ISSUE THREAD

**Issue by cdrage** [instructlab/instructlab#2699]
**What is the current experience of ilab you've found issue with?**

The command here: https://github.com/instructlab/instructlab?tab=readme-ov-file#train-the-model-locally-with-gpu-acceleration

Shows ` --device cpu` even though that it's a GPU pipeline.

**How do you think the described experience should be?**

Corrected command

**What is the benefit of the change you are proposing?**

GPU

**If applicable, how would backwards-compatability be handled?**

N/A

**Additional context**

N/A

**Comment by Ankush1oo8** [comment]
what to change exactly
