### ISSUE TITLE
Expose the ilab model serve --host_port configuration option in the CLI

### ISSUE THREAD

**Issue by nerdalert** [instructlab/instructlab#2774]
**Is your feature request related to a problem? Please describe.**
It would be great to serve multiple models via ilab. The primary scenario I have is for post tuning model chat eval for the UI giving the user both the pre-trained and post-trained outputs for them to query to validate their submission.

The current workaround llama-cpp.server or vllm, which expose host/port per process for multiple inferences. 
For example:

```bash
python -m llama_cpp.server  --model ~/.local/share/instructlab/checkpoints/ggml-model-f16.gguf --host 0.0.0.0 --port 8000
python -m llama_cpp.server --model ~/.cache/instructlab/models/granite-7b-lab-Q4_K_M.gguf --host 0.0.0.0 --port 8001
```

Having it natively available in the CLI would reduce the dependancies needed for setup and a cleaner UX.

**Describe the solution you'd like**
Expose the host_port config option in the serve section as a CLI flag e.g. `--host_port` to override the host_port config.yaml option and allow the user to run multiple instances.

**Additional context**
Happy to cut the PR for it, just wanted to pop an issue to see if folks are open to it before I write the code. Ty!

**Comment by nathan-weinberg** [comment]
@nerdalert how does this differ from https://github.com/instructlab/instructlab/issues/2604?

**Comment by nerdalert** [comment]
@nathan-weinberg thanks I totally missed that! Exactly what I need. I will close this to declutter your issues and track on that issue.

**Comment by nathan-weinberg** [comment]
@nerdalert no worries! appreciate any reviews on that PR! perhaps this is the push we need to move it forward :smile:
