### ISSUE TITLE
Performance Documentation

### ISSUE THREAD

**Issue by tharapalanivel** [instructlab/instructlab#310]
Add tps baseline numbers and collect performance stats as we tweak defaults for hyperparameters. Potentially could evolve into the place to also track those tuning/tweaking parameters or even track versions if the defaults change.

**Comment by nathan-weinberg** [comment]
@tharapalanivel is this still relevant or can it be closed?

**Comment by nathan-weinberg** [comment]
Closing for now, feel free to reopen if you want to take this on
