### ISSUE TITLE
Bug: Kaggle install consistent dependencies for the LoRA training notebook

### ISSUE THREAD

**Issue by RobotSail** [instructlab/instructlab#348]
An issue discovered when running our notebooks in Kaggle is that the dependencies it'll use are not consistent at all.
For example, sometimes a difference in which Pandas version was installed led to a failure to properly read the dataset head in one of our cells.

We need to create a `requirements.txt` file to lock the dependencies that we're actually using.

**Comment by nathan-weinberg** [comment]
@RobotSail is this still relevant or can it be closed?

**Comment by RobotSail** [comment]
@nathan-weinberg Not at all relevant.
