### ISSUE TITLE
lab train errors out on 16GB M1 Mac

### ISSUE THREAD

**Issue by alinaryan** [instructlab/instructlab#380]
hitting this error on an M1 mac while running lab train:

`libc++abi: terminating due to uncaught exception of type std::runtime_error: [METAL] Command buffer execution failed: Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)`

Tried increasing the VRAM with `sudo sysctl 'debug.iogpu.wired_limit=12345'` and still saw the same issue. 

There seems to be a memory spike that kills the process:

<img width="1080" alt="Screenshot 2024-03-06 at 2 34 30 PM" src="https://github.com/instruct-lab/cli/assets/66272285/e97cb290-6a43-4dd1-bec0-6f0d63e8a30c">

**Comment by derekhiggins** [comment]
you could try applying this PR https://github.com/instructlab/instructlab/pull/1008
Then running with
`ilab train --device cuda --override-training-args '{"bf16":false, "gradient_checkpointing":true, "gradient_accumulation_steps":8}'`

worked for me on colab, iirc using about 14.7GB of vram
(notebook here https://colab.research.google.com/drive/16DK68txzhCeLxBJ4YCaIixuZocCoEuXU#scrollTo=rRNnMNoIGpIa )

**Comment by leseb** [comment]
@alinaryan does this [comment](https://github.com/instructlab/instructlab/issues/380#issuecomment-2087683005) give you a resolution to this bug? If so, can we close this? Or is there anything else to investigate? Thanks!

**Comment by alinaryan** [comment]
Sorry for the delay - I'll prioritize trying this again this week and go from there.

**Comment by nathan-weinberg** [comment]
@alinaryan is this still relevant or can it be closed?

**Comment by alinaryan** [comment]
I'm going to close this, I am not able to reproduce
