### ISSUE TITLE
llamacpp/quantize binary in git repo

### ISSUE THREAD

**Issue by giuseppe** [instructlab/instructlab#438]
currently there is a binary file distributed as part of the git repository.

I understand it simplifies the distribution, so I am opening the issue just to not track it somewhere. 

What is the plan for it?  Should it be a git submodule and built from the llama.cpp repository?

**Comment by mairin** [comment]
@tiran Wondering if you might have cycles to work on this for the May 30 release. Let us know and we can pop it onto the 5/30 milestone, or we can keep it on the backlog for now.

**Comment by tiran** [comment]
End of May is doable. I'm going to need somebody with a Mac book to test the new package.

**Comment by markstur** [comment]
we shouldn't put a binary in git.

Ideally if we need it, we'd build it and attach it to releases.  Also dev instructions.  

Do we need a fork of llama.cpp to have fixes for quantize and build that in our build?

Also I can test on Mac

**Comment by tiran** [comment]
The idea is to move the `quantize` binary into a separate project and Python package. This allows us to have a conditional dependency on the binary. MacOS users will then get the binary automatically. I have created https://github.com/tiran/instructlab-quantize/ .

```
# requirements.txt
instructlab-quantize; sys_platform == 'darwin' and platform_machine == 'arm64'
```

```python
# Python code
if sys.platform == "darwin" and  platform.machine() == "arm64":
    from instructlab_quantize import run_quantize

    run_quantize("llama.cpp/models/ggml-vocab-llama.gguf", "Q4_K_M")
```

**Comment by hickeyma** [comment]
@tiran This looks like a nice approach. I can test as well once you are ready.

**Comment by tiran** [comment]
Go ahead, the package is on PyPI and the PR is ready to test.

**Comment by tiran** [comment]
I have extended my instructlab-quantize package for @cdoern . It now comes with Linux binaries for x86_64 and aarch64 with RHEL 8 ABI. The binaries work on all Linux distros with glibc ABI 2.27 or newer.
