### ISSUE TITLE
make the maxOS and Linux backend of `ilab train` consistent

### ISSUE THREAD

**Issue by xukai92** [instructlab/instructlab#481]
with https://github.com/instruct-lab/cli/pull/374 merged, we now have both macOS support via MLX and Linux support via PyTorch (CPU for now but easily for CUDA).
however, their user-facing interface is a bit inconsistent
- MLX assumes `--iters` but PyTorch assumes `--num-epochs`
- the output folders of the training artifacts are different

**Comment by mairin** [comment]
- [] make sure linux train only does train
- [] make sure convert on linux works
- [] ilab test on linux works
- [] make sure if there's shared code both platforms use it
- [] make sure models output to the same place
- [] make arguments more consistent across platforms (eg --ters vs --num-epocs)
- [] expose additional argments

**Comment by mbestavros** [comment]
Per @khaledsulayman, this is pretty tightly coupled with https://github.com/instructlab/instructlab/issues/659

**Comment by nathan-weinberg** [comment]
This is duplicated by https://github.com/instructlab/instructlab/issues/1108 which @cdoern has an open PR for https://github.com/instructlab/instructlab/pull/1157, so closing this one out
