### ISSUE TITLE
improve Linux backend of `lab train`

### ISSUE THREAD

**Issue by xukai92** [instructlab/instructlab#482]
a few things to improve upon https://github.com/instruct-lab/cli/pull/374
- [x] tighten requirements.txt
- [ ] addressing TODOs

**Comment by nathan-weinberg** [comment]
@alimaredia is this still relevant or can it be closed?

**Comment by nathan-weinberg** [comment]
Closing for now, @alimaredia feel free to reopen if you want to revisit it
