### ISSUE TITLE
Replace os.system("python ...") with subprocess.check_call([sys.executable, ...])

### ISSUE THREAD

**Issue by tiran** [instructlab/instructlab#530]
The `cli.lab` uses `os.system()` to run sub processes. The use of `os.system` is problematic for two major reasons:

* The call does not raise an exception if a sub process fails. The main program just continues to run.
* The function requires a properly shell-escaped argument. If the argument is not correctly escaped for the user's current shell, then the command can fail in all sorts of funny ways, e.g. with space or non-ASCII directory name.

I highly recommend to replace any use of `os.system()` with `subprocess.check_call()`

Instead of
```python
cmd = f"{script} --gguf {gguf_model_path} --repo {tokenizer_dir} --mlx-path {dest_model_dir}"
os.system("python {}".format(cmd))
```
do
```python
subprocess.check_call([sys.executable, script, "--gguf", gguf_model_path, "--repo", tokenizer_dir, "--mlx-path", dest_model_dir])
```

`check_call()` checks the exit status of a command and fails with an exception if the program fails.

**Comment by nathan-weinberg** [comment]
This issue is obsolete due to https://github.com/instructlab/instructlab/issues/438
