### ISSUE TITLE
issues install mlx on macos/aarch64, python3.12, pip 23.3.1/24

### ISSUE THREAD

**Issue by jmtd** [instructlab/instructlab#554]
Attempting to follow the install recipe. First, system python3

```
bash-5.2$ python3 --version
Python 3.8.9
bash-5.2$ python3 -m venv venv
bash-5.2$ source venv/bin/activate
(venv) bash-5.2$ pip install git+ssh://git@github.com/instruct-lab/cli.git@stable
...
ERROR: Package 'cli' requires a different Python: 3.8.9 not in '>=3.9'
```

OK. I have python3.12 available too (via Brew). With a new venv 

```
bash-5.2$ deactivate
bash-5.2$ rm -rf venv
```

then

```
bash-5.2$ python3.12 --version
Python 3.12.1
bash-5.2$ python3.12 -m venv venv
source bash-5.2$ source venv/bin/activate
(venv) bash-5.2$ pip install git+ssh://git@github.com/instruct-lab/cli.git@stable
...

ERROR: Could not find a version that satisfies the requirement mlx!=0.3.*,!=0.4.*,!=0.5.0,<0.6.0,>=0.2.0 (from cli) (from versions: none)
ERROR: No matching distribution found for mlx!=0.3.*,!=0.4.*,!=0.5.0,<0.6.0,>=0.2.0
```

and indeed, `pip install mlx==0.6.0` in isolation likewise fails.

I'm not enough of a Python expert to understand what's missing, or how to instruct pip where/how to install mlx. Any help gratefully received; in turn I could explore improving the docs.

**Comment by nathan-weinberg** [comment]
@jmtd Is still an issue for you? We can escalate if so

**Comment by tiran** [comment]
No response from original poster since April. I'm closing the bug. Please open a new bug if  the problem persists.
