### ISSUE TITLE
adding more details / clarify workflow chart

### ISSUE THREAD

**Issue by xukai92** [instructlab/instructlab#592]
feedbacks from the channel

> side note - maybe the Lab list box in https://github.com/instruct-lab/cli/blob/main/docs/workflow.png should say view the taxonomy diff to be clear
-- Jaideep

**Comment by nathan-weinberg** [comment]
There's going to be a heavy lift of docs with the upcoming release - this one is fairly out-of-date at this point so I'm going to close it
