### ISSUE TITLE
lab serve should automatically reserve only the amount of GPU layers available

### ISSUE THREAD

**Issue by cdoern** [instructlab/instructlab#624]
`lab serve` has a `--gpu-layers` option that one needs to specify if you are running on a machine with limited GPU memory. We should figure out a way (either by trial and error or via some system query) to ensure that `lab serve` never takes ALL of the GPU memory leading to the command failing.

Possibly roll other limited resource GPU enablements into the PR for this issue as they are found.

**Comment by nathan-weinberg** [comment]
@cdoern is this issue still relevant or can it be closed?
