### ISSUE TITLE
`lab test` should be implemented for Linux

### ISSUE THREAD

**Issue by bbrowning** [instructlab/instructlab#659]
As we get closer to merging reliable Linux training, the next step is to figure out how to get `lab test` ported to Linux as well.

**Comment by kelbrown20** [comment]
Note: Also remove note in README for Mac only, or say its Mac and Linux only, when this is implemented:
https://github.com/instructlab/instructlab/blob/main/README.md#-test-the-newly-trained-model

I can also do this if needed!

**Comment by nathan-weinberg** [comment]
@mbestavros was this something you were interested in picking up?

**Comment by jaideepr97** [comment]
as part of @cdoern's redesign we will be renaming this to `lab inference` since `lab test` is kind of vague and unintuitive

**Comment by makelinux** [comment]
> [@mbestavros](https://github.com/mbestavros) was this something you were interested in picking up?

I am picking up.
