### ISSUE TITLE
cmake minimum version not specified in docs

### ISSUE THREAD

**Issue by candita** [instructlab/instructlab#672]
The lab cli doesn't install for me because it uses a "cmake -c" command that's not available in version 3.26.5.   What version is acceptable?
 
Excerpt of output from the pip install:
....
 Building wheel for llama-cpp-python (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/cholman/code/instruct-lab/cli/venv/bin/python3.9 /home/cholman/code/instruct-lab/cli/venv/lib64/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpcig9yzut
       cwd: /tmp/pip-install-h97hh46l/llama-cpp-python
  Complete output (52 lines):
  *** scikit-build-core 0.8.2 using CMake 3.26.5 (wheel)
  *** Configuring CMake...
  2024-03-18 21:23:31,659 - scikit_build_core - WARNING - libdir/ldlibrary: /usr/lib64/libpython3.9.so is not a real file!
  2024-03-18 21:23:31,659 - scikit_build_core - WARNING - Can't find a Python library, got libdir=/usr/lib64, ldlibrary=libpython3.9.so, multiarch=x86_64-linux-gnu, masd=None
  loading initial cache file /tmp/tmpcu8heskk/build/CMakeInit.txt
  -- The C compiler identification is GNU 8.5.0
  -- The CXX compiler identification is unknown
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - failed
  -- Check for working CXX compiler: /usr/bin/cmake
  -- Check for working CXX compiler: /usr/bin/cmake - broken
  CMake Error at /usr/share/cmake/Modules/CMakeTestCXXCompiler.cmake:60 (message):
    The C++ compiler
  
      "/usr/bin/cmake"
  
    is not able to compile a simple test program.
  
    It fails with the following output:
  
      Change Dir: /tmp/tmpcu8heskk/build/CMakeFiles/CMakeScratch/TryCompile-20VbGg
  
      Run Build Command(s):/tmp/pip-build-env-v83e3pz_/normal/lib64/python3.9/site-packages/ninja/data/bin/ninja -v cmTC_b4e34 && [1/2] /usr/bin/cmake    -o CMakeFiles/cmTC_b4e34.dir/testCXXCompiler.cxx.o -c /tmp/tmpcu8heskk/build/CMakeFiles/CMakeScratch/TryCompile-20VbGg/testCXXCompiler.cxx
      FAILED: CMakeFiles/cmTC_b4e34.dir/testCXXCompiler.cxx.o
      /usr/bin/cmake    -o CMakeFiles/cmTC_b4e34.dir/testCXXCompiler.cxx.o -c /tmp/tmpcu8heskk/build/CMakeFiles/CMakeScratch/TryCompile-20VbGg/testCXXCompiler.cxx
      CMake Warning:
        Ignoring extra path from command line:
  
         "/tmp/tmpcu8heskk/build/CMakeFiles/CMakeScratch/TryCompile-20VbGg/testCXXCompiler.cxx"
  
  
      CMake Error: Unknown argument -c
      CMake Error: Run 'cmake --help' for all supported options.
      ninja: build stopped: subcommand failed.
  
  
  
  
  
    CMake will not be able to correctly generate this project.
  Call Stack (most recent call first):
    CMakeLists.txt:3 (project)
  
  
  -- Configuring incomplete, errors occurred!
  
  *** CMake configuration failed
  ----------------------------------------
  ERROR: Failed building wheel for llama-cpp-python
Successfully built cli
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 20.2.4; however, version 24.0 is available.
You should consider upgrading via the '/home/cholman/code/instruct-lab/cli/venv/bin/python3.9 -m pip install --upgrade pip' command.

(venv) $ cmake -c
CMake Error: Unknown argument -c
CMake Error: Run 'cmake --help' for all supported options.
(venv) $ cmake --version
cmake version 3.26.5

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by nathan-weinberg** [comment]
@candita are you able to reproduce this issue with the latest `ilab` version?

**Comment by nathan-weinberg** [comment]
Closing this, @candita feel free to reopen if it's still an issue for you
