### ISSUE TITLE
Wrong pyspelling config

### ISSUE THREAD

**Issue by schuellerf** [instructlab/instructlab#677]
The config `.spellcheck.yml` is wrong and ignores all lines after ` ``` ` **until the end of the file** as the regex is greedy (including newlines)

The fix is to remove the `(?s)`
```
--- a/.spellcheck.yml
+++ b/.spellcheck.yml
@@ -19,7 +19,7 @@ matrix:
       # ```language
       # content
       # ```
-      - open: '(?s)^(?P<open> *`{3,}).*$'
+      - open: '^(?P<open> *`{3,}).*$'
         close: '^(?P=open)$'
       # Ignore text between inline back ticks
       - open: '(?P<open>`+)'
```

I didn't dare to commit this as PR as then ALL documents need to be updated.

**Comment by booxter** [comment]
Just noticed this issue while looking through the backlog. I think this is addressed in https://github.com/instructlab/instructlab/pull/944
