### ISSUE TITLE
[doc] Add Troubleshooting for pip install llama-cpp-python ERROR: Failed building wheel for llama-cpp-python

### ISSUE THREAD

**Issue by skrthomas** [instructlab/instructlab#680]
This[ known issue](https://docs.google.com/spreadsheets/d/1jZIOO2WvhCNk5dh-n2lA0rA3x_8ehNI0oCQzV0qgUv4/edit#gid=0) was a blocker for me getting up and running for about an hour until I uncovered some context about how to overcome it in a Slack thread search. I know the Requirements section of the Getting started README.md states that C++ compiler is required. However, I think its hard to know how one makes sure this is installed and warrants more context in the form of a Troubleshooting header. 

The error text is also confusing because it leads you to believe that you need to have XCode installed, which a lot of folks have XCode installed in their Developer Tools, so if they run `xcode select --install` they'll see that `xcode-select: note: Command line tools are already installed.`. And then its sorta hard to guess or know that the Developer Tools XCode doesn't have C++. The Troubleshooting should have guidance for users to know they either need to download XCode from the App Store because this version has C++, or they need to use a package manager like brew, yum, or dnf to install a C++ compiler. 

Personally, once I downloaded XCode from the App Store and installed it, I was able to successfully run the `pip install git+ssh://git@github.com/instruct-lab/cli.git@stable` step and access `lab`

**Comment by cdoern** [comment]
closing as fixed in #1110
