### ISSUE TITLE
llama-cpp-python doesn't automatically pick up Metal on Mac, requires CMake args

### ISSUE THREAD

**Issue by JamesKunstle** [instructlab/instructlab#698]
(Note from Mo: this issue is connected to this doc issue: https://github.com/instructlab/instructlab/issues/680)

When trying to run `lab serve`: 

```
INFO 2024-03-20 14:52:11,866 lab.py:282 Using model 'models/merlinite-7b-Q4_K_M.gguf' with -1 gpu-layers and 4096 max context size.
ggml_metal_init: error: Error Domain=MTLLibraryErrorDomain Code=3 "program_source:3:10: fatal error: 'ggml-common.h' file not found
#include "ggml-common.h"
         ^~~~~~~~~~~~~~~
" UserInfo={NSLocalizedDescription=program_source:3:10: fatal error: 'ggml-common.h' file not found
#include "ggml-common.h"
         ^~~~~~~~~~~~~~~
}
llama_new_context_with_model: failed to initialize Metal backend
Error creating server: failed creating the server application: Failed to create llama_context
```

To rebuild llama-cpp-python with Metal enabled:

`CMAKE_ARGS="-DLLAMA_METAL_EMBED_LIBRARY=ON -DLLAMA_METAL=on" pip3 install llama-cpp-python --no-cache-dir --force-reinstall`

From [this](https://github.com/abetlen/llama-cpp-python/issues/1285) issue resolution.

**Comment by mairin** [comment]
solution:
- docs for manually doing GPU acceleration need to be fixed to have the correct special `make` args. this happens on both mac and linux. this is handled in #680 
- container based installation of llama.cpp that requires logic for configuring llama.cpp to use the available hw

@jaideepr97 longer term effort to move away from mlx to something that is more compatible with pytorch?

**Comment by nathan-weinberg** [comment]
@JamesKunstle is this still relevant or can we close it?

**Comment by alimaredia** [comment]
Due to inactivity and the fact that the llama_cpp_python package has been bumped, this issue is getting closed.
