### ISSUE TITLE
In 'lab chat', tell the user if you are using a default model, please validate --model or -m before running

### ISSUE THREAD

**Issue by DennisPeriquet** [instructlab/instructlab#753]
After running lab init, lab check, lab generate, lab train --device cuda (on Linux), I end up with a new .gguf file:

```bash
$ ls -l models/
total 14145392
-rw-rw-r-- 1 dperique dperique 14484862880 Mar 25 16:43 ggml-model-f16.gguf
lrwxrwxrwx 1 dperique dperique         148 Mar 15 20:56 merlinite-7b-Q4_K_M.gguf -> ../../../../../../../../.cache/huggingface/hub/models--ibm--merlinite-7b-GGUF/blobs/94f3a16321c9604ca22e970f3b89931ae5b4bbfd4c5d996e2bb606c506590666
```

This is the merged model (i.e., original model plus adapter).  If I try to chat with it via `lab chat -m ggml-model-f16.gguf`, it appears to load:

```bash
$ lab chat -m ggml-model-f16.gguf 
╭──────────────────────────────────────────────────────────── system ────────────────────────────────────────────────────────────╮
│ Welcome to Chat CLI w/ GGML-MODEL-F16.GGUF (type /h for help)                                                                  │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
>>>                                                                                                                   [S][default]
```

But that is NOT the correct model -- even though it confidently implies it in the "Welcome ..." message.

You can observe this more clearly using a non existent file:

```bash
$ lab chat -m something_non_existent.lala
╭──────────────────────────────────────────────────────────── system ────────────────────────────────────────────────────────────╮
│ Welcome to Chat CLI w/ SOMETHING_NON_EXISTENT.LALA (type /h for help)                                                          │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
>>>            
```

Clearly, we're defaulting to something (probably in the `config.yaml`) but the user should be informed explicitly -- silence is not acceptable.

With silence, the user may try to test the model manually only to find it does not appear to be fine-tuned.  This in fact was my case as I spent a lot of time trying to understand why my resultant gguf file didn't seem to incorporate my dataset.

Using the correct file loads the expected model:

```bash
$ lab chat -m ./models/ggml-model-f16.gguf
╭──────────────────────────────────────────────────────────── system ────────────────────────────────────────────────────────────╮
│ Welcome to Chat CLI w/ ./MODELS/GGML-MODEL-F16.GGUF (type /h for help)                                                         │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
>>> 
```

And my tests show the model was fine-tuned as expected.

We should validate the existence of the value of the `--model` or `-m` parameter to avoid the user being confused about what model is being used and/or invalidating long hours of testing.

**Comment by mairin** [comment]
@cdoern suggesting for 5/30, when user specifies --model-path, we funnel that into the next lab chat unless they specify --model, and we wire --model up to ab chat to do something meaningful. when they do --model-path in lab serve, changes it in the config. so config.serv.modelpath is used for source of truth for chatting. Something in there needs to be changed for 5.2. 

user experience - if you serve model A, then do chat... it doesn't necessarily use model A (it uses the model configured as default in the config.) 

Default should probably be that chat always uses the model being served... or the model most recently served...
