### ISSUE TITLE
Use Taxonomy schema to validate YAML files

### ISSUE THREAD

**Issue by xukai92** [instructlab/instructlab#760]
Since https://github.com/instruct-lab/taxonomy/pull/616, the taxonomy side has included schema files for validating the Taxonomy YAML. The CLI should also validate with the schema.

~given that we are cloning the taxonomy already, we could just use the schema file from there.
one question is how to do a schema update (like https://github.com/instruct-lab/cli/issues/702, https://github.com/instruct-lab/taxonomy/issues/635) on both side.
CLI side will want to develop the feature first before taxonomy side officially supports that.
@lehors suggested maybe the taxonomy side could take a dev/main branch or a similar main/stable tag idea so they would be able to have an schema in development.~

From @anik120 in https://github.com/instruct-lab/cli/issues/760#issuecomment-2026478007:

We need to think about the implications of needing the taxonomy folder cloned into the current working directory. At the moment, if you make any changes to the cli that pulls in this dependency, the test cases will break. It's also not a great design to need the taxonomy folder in the current working directory. The path of least resistance here if we have a central repository, say `instruct-lab/api` that contains this yaml schema, which is then pulled into both the `taxonomy` repository and the `cli` repository to implement changes needed for the tooling. 

Breakdown of work:

- [x] Create repository for the JSON schema for Taxonomy (https://github.com/instruct-lab/schema/pull/1)
- [x] Add schema checking to CLI (#776)
- [x] Update Taxonomy repository to use the new schema repository (https://github.com/instructlab/taxonomy/pull/721)
- [x] Update CLI repository to use the new schema repository (https://github.com/instructlab/instructlab/pull/913)
- [x] Add additional unit tests
- [x] Refactor redundant code (https://github.com/instruct-lab/cli/pull/841)
- [x] Update documentation

**Comment by hickeyma** [comment]
Closing as tasks now completed. Thanks @bjhargrave for the work on this.
