### ISSUE TITLE
`functional-tests.sh` assumes gnu utils

### ISSUE THREAD

**Issue by russellb** [instructlab/instructlab#775]
When I run `tox -e functional` on my mac, I get a bunch of `printf` and `sed` related errors. It looks like it's from assuming the gnu versions of `printf` (coreutils) and `sed`.

It would be nice for the script to either:

1. Be adjusted to be compatible with the default versions of these utilities on mac
2. Explicitly check that the gnu versions are present and giving a friendly error message if not.

**Comment by leseb** [comment]
Fixed by https://github.com/instructlab/instructlab/pull/1039. Can we close this? Thanks!
