### ISSUE TITLE
Document knowledge doc size limit 

### ISSUE THREAD

**Issue by anik120** [instructlab/instructlab#782]

**Comment by mairin** [comment]
@kelbrown20 complete for taxonomy, working on CLI today

**Comment by mingxzhao** [comment]
While I understand limiting the question to the token max for merlinite, why is the qna pair be limited as well? My understanding is that it is passed to the teacher model as you say but can the context limit of the teacher model not be upped to accommodate this? If the teacher model is a different model than the merlinite model is the max context length still the same for both?

**Comment by bbrowning** [comment]
A larger teacher model can have a larger context window, but the default experience with the `ilab` CLI uses the merlinite-7b-Q4_K_M model that only has a 4096 context size. The `--server-context-size` parameter to `ilab generate` allows you to override this from 4096 to something larger.

And, from a documentation standpoint, you're right that the values here really depend on the model in use and its maximum context size.

**Comment by mingxzhao** [comment]
Thank you for answering. To follow up, I understand that the ilab cli has this max in place, but is this max also set for the teacher model, which based on the documentation is the mixtral 8x7B? My confusion is that even if the ilab has this max, it is never passed the question and answer anyways, it is only ever passed the question with generate, so having the max be a combination of question and answer doesn't quite make sense to me.

**Comment by bbrowning** [comment]
The teacher model is the same merlinite model unless the user changes the default to point to another teacher model they host themselves. And we do pass two question and answer pairs to the teacher model (as examples in the prompt we give it), which by default is the merlinite model with the 4096 max context size.

**Comment by mingxzhao** [comment]
Ahhhh I see I apologize I did not realize this was for the quantized model for the cli. Is there any reason these maxes would need to be implemented in actual pr submissions?

**Comment by bbrowning** [comment]
My personal opinion is that PR submissions to the taxonomy repo should be limited to whatever works by default with the `ilab` CLI. I'm not sure others agree, and there's probably a broader discussion around what role `ilab` plays in taxonomy PR submissions.
