### ISSUE TITLE
ilab diff on a single file fails unless you specify --quiet

### ISSUE THREAD

**Issue by bjhargrave** [instructlab/instructlab#796]
When running diff on an individual file:

```
ilab diff --taxonomy-path=xx.yaml
```

it errors out:

> Reading taxonomy failed with the following error: /Users/hargrave/git/instruct-lab/cli/xx.yaml

If you also specify `--quiet`, then it works.

This is because the non-quiet code path assumes the specified taxonomy path is a folder(git repo):

https://github.com/instruct-lab/cli/blob/eb953979454c546c3206da34316cfe068ad84f0c/cli/lab.py#L241

and does not detect that it is a file like is done in:

https://github.com/instruct-lab/cli/blob/eb953979454c546c3206da34316cfe068ad84f0c/cli/generator/generate_data.py#L632-L633

**Comment by mairin** [comment]
@cdoern will review this
