### ISSUE TITLE
Document git repo fetching errors causes generate to hang

### ISSUE THREAD

**Issue by bbrowning** [instructlab/instructlab#807]
When cloning the git repo of a document, we sometimes end up logging fatal errors but don't actually treat those as fatal for the overall generation, and I ended up in a state where my generate was sitting indefinitely doing nothing because of it. The process was hung here until I killed it.

Some example output below, with the actual git repo URL changed. For the purposes of this example, it's just a self-hosted repo with a self-signed certificate. The underlying error is because of that certificate, but this is just one example of how we can get in a bad state when the repo cloning fails:

```Generating synthetic data using 'merlinite-7b-Q4_K_M' model, taxonomy:'/workspace/taxonomy/qna.yaml' against http://127.0.0.1:38070/v1 server
ERROR 2024-04-04 20:12:11,353 utils.py:210 Error: Cmd('git') failed due to: exit code(128)
cmdline: git clone -v -- https://some-url/my-repo.git /workspace/taxonomy/temp_repo
stderr: 'Cloning into '/workspace/taxonomy/temp_repo'...
fatal: unable to access 'https://some-url/my-repo.git/': SSL certificate problem: self-signed certificate in certificate chain
'
INFO 2024-04-04 20:12:11,361 generate_data.py:595 Content from git repo fetched
INFO 2024-04-04 20:12:11,365 rouge_scorer.py:83 Using default tokenizer.
0%| | 0/10 [00:00<?, ?it/s]INFO 2024-04-04 20:12:11,367 generate_data.py:446 Selected taxonomy path workspace->taxonomy```

**Comment by derekhiggins** [comment]
My Pr for this got accidentally  closed, I haven't re-opened it as I think this bug is no longer happening (I think i was fixed eslewhere)

**Comment by mairin** [comment]
We should probably ensure this isn't happening anymore before closing.

**Comment by bbrowning** [comment]
I can no longer reproduce this issue - errors cloning the git repository now appear fatal and properly exit versus the errors being ignored and incorporated into my training data.

**Comment by nathan-weinberg** [comment]
Per @bbrowning's comment I'm going to close this for now - feel free to reopen if this is still an issue
