### ISSUE TITLE
add maximum number of trials for `ilab generate`

### ISSUE THREAD

**Issue by xukai92** [instructlab/instructlab#811]
an idea of Mark's:
in case the model keeps generating samples that are same, we don't want it working on generation forever.
therefore this parameter is needed.
in the same time, above is an indication of bad seed examples and would probably require refinement of the examples themselves.

**Comment by nathan-weinberg** [comment]
@xukai92 which Mark? @markstur?

**Comment by nathan-weinberg** [comment]
@xukai92 is this issue still relevant?

**Comment by nathan-weinberg** [comment]
Closing due to lack of traction, feel free to reopen if it's still relevant
