### ISSUE TITLE
Reconcile differences for data generation between `ilab` and backend pipeline

### ISSUE THREAD

**Issue by russellb** [instructlab/instructlab#826]
`ilab` has a `generate` subcommand, but its implementation is independent from that of the backend pipeline (mostly here - https://github.com/instruct-lab/datagen-pipeline).

Further, I keep hearing people referring to the `ilab generate` command as more of a demo, and not actually useful for any real purpose. For example, we have @instruct-lab-bot supporting a `generate` command on PRs. The first implementation uses `ilab generate`, but some have asked that to be dropped ASAP in favor of hitting a web service that uses the backend pipeline, because they don't consider the results from `ilab generate` and the local quantized model to be useful. I'm not expressing a specific opinion here - just realying my experience.

This needs to be reconciled in one way or another.  Options could include:

1. Reconciling some functional differences by sharing more code. Get the CLI implementation closer to what's done on the backend to where it's considered good enough to be useful.
2. Document `ilab generate` in the README and command line help text to set proper expectations about the quality of results to expect.
3. Drop `ilab generate` completely if the results it generates are not considered useful.
4. Replace `ilab generate` completely with an implementation that only supports hitting an API exposed by a backend service.

**Comment by nathan-weinberg** [comment]
This is solved by the creation of https://github.com/instructlab/sdg
