### ISSUE TITLE
Logging from `cli/utils` always happens at INFO level

### ISSUE THREAD

**Issue by bbrowning** [instructlab/instructlab#835]
The logger created in `cli/utils` is hardcoded to always use the INFO level, even though there is at least one logging statement in that file that happens at debug level. If we're going to log from within the code there, we should either pass the properly configured logger in when calling those functions or initialize the logger based on the configured logging level directly in utils.py.

**Comment by tiran** [comment]
Logging has been changed and improved since the bug was reported. I'm closing the ticket as fixed. Please open a new bug if  the problem persists.
