### ISSUE TITLE
Extend checks to the Mac train functionality

### ISSUE THREAD

**Issue by hickeyma** [instructlab/instructlab#844]
Extend checking of the [Mac train functionality](https://github.com/instruct-lab/cli/tree/main/cli/train).  

Checks as follows:

- [ ] Linting (not on the copied code)
- [ ] Extend unit tests
- [ ] Functionality tests

This is to check for regressions as fixed in #843

**Comment by nathan-weinberg** [comment]
@hickeyma is this issue still relevant?

**Comment by ktam3** [comment]
Closing this in favor of #2133
