### ISSUE TITLE
EPIC: make sure `ilab serve` runs Mixtral-8x7B properly

### ISSUE THREAD

**Issue by xukai92** [instructlab/instructlab#851]
model: `Q4_K_M` variant from https://huggingface.co/TheBloke/Mixtral-8x7B-v0.1-GGUF

goal: to make sure `ilab serve` runs the `Q4_K_M` variant of Mixtral-8x7B
- https://github.com/instructlab/instructlab/issues/973
  - https://github.com/instructlab/instructlab/blob/main/src/instructlab/config.py#L19 needs to be model-dependent
  - https://github.com/instructlab/instructlab/blob/main/src/instructlab/server.py#L159  needs to be model-dependent
- this will needed to be solved: https://github.com/instruct-lab/cli/issues/29 
- `ilab generate` should produce better samples
- fix references to hard-coded models
+ documentation

PS: I've tested 3rd party serving tools (https://lmstudio.ai) with this setup already so I'm sure as long as we make sure `ilab generate` is correctly set up, we are good with generation from Mixtral locally.

**Comment by mairin** [comment]
@Jaideep suggestion is publishing a chart to show what models can be used and what the HW specs for them is. @cdoern is going to split the first comment into different issues and the docs issue should be assigned to @jaideepr97 

We are going to make this entire EPIC a priority for 5/2 milestone

**Comment by nathan-weinberg** [comment]
Complete per @jaideepr97 and @cdoern
