### ISSUE TITLE
make the full model in GGUF format available on HF

### ISSUE THREAD

**Issue by xukai92** [instructlab/instructlab#853]
HF page: `ibm/merlinite-7b-GGUF`

criteria
- make sure it works fine with `ilab download` with some arg
- make sure it works fine with `ilab chat`
  - like chatting is fine, no weird behavior (unexpected tokens), etc.

**Comment by nathan-weinberg** [comment]
Isn't this done?

**Comment by nathan-weinberg** [comment]
Spoke with @jaideepr97 and he said we can close this out for now
