### ISSUE TITLE
ROCm container no longer builds (clang++: error: cannot find ROCm device library)

### ISSUE THREAD

**Issue by tiran** [instructlab/instructlab#855]
The ROCm container no longer builds. `llama-cpp-python` fails to compile from source with error message `clang++: error: cannot find ROCm device library` or clang not found.

The issue is caused by a recent update. Fedora 40 now uses `clang-18` as default `clang` compiler. However `rocm-device-libs` is build for `clang-17` (`/usr/lib/clang/17/amdgcn/bitcode`). The fix is trivial: append `-17` to `clang` and `clang++`.

**Comment by nathan-weinberg** [comment]
@tiran is this a dup of https://github.com/instructlab/instructlab/issues/1752? if so do you mind if I close this one in favor of the other since there is an associated PR?
