### ISSUE TITLE
add the taxonomy node information as metadata in generated data

### ISSUE THREAD

**Issue by pkyj95** [instructlab/instructlab#858]
For each generated example by "_ilab generate_",  can you please add the taxonomy node where the example belongs to (e.g., "taxonomy": "compositional_skills/STEM/math/area/")? 
This will help us to identify the right SMEs to review the synthetically generated data.

**Comment by nathan-weinberg** [comment]
@pkyj95 can you revisit this with the latest ilab release and see if it is still relevant/update if so?

**Comment by nathan-weinberg** [comment]
Closing due to lack of traction, feel free to reopen if you wish to revisit the issue
