### ISSUE TITLE
inconsistent log-level

### ISSUE THREAD

**Issue by xukai92** [instructlab/instructlab#859]
I found that the `httpx`'s logger is not set to the log level from our config thus introduces (https://github.com/instruct-lab/cli/blob/main/cli/chat/chat.py#L19).

@wking also noted that
> https://github.com/instruct-lab/cli/blob/1d18d7e257529913da76adea222c33bc0ff1a00e/cli/utils.py#L26 is setting up info without a knob that I've found to let the caller override

I feel we should update them to use the log level from config.

**Comment by nathan-weinberg** [comment]
@tiran @leseb i think the changes made since this was opened to the logger address this - can either of you confirm?

**Comment by leseb** [comment]
Fixed in https://github.com/instructlab/instructlab/pull/1443.
