### ISSUE TITLE
Baremetal / non-openshift phased training

### ISSUE THREAD

**Issue by tkatarki** [instructlab/instructlab#865]

**Comment by tiran** [comment]
For the record, deepspeed may simplify Gaudi support. Habana Labs has a fork, see [Habana AI DeepSpeed User Guide]( https://docs.habana.ai/en/latest/PyTorch/DeepSpeed/DeepSpeed_User_Guide/DeepSpeed_User_Guide.html#installing-deepspeed-library).

**Comment by nathan-weinberg** [comment]
Removing the stale label as @JamesKunstle is actively working on this
