### ISSUE TITLE
`ilab serve` + `ilab chat` model-path behavior is wrong

### ISSUE THREAD

**Issue by cdoern** [instructlab/instructlab#880]
a few things I noticed in serve+chat

1. in config.yaml, `chat.model` shouldn't exist. `serve.model_path` should be the only option and chat should pull from it if the user does not specify `--model`
2. `--model` doesn't seem to do anything nor is it validated (we have an issue for the validation)
3. `--model-path` in `ilab serve` should update `config.serve.model_path` so that the next chat uses the proper value

**Comment by nathan-weinberg** [comment]
@cdoern is this still relevant or can it be closed?
