### ISSUE TITLE
Container ships build dependencies

### ISSUE THREAD

**Issue by fabiendupont** [instructlab/instructlab#899]
The Containerfile for CUDA is a single stage based on CUDA devel image, which contains all the NVIDIA development files, on top of which we add compilers. The final image weighs 16.4 GB, which is massive. It would be more user and planet friendly to have an optimized image.

**Comment by nathan-weinberg** [comment]
@fabiendupont @tiran Hi, should #932 be closed in favor of #994?

**Comment by nathan-weinberg** [comment]
Removing `stale` since this is actively being worked on by @fabiendupont
