### ISSUE TITLE
Implement granular logging level in config

### ISSUE THREAD

**Issue by leseb** [instructlab/instructlab#905]
The project uses a few libraries that have their own logging. Currently, we can only control our own from the config. It will be great to allow setting log level for other libs such as openai and httpx.

Related to https://github.com/instructlab/instructlab/pull/872

**Comment by alimaredia** [comment]
@leseb https://github.com/instructlab/instructlab/pull/924 is just the start of this right? I'm guessing you have a plan to break logging down section by section in the config somehow?

**Comment by leseb** [comment]
I'll tackle this once https://github.com/instructlab/instructlab/pull/1092 is merged.

**Comment by leseb** [comment]
Now waiting for https://github.com/instructlab/instructlab/pull/1134

**Comment by leseb** [comment]
Removing myself from this, it's not large and a good candidate for newcomers.
The idea is to add more log statements in the config.

Today we have:

```
general:
  log_level: DEBUG
```

We could add `openapi_log_level` and `httpx_log_level`, then modify:

```
logging.getLogger("openai").setLevel(logging.ERROR)
logging.getLogger("httpx").setLevel(logging.ERROR)
```

From lab.py, to handle the level that was set in the config.

**Comment by ktam3** [comment]
@leseb is this related to the logging work you're doing? #2084 

also, we may want to consider creating a logging 'epic' and include all the logging work you've been doing there!
