### ISSUE TITLE
ilab chat displays wrong model in the header

### ISSUE THREAD

**Issue by gshipley** [instructlab/instructlab#911]
Given the following 'ilab serve' command:

`ilab serve --model-path ./ibm-merlinite-7b-mlx-q-fused-pt/ggml-model-f16.gguf`

It is expected that the 'ilab chat' command would display the correct value in the header. However, it displays the following:

`
╭───────────────────────────────────────────────╮

│ Welcome to Chat CLI w/ MERLINITE-7B-Q4_K_M (type /h for help)                                                                                                                                                   │
`

**Comment by leseb** [comment]
As far as I can tell the client and serve do not negotiate the name of the model provided by the server.
I can work on this, can someone assign it to me? 

Thanks!
