### ISSUE TITLE
ilab init can't clone taxonomy without ssh keys set

### ISSUE THREAD

**Issue by derekhiggins** [instructlab/instructlab#914]
ssh keys are no longer required, we can clone over ssh and avoid

```
Cloning [git@github.com](mailto:git@github.com):instructlab/taxonomy.git...
Failed to clone taxonomy repo: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --branch=main -- [git@github.com](mailto:git@github.com):instructlab/taxonomy.git taxonomy
  stderr: 'Cloning into 'taxonomy'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
'
```

**Comment by bjhargrave** [comment]
I made a fix in #913 

https://github.com/instructlab/instructlab/pull/913/files#diff-c0d3c760847b4e8ff4fd34f5e4bbd46c4f1e2b14ea26e9addb1dab2fec0473c7R15 

to use the https URL.

**Comment by derekhiggins** [comment]
> I made a fix in #913
> 
> https://github.com/instructlab/instructlab/pull/913/files#diff-c0d3c760847b4e8ff4fd34f5e4bbd46c4f1e2b14ea26e9addb1dab2fec0473c7R15
> 
> to use the https URL.

Ack, sorry I hadn't noticed, do you expect that to merge reasonably quickly ? if so I'll close this

**Comment by bjhargrave** [comment]
I don't know how quick. Leave your PR open since you smartly included doc changes. Once of us will need to rebase :-)

**Comment by derekhiggins** [comment]
> I don't know how quick. Leave your PR open since you smartly included doc changes. Once of us will need to rebase :-)

ok, will reopen, and close again if it doesn't make it :-)
