### ISSUE TITLE
Improve error message for too few examples provided

### ISSUE THREAD

**Issue by sroecker** [instructlab/instructlab#936]
If you create a new skill (or modify any of the existing ones) and add less than 5 examples check fails with an error message like this:

```
$ ilab diff
compositional_skills/writing/freeform/poetry/haiku/qna.yaml
ERROR 2024-04-19 14:24:55,912 generate_data.py:636 Validation error in compositional_skills/writing/freeform/poetry/haiku/qna.yaml on .seed_examples: [ <parsed dict> ] is too short
```
It is not clear what is too short. It would be helpful to output "list is too short" or "too few examples, you need to provide a minimum of five.".

**Comment by bjhargrave** [comment]
I improved this message in the taxonomy repo action:

https://github.com/instructlab/taxonomy/blob/c7e15430012d375a4a9a1c0dbf3925e0c68e11b6/.github/scripts/check-yaml.py#L204-L209

I just need to bring this over to the cli command.

**Comment by sroecker** [comment]
Ah perfect, I was wondering where it's from.
