### ISSUE TITLE
Isolate unit test file system for each test case using an implicit fixture

### ISSUE THREAD

**Issue by booxter** [instructlab/instructlab#963]
There's a patch to fix one of test cases that missed isolated_filesystem() context manager: https://github.com/instructlab/instructlab/pull/962

The patch fixes the immediate failure, but leaves the window open for the situation to happen in the future for another new test case. Ideally, the test suite would enforce a new file system structure for every test case in the test class(es). This issue is to build such mechanism, as a fixture or otherwise.

**Comment by nathan-weinberg** [comment]
This strikes me as something still work doing - wdyt @booxter?

**Comment by booxter** [comment]
@nathan-weinberg I think no. The patch was sent https://github.com/instructlab/instructlab/pull/1121 but was rejected with the rationale that this isolation will have to be requested explicitly (via a pytest fixture passed through test function argument) when needed.
