### ISSUE TITLE
Knowledge documents with very long lines do not get chunked properly

### ISSUE THREAD

**Issue by bbrowning** [instructlab/instructlab#968]
We only chunk knowledge documents on newlines at https://github.com/instructlab/instructlab/blob/fd1be3f2ae2bb4ea90822566de58651122de1537/src/instructlab/utils.py#L259

In testing some more real-world use-cases, I'm running across knowledge documents that have some very long lines. These documents are converted to markdown from other systems, and in some cases have stacktraces, very long absolute paths with filenames, and so on that leads to very long lines. When a document chunk with one of these long lines gets selected, we still blow up the context window with errors like `Exception: Requested tokens (4488) exceed context window of 4096`

Should we chunk on something besides newline tokens? Should we check our chunk sizes after chunking and drop any chunks that are too large with a warning? Do we not change anything and just document a maximum line length?

I think the cleanest solution is to check the chunk sizes after we've split them and drop any chunks that are above our threshold with a warning that the file contains very long lines that will get skipped or something of the sort. I'm happy to hear thoughts from others about the best way to handle this.

**Comment by bbrowning** [comment]
Actually, the best thing may be to enable splitting on spaces as well. The splits are in priority order, so we'll only split on spaces if we couldn't create small enough chunks by splitting on paragraphs or newlines.

**Comment by aartij22** [comment]
@bbrowning Have you tried changing the chunk_word_count? Default is set to 1000.

Additionally, I agree that we should revise the chunking logic. Initial approach was to chunk on new line characters to preserve the sentence integrity. As a starting point, we can introduce spaces and then explore other chunking methods that LangChain provides.

**Comment by bbrowning** [comment]
In my example case, a single long line is over our entire max context size so it has to get chunked somehow or error. #969  still preserves chunking on paragraphs and newlines but also adds spaces. LangChain's splitter tries these in-order, so it will only fall back to using spaces for very long chunks that cannot be split small enough based on paragraphs or newlines.

My specific case is with some documents converted into markdown from another system, and I can't assume all the lines are nice and short in the markdown document. So, this is an attempt to make the chunking a bit more resilient to document formatting.
