### ISSUE TITLE
Knowledge documents with very long words do not get chunked properly

### ISSUE THREAD

**Issue by bbrowning** [instructlab/instructlab#975]
As a follow-up to #968, I also discovered that documents with very long words (such as 2000 characters in a row with no newlines or spaces in between) do not get chunked properly.

The fix in #969 will not fix this issue, and opening this one separately to discuss long words and whether we want to fix these, throw a fatal error during generation and stop the entire process like we do today, or perhaps log a warning and ignore chunks like this during generation without aborting the entire generation run.

**Comment by bbrowning** [comment]
The chunking code has all moved over to the instructlab/sdg repository, and has been tweaked in such a way that I don't think it will choke on knowledge documents that have very long words (ie consecutive text with no whitespace). I haven't personally tested that since the sdg repo got factored out and the pipelines concept added over there, but I suspect this is no longer an issue or if it is would be different enough to warrant creating an entirely new issue in that repo vs this one.

**Comment by nathan-weinberg** [comment]
Sounds good, thanks @bbrowning - given that I'm going to close this, we can reopen in https://github.com/instructlab/sdg if it's still an issue
