### ISSUE TITLE
`ilab generate` fails with schema errors when used with existing skills in the instructlab/taxonomy repo

### ISSUE THREAD

**Issue by bbrowning** [instructlab/instructlab#989]
We validate the yaml files match our linting rules (line length, required attribution, etc) during `ilab generate`. Some of the merged skills and knowledge in the instructlab/taxonomy repository were merged before all of the linting was in place, and are not valid by today's standards. We need some way to tell `ilab generate` to ignore yaml validation errors or some versioning in place between the schema, CLI, and taxonomy files so that each change to our linting rules is a new schema version and we can properly handle older taxonomy files done with looser linting compared to newer taxonomy files with different linting rules.

Example of the error I get today pointing the CLI at some existing knowledge in the merged taxonomy repo:

```
$ ilab generate --taxonomy-path taxonomy/knowledge/textbook/history/ibm_history/qna.yaml
...
INFO 2024-04-24 18:12:31,333 _client.py:1026 HTTP Request: GET http://127.0.0.1:8000/v1/models "HTTP/1.1 200 OK"
Generating synthetic data using 'merlinite-7b-lab-Q4_K_M' model, taxonomy:'taxonomy/knowledge/textbook/history/ibm_history/qna.yaml' against http://127.0.0.1:8000/v1 server
ERROR 2024-04-24 18:12:31,421 utils.py:462 Problems found in file taxonomy/knowledge/textbook/history/ibm_history/qna.yaml
36:121: [warning] line too long (314 > 120 characters) (line-length)
39:121: [warning] line too long (363 > 120 characters) (line-length)
42:121: [warning] line too long (410 > 120 characters) (line-length)
```

**Comment by bjhargrave** [comment]
It is not just linting which is more strict than in the past. It is also the schema. Some older yaml files have empty task descriptions which is currently not allowed.

The code in the cli is ready to add support for new schema versions. We could change the schema to define a new relaxed schema as version 1 (includes yaml files without version key) and move the current schema as version 2 (yaml files must have `version: 2`). We can use this version to define more relaxed/no linting standards for version 1. We would then require all new contributions in taxonomy repo to conform to the highest schema version currently in effect to make sure new contributions meet the latest standards for linting and schema validation. This would then allow the cli to consume the older yaml without complaint while allowing the taxonomy repo contribution process to require the latest standards.

**Comment by bbrowning** [comment]
I'm open to the idea that I might be doing things wrong by pointing `ilab generate` at existing known-good skills. But, as we think about the lifecycle of taxonomy and the CLI, any time we add a new linting rule to `ilab`, all existing skill yamls may immediately become invalid and unusable with `ilab generate` from one version to the next unless we have some kind of versioning scheme.

**Comment by bbrowning** [comment]
> It is not just linting which is more strict than in the past. It is also the schema.

I updated the title to say schema instead of linting, as you're right it's not just the linting. Thanks!

**Comment by bjhargrave** [comment]
OK, I have all the work done which is 3 PRs:

schema: https://github.com/instructlab/schema/pull/11
instructlab: https://github.com/instructlab/instructlab/pull/1009
taxonomy: https://github.com/instructlab/taxonomy/pull/769

To proceed, the schema PR needs to be merged first and then the other two PRs updated to use the new commit SHA containing the schema updates.
